### PR TITLE
Reland "[aot inductor] Move constant loading logic from Container to Model"

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112197

Trying again, hopefully with 100% fewer merge conflicts

Original diff: D50582959
Revert diff: D50657400

Differential Revision: [D50710815](https://our.internmc.facebook.com/intern/diff/D50710815/)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by chenyang78** [comment]
Hmm, based on the test names, seems some accuracy failures are related to this change.

**Review by desertfire — APPROVED** [review]

**Review by chenyang78 — APPROVED** [review]

**Comment by bertmaher** [comment]
@bertmaher has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50710815).

**Pull request closed without merging**
