### PR TITLE
Move SingletonSymNodeImpl from c10 to aten

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #114380
* #114971
* #114970
* #114969
* #114897
* #115748
* #115739
* __->__ #114895

### CODE REVIEW

**Comment by soulitzer** [comment]
TODO: actually update the namespace

**Review by jbschlosser — APPROVED** [review]
You're moving this to ATen because the idea is that `SingletonSymNode`s will store tensor data on them, is that right?

It's a bit strange to separate `SingletonSymNode` from the related `Sym*` in `c10/core`, but I'm good with it as long as everything passes :) Might be good to get someone else who knows dynamic shapes to sign off on this as well.

**Comment by soulitzer** [comment]
> You're moving this to ATen because the idea is that SingletonSymNodes will store tensor data on them, is that right?

Yup

> It's a bit strange to separate SingletonSymNode from the related Sym* in c10/core

It seems that moving Sym* would require moving quite a few unrelated pieces from c10 to aten. Not sure if we would want to do that.

cc @Chillee @voznesenskym

**Comment by jbschlosser** [comment]
> It seems that moving Sym* would require moving quite a few unrelated pieces from c10 to aten. Not sure if we would want to do that.

I was more thinking that perhaps we should keep SingletonSymNodeImpl where it is somehow, but eh

**Comment by soulitzer** [comment]
Ah well too late :) 
At least its more flexible this way. If we figure out how to not have to store tensor in SingletonSymNodeImpl later, we can always move it back.

**Pull request closed without merging**
