### PR TITLE
fix torchrun script for custom device

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #ISSUE_NUMBER
as the title,add torchrun support for custom device

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

### CODE REVIEW

**Review by kumpera — APPROVED** [review]
LGTM

**Comment by kit1980** [comment]
@heidongxianhua merge?

**Comment by heidongxianhua** [comment]
> @heidongxianhua merge?

yeah, sorry, I found there maybe have a bug for custom device, I need some tests before merge. @kit1980

**Pull request closed without merging**
