### PR TITLE
Allow batch sizes > 65535 for inverse, solve, cholesky_solve and tria…

### LINKED ISSUE #13276: Memory error for batched inverse
## 🐛 Bug

There seems to be a limit of N=256x256 for the number of batches one can invert on the gpu. I don't think this limit corresponds properly to available memory. Because I can run a N=256x256 -1 batched inverse on a gpu with less availiable memory. I have tested tensorflow on google collab and it allows batched inverse of size N=6144x6144.

## To Reproduce

```
import torch
N = 256
x = torch.randn(N*N , 2, 2).cuda()
y = torch.inverse(x)
print(y.cpu().numpy())
```

Error:

> ----> 1 y.cpu().numpy()
> 
> RuntimeError: cuda runtime error (9) : invalid configuration argument at /opt/conda/conda-bld/pytorch-nightly_1540802486426/work/aten/src/THC/THCTensorCopy.cu:205

## Expected behavior
It works if I reduce the batch dimension by one.
`x = torch.randn(N*N -1 , 2, 2).cuda()
`
## Environment

> PyTorch version: 1.0.0.dev20181029
> Is debug build: No
> CUDA used to build PyTorch: 8.0.61
> 
> OS: Ubuntu 16.04.4 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
> CMake version: version 3.11.0
> 
> Python version: 3.6
> Is CUDA available: Yes
> CUDA runtime version: 9.1.85
> GPU models and configuration: 
> GPU 0: GeForce GTX 1080
> GPU 1: GeForce GTX 1080
> 
> Nvidia driver version: 387.26
> cuDNN version: Probably one of the following:
> /usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7
> /usr/local/cuda-9.1/lib64/libcudnn.so
> /usr/local/cuda-9.1/lib64/libcudnn.so.7
> /usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
> /usr/local/cuda-9.1/lib64/libcudnn.so.7.1.1
> /usr/local/cuda-9.1/lib64/libcudnn_static.a
> 
> Versions of relevant libraries:
> [pip] Could not collect
> [conda] cuda80                    1.0                           0    soumith
> [conda] cuda91                    1.0                  h4c16780_0    pytorch
> [conda] guided-filter-pytorch     1.1.1                     <pip>
> [conda] magma-cuda91              2.3.0                         1    pytorch
> [conda] pytorch-nightly           1.0.0.dev20181029 py3.6_cuda8.0.61_cudnn7.1.2_0  [cuda80]  pytorch
> [conda] torch                     0.4.0                     <pip>
> [conda] torch                     0.3.1                     <pip>

### LINKED ISSUE #21643: torch.solve in GPU fails when batch > 65535
## 🐛 Bug

`torch.solve` in GPU tensor fails when the batch size of the tensors > 65535, and throws a `RuntimeError: CUDA error: invalid configuration argument `. Interestingly, if you run the `torch.solve` multiple times, it will occasionally pass (but with wrong results). See the reproducing code.

## To Reproduce

```python
import torch

def test(batch_size):
    mat = torch.randn(batch_size, 12, 12)
    vec = torch.randn(batch_size, 12, 1)

    res, _ = torch.solve(vec, mat)
    print("CPU res: {}".format(torch.norm(torch.bmm(mat,res) - vec)))

    mat = mat.cuda()
    vec = vec.cuda()

    res, _ = torch.solve(vec, mat)
    res, _ = torch.solve(vec, mat)
    print("GPU res: {}".format(torch.norm(torch.bmm(mat,res) - vec)))

test(batch_size=65535)
print()
test(batch_size=65536)
```
It will output
```
CPU res: 0.07957195490598679
GPU res: 0.09418904036283493

CPU res: 0.06375715881586075
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    test(batch_size=65536)
  File "test.py", line 14, in test
    res, _ = torch.solve(vec, mat)
RuntimeError: CUDA error: invalid configuration argument
```

if you execute multiple times like this
```python
import torch

def test(batch_size):
    mat = torch.randn(batch_size, 12, 12)
    vec = torch.randn(batch_size, 12, 1)

    res, _ = torch.solve(vec, mat)
    print("CPU res: {}".format(torch.norm(torch.bmm(mat,res) - vec)))

    mat = mat.cuda()
    vec = vec.cuda()

    res, _ = torch.solve(vec, mat)
    try:
        res, _ = torch.solve(vec, mat)
    except:
        pass
    print("GPU res: {}".format(torch.norm(torch.bmm(mat,res) - vec)))

test(batch_size=65535)
print()
test(batch_size=65536)
```
You will get
```
CPU res: 0.03482796251773834
GPU res: 0.03578644245862961

CPU res: 0.0608956404030323
GPU res: 3199.743896484375
```

## Environment

```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 418.39
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.5.1

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py37_cu10.0.130_1    pytorch
```

## Additional notes
For now, I use this snippet to get around with the bug. But the runtime becomes similar to that runs on CPU only.
```python
def GPU_solve(As, bs):
    batch_size, N, N = As.shape
    Ws = As.new(size=(*As.shape[:2], 1))
    smb = 65535
    temp_LR = As.new(size=(smb, *As.shape[1:]))
    for i in range(batch_size // smb + 1):
        start = smb * i
        end = smb * (i + 1) if i < batch_size // smb else batch_size
        torch.solve(bs[start:end], As[start:end], out=(Ws[start:end], temp_LR[0:end-start]))
    return Ws
```

Suspect this issue relates to [this issue](https://github.com/pytorch/pytorch/pull/21067)

### PR DESCRIPTION
**Pull request by vishwakftw**
…ngular_solve

Changelog:
- Iterate over mini batches of 65535 matrices (maximum)

Test Plan:
- Added slow tests to test the behavior in test_torch and test_cuda

Fixes #21643 and fixes #13276

### CODE REVIEW

**Comment by vishwakftw** [comment]
cc: @YurongYou @MarcoForte

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
test failures are legit

**Comment by vishwakftw** [comment]
@soumith all CUDA tests pass.

**Comment by soumith** [comment]
thank you!

**Pull request closed without merging**
