### PR TITLE
fix torch.norm for custom device

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #ISSUE_NUMBER
as title, fix torch.norm for custom device

### CODE REVIEW

**Comment by heidongxianhua** [comment]
> `torch.norm` is deprecated and may be removed in a future PyTorch release. Its documentation and behavior may be incorrect, and it is no longer actively maintained: https://pytorch.org/docs/stable/generated/torch.norm.html
> 
> Is this fix applicable/needed for `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`?

yeah, the purpose of this PR is to fix these operators like `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`. @kit1980

**Comment by kit1980** [comment]
> > `torch.norm` is deprecated and may be removed in a future PyTorch release. Its documentation and behavior may be incorrect, and it is no longer actively maintained: https://pytorch.org/docs/stable/generated/torch.norm.html
> > Is this fix applicable/needed for `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`?
> 
> yeah, the purpose of this PR is to fix these operators like `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`.

I don't understand. Is this PR affecting `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`?

**Comment by heidongxianhua** [comment]
> > > `torch.norm` is deprecated and may be removed in a future PyTorch release. Its documentation and behavior may be incorrect, and it is no longer actively maintained: https://pytorch.org/docs/stable/generated/torch.norm.html
> > > Is this fix applicable/needed for `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`?
> > 
> > 
> > yeah, the purpose of this PR is to fix these operators like `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`.
> 
> I don't understand. Is this PR affecting `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`?

As for custom-device, we now support these operators,  `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`, so we want to go directly to this judgment branch, and don't go to other branches for dense tensors, just like cuda device. @kit1980

**Comment by kit1980** [comment]
@heidongxianhua Is this PR affecting `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`? Yes or no?

**Comment by heidongxianhua** [comment]
> @heidongxianhua Is this PR affecting `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`? Yes or no?
no, it won't affect these operators. @kit1980

**Comment by kit1980** [comment]
@heidongxianhua is the similar change needed for `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`?

**Comment by heidongxianhua** [comment]
> @heidongxianhua is the similar change needed for `torch.linalg.vector_norm`, `torch.linalg.matrix_norm`, `torch.linalg.norm`?

no, we just only need this PR change. @kit1980

**Review by lezcano — COMMENTED** [review]
This seems reasonable to me, but let's wait for @ezyang's review in case he has anything to say.

**Review by ezyang — APPROVED** [review]
okey dokey

**Pull request closed without merging**
