### PR TITLE
Get ARC jobs to run on both classic and ARC infra

### PR DESCRIPTION
**Pull request by ZainRizvi**
ARC jobs are too unstable right now.

We're going to mitigate this by:

- Reverting ARC jobs to run on the classic infra (https://github.com/pytorch/pytorch/pull/124748)
- Spin up new jobs in parallel to run on the new infra. (this PR)
- Mark these ARC jobs as unstable (will be done before merging this PR)

More details in https://github.com/pytorch/ci-infra/issues/149

### CODE REVIEW

**Review by zxiiro — APPROVED** [review]

**Comment by seemethere** [comment]
How are these actually marked as unstable?

**Review by seemethere — APPROVED** [review]

**Comment by ZainRizvi** [comment]
> How are these actually marked as unstable?

They're not marked as unstable yet (I'll make sure that happens before merging this PR)

I'm currently looking into how exactly that part is done.  It'll be one of the following:
- I'll creating issues for each job that mark them as unstable 
- If that doesn't work, then I'll manually move this to the unstable.yml workflow instead

**Comment by kit1980** [comment]
> If that doesn't work, then I'll manually move this to the unstable.yml workflow instead

I'd suggest to just put the jobs into unstable.yml from the beginning.
The issue mechanism is good for doing things fast for oncalls, but for this kind of changes I think normal files in CI are much better.

**Comment by ZainRizvi** [comment]
> I'd suggest to just put the jobs into unstable.yml from the beginning. The issue mechanism is good for doing things fast for oncalls, but for this kind of changes I think normal files in CI are much better.

Yeah, that makes sense for now while we know the jobs don't work too well. When we have more faith in ARC and it's time to properly enable the jobs in prod again we can switch to using issues as part of a deployment plan

**Pull request closed without merging**
