### PR TITLE
[ROCm] Upgrade CI to ROCm 1.9.2

### PR DESCRIPTION
**Pull request by iotamudelta**
Drop custom hcc/hip as the 1.9.2 release should contain the relevant patches therein.

Most notable feature in 1.9.2 is mixed precision support in rocBLAS and MIOpen. These features will be enabled by subsequent PRs.

@bddppq @ezyang

### CODE REVIEW

**Comment by bddppq** [comment]
@iotamudelta I think the next step is you to update the packages repo link?

**Comment by iotamudelta** [comment]
@bddppq the repos are already updated in this patch to 1.9.2?

**Comment by bddppq** [comment]
@iotamudelta But I thought we are going to use the pre-release 1.9.2++ in the CI?

**Comment by iotamudelta** [comment]
@bddppq we were under the impression you wanted to evaluate that step only after the CI nodes had been upgraded to 1.9.2

**Comment by bddppq** [comment]
@iotamudelta Oh looks like there are misunderstanding between us, the steps I have in mind are:
1. build docker images with the desired rocm version
2. take couple CI boxes offline and upgrade their rocm version
3. test the docker images produced in 1. on boxes taken offline in 2. (if something goes wrong we iterate)
4. upgrade all the CI boxes to the new rocm version and change all the jenkins jobs to use the new docker images

**Comment by iotamudelta** [comment]
@bddppq no worries, will let people know to release packages and update this PR tomorrow to pull them in.

**Comment by bddppq** [comment]
new docker images build: https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/234/

**Comment by bddppq** [comment]
New docker images build with "sudo" fix https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/236

**Comment by bddppq** [comment]
Triggered rocm builds with new docker images:
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/9261/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/2264/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/9273/

**Review by bddppq — APPROVED** [review]

**Pull request closed without merging**
