### PR TITLE
Fix for incorrect usage of logging in torch/distributed/distributed_c10d.py

### LINKED ISSUE #51428: init_process_group changes the behavior of logging
When running init_process_group, Python library's logging is changed, as I show in the screenshot
Screenshot from 2021-01-31 10-17-57
This happens when I was using OpenSelfSup, a library made by CUHK, and the log disappeared. Because the framework use 'hasHandlers' function to judge whether the logging level is 'WARNING' or 'INFO', this behavior makes the logger level be 'WARNING' , all 'INFO' disappeared.
I don't know this is a bug or I did things wrong,
When I changed the source code version to 1.7.1 and recompile it again, this behavior was fixed.

# Enviroment
pytorch version: compiled from source, master branch
CUDA used to build Pytorch: 11.2
Python: 3.8.5
OS: ubuntu 2004
GPU: GeForce RTX 3090

Thanks so much for your attention.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

### PR DESCRIPTION
**Pull request by szmigacz**
Fixes #51428

### CODE REVIEW

**Comment by ngimel** [comment]
Can you add a test for this behavior, similar maybe to failing case in #51428?

**Comment by szmigacz** [comment]
I added a simple unit test, I'm not sure if I picked the best location for this test case, please verify.

**Review by pritamdamania87 — APPROVED** [review]
Thanks for fixing this!

**Comment by H-Huang** [comment]
This PR broke [flake8 CI test](https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master) due to `import logging` being defined twice, so I am reverting. 

@szmigacz could you rebase and resubmit this PR?

**Pull request closed without merging**
