### PR TITLE
Add objective-c language support in CMake

### LINKED ISSUE #80018: `USE_PRECOMPILED_HEADERS` is not supported on Apple M1
### 🐛 Describe the bug

I set `USE_PRECOMPILED_HEADERS` on and built PyTorch from source, errors occurred due to the following lines:

`error: Objective-C was disabled in PCH file but is currently enabled`

https://github.com/pytorch/pytorch/blob/7751ed41a6f81041c7eb0b21f45ac96a8bebe7dd/caffe2/CMakeLists.txt#L838-L840

### Versions

```
PyTorch version: 1.13.0a0+git44764f1
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] torch==1.13.0a0+git44764f1
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.13.0a0+git44764f1           dev_0    <develop>
```

cc @malfet @seemethere

### PR DESCRIPTION
**Pull request by qqaatw**
Fixes #80018

Local build on my machine looks fine.

cc @albanD @peterbell10

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks for sending a PR for this!

**Comment by albanD** [comment]
ios job is flaky from asking. So ignoring it.

**Comment by linbinyu** [comment]
I don't know why but it did break the test. Fix in https://github.com/pytorch/pytorch/pull/80554. Ideally we want core ML build also working on Apple M1 so there might be a better way to fix it. cc @qqaatw

**Comment by qqaatw** [comment]
Hi @malfet, thanks for the comment and suggestion.

I think the context of the motivation and why I sent this PR have been already provided by the linked issue.

For the explanation of `enable_language(objcxx)`'s effect: I'm not an expert of CMake and have unfortunately no time to dive into CMake's source code to find out all the ramification. As a result, I took the suggestion from this [comment](https://github.com/pytorch/pytorch/issues/80018#issuecomment-1166262712) and also checked out the [doc](https://cmake.org/cmake/help/latest/command/enable_language.html), which looked benign to me to propose a PR without guarded by `USE_PRECOMPILED_HEADERS`.

After all, the build failure indeed happened, which was unexpected. If the expectation to PR senders is having extensive knowledge about all the changes proposed, maybe not sending this PR is the safest solution partly because the redress proposed here #80554 was not considered, and the PR got reverted directly.

Otherwise, the following is a good suggestion, thank you.

> And as precompiled headers are opt in feature, perhaps a safer solution would be to guard it behind USE_PRECOMPILED_HEADERS and DARWIN or something like that?

**Comment by albanD** [comment]
@malfet it does seem like enabling this language is needed to be able to use precompiled headers in conjunction with objc code ([forum post](https://discourse.cmake.org/t/target-precompile-headers-with-macos-and-objective-c-mm-files/3205/3)).
I also though this is a rather simple change but I guess this makes sense.

I think we only use objc when using either `USE_MPS` or `USE_METAL` so maybe we should guard adding the language on either of these flags.
@malfet would you be ok with an updated version of this PR with these extra checks?

**Pull request closed without merging**
