### PR TITLE
[Quant][BC-breaking] Change arg order of conv_transposeNd_prepack to align with corresponding conv_transposeNd functional op

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97936

**Summary**
Change arg order of `conv_transposeNd_prepack` to align with corresponding `conv_transposeNd` functional op. The order of last two args (`dilation, groups`) are changed while others are intact.
- Original arg order of conv_transposeNd_prepack: `{w, b, stride, padding, output_padding, dilation, groups}`
- Arg order of functional ops: `{x, w, b, stride, padding, output_padding, groups, dilation}`
- Arg order of prepack ops after this PR: `{w, b, stride, padding, output_padding, groups, dilation}`

**BC-breaking notes**
As the arg order is changed, users will have to swap the two args when calling these prepack ops. If users have not specified these two args or have specified by `kwargs` instead of positional, no action is required.
Affected ops:
- torch.ops.quantized.conv_transpose1d_prepack
- torch.ops.quantized.conv_transpose2d_prepack
- torch.ops.quantized.conv_transpose3d_prepack
- torch.ops._quantized.conv_transpose1d_prepack
- torch.ops._quantized.conv_transpose2d_prepack
- torch.ops._quantized.conv_transpose3d_prepack

Before:
```python
w_packed = torch.ops.quantized.conv_transposeNd_prepack(w, b, stride, padding, output_padding, dilation, groups)
qy = torch.ops.quantized.conv_transposeNd(qx, w_packed, y_scale, y_zp)
```
after
```python
w_packed = torch.ops.quantized.conv_transposeNd_prepack(w, b, stride, padding, output_padding, groups, dilation)
qy = torch.ops.quantized.conv_transposeNd(qx, w_packed, y_scale, y_zp)
```

**Test plan**
python test/test_quantization.py

cc @ezyang @gchanan @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

Differential Revision: [D45381772](https://our.internmc.facebook.com/intern/diff/D45381772)

### CODE REVIEW

**Comment by Xia-Weiwen** [comment]
> please write a summary and bc-breaking note

Thanks. They are added.

**Review by jgong5 — APPROVED** [review]
LGTM.

**Comment by jerryzh168** [comment]
> > please write a summary and bc-breaking note
> 
> Thanks. They are added.

thanks please use this format for bc-breaking notes: https://github.com/pytorch/pytorch/pull/77608, basically we need a section for Before and a section for After to describe what is changed

**Comment by Xia-Weiwen** [comment]
> > > please write a summary and bc-breaking note
> > 
> > 
> > Thanks. They are added.
> 
> thanks please use this format for bc-breaking notes: #77608, basically we need a section for Before and a section for After to describe what is changed

Thanks. I have modified that part. Please take a look again.

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168  Please take a look. What should I do to fix the broken trunk issue? Thanks.

**Comment by Xia-Weiwen** [comment]
> Hi @jerryzh168 Please take a look. What should I do to fix the broken trunk issue? Thanks.

Please take a look. Thanks.

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168 It's been a while since last update. Could you please take a look?

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168 Could you please take a look? Thanks.

**Comment by jerryzh168** [comment]
cc @kimishpatel will this break edge models?

**Comment by kimishpatel** [comment]
> Change arg order of `conv_transposeNd_prepack` to align with corresponding `conv_transposeNd` functional op. The order of last two args (`dilation, groups`) are changed while others are intact.

Since serialization format has not changed, it may not impact significantly. But I wont be surprised if there is some model that has not prepack op folded. So I would like to careful landing this. If we do, we will have to try out and ready to revert.

**Comment by jerryzh168** [comment]
OK, let's try landing this then

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45381772).

**Comment by jerryzh168** [comment]
@Xia-Weiwen could you rebase I think there is a rename from master to main recently

**Comment by Xia-Weiwen** [comment]
> @Xia-Weiwen could you rebase? I think there is a rename from master to main recently

Sure. It's done. Now CI checks are running.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45381772).

**Comment by jerryzh168** [comment]
@Xia-Weiwen could you rebase again and land in OSS directly? I didn't see an error in fbcode

**Comment by jerryzh168** [comment]
@Xia-Weiwen oh sorry, I did see an error:
```
quantized::conv_transpose2d_prepack(Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] output_padding, int groups, int[] dilation) -> __torch__.torch.classes.quantized.Conv2dPackedParamsBase:
Expected a value of type 'int' for argument 'groups' but instead found type 'List[int]'.
:
  File "code/__torch__/torch/nn/quantized/modules/conv.py", line 159
    _28 = [_26, _27]
    _29, _30, = dilation
    _31 = ops.quantized.conv_transpose2d_prepack(w, b, _22, _25, _28, [_29, _30], groups)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    self._packed_params = _31
    return None
'ConvTranspose2d.set_weight_bias' is being compiled since it was called from 'ConvTranspose2d.__setstate__'
Serialized   File "code/__torch__/torch/nn/quantized/modules/conv.py", line 135
    self.groups = (state)[8]
    self.padding_mode = (state)[9]
    _19 = (self).set_weight_bias((state)[10], (state)[11], )
                                               ~~~~~~~~~~ <--- HERE
    self.scale = (state)[12]
    self.zero_point = (state)[13]
```

looks like a bc problem in torchscript

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168. May I know the status of this PR? Is it already merged into main?

**Comment by jerryzh168** [comment]
this PR caused some internal failures so it's probably not a good idea to land right now

**Comment by Xia-Weiwen** [comment]
> this PR caused some internal failures so it's probably not a good idea to land right now

I see. Thanks. So, what do you suggest I do? Wait or modify somehow?

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168 Do you think this PR is still needed? What shall we do for it now? Thanks.

**Comment by Xia-Weiwen** [comment]
Close as it breaks Meta internal tests and these ops are becoming deprecated.

**Pull request closed without merging**
