### PR TITLE
enforece dtype

### PR DESCRIPTION
**Pull request by uciyc123**
Summary: Add a flag to enforce the gather data dtype. In case backward compatibility, make the default as False

Test Plan: local and mast

Reviewed By: zyan0, strisunshinewentingwang

Differential Revision: D46295190

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
LGTM!

**Comment by malfet** [comment]
This broke dynamo tests

**Comment by wanchaol** [comment]
> This broke dynamo tests: https://hud.pytorch.org/pytorch/pytorch/commit/8e2a86c2a54719fd66a3e612fe8b433fbb1d4522

Hey @malfet, looking into the failures, it does not seem this PR is correlated to those failures? the failure is the CI is sth related to optimizer iiuc

**Comment by malfet** [comment]
@wanchaol yes, you are right. Please go ahead and resubmit the pr.

**Pull request closed without merging**
