### PR TITLE
Added size checks to batch norm inputs (running_mean, var, weight + bias)

### PR DESCRIPTION
**Pull request by alykhantejani**
Added at the C++ layer in response to issue #378

### CODE REVIEW

**Comment by alykhantejani** [comment]
From the build logs it seems these tests are failing on the osx-cpu run  `distributed tests for the TCP backend`. Any ideas?

**Comment by soumith** [comment]
you  can ignore those

**Comment by alykhantejani** [comment]
Ah ok cool 👍

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
thanks man!

**Pull request merged**
