### PR TITLE
[c10d] Simplify ProcessGroupNCCL into single-device style

### LINKED ISSUE #117756: [c10d] Refactor ProcessGroupNCCL to use single device
### 🚀 The feature, motivation and pitch

After removing the `*_multigpu` python APIs, we can now refactor cpp code in ProcessGroupNCCL to make it simpler.

Without changing the Backend API signature yet, we can do so by simply taking the tensor or device out once we get into a function:
```
auto tensor = tensors[0];
auto device = devices[0];
```

### Alternatives

_No response_

### Additional context

_No response_

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### PR DESCRIPTION
**Pull request by kwen2501**
Resolves #117756

Saves ~45 for loops.
Saves ~100 std::vector.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @gchanan

### CODE REVIEW

**Comment by wconstab** [comment]
this SGTM! a couple thoughts on landing. Should we first land a change that just starts asserting the condition we want to achieve (assert that all those loops/vectors are size 1) and ensure no breakages with minimal code change effort?  Then the remaining PR would literally be dead code removal.  (and could even be landed in a few smaller chunks if its easier to review)

**Comment by kwen2501** [comment]
Thanks, I think that's a good idea. But I also just realized that a lot of our tests were written in `pg.all_reduce([tensors])` style, instead of `dist.all_reduce(tensor)` (the documented way). So, even for assert == 1 to become green, there needs quite some efforts to refactor our tests first.

**Comment by wconstab** [comment]
is this actually a deprecation and a bc cycle kind of thing? (and are you thinking its not worth doing the normal BC process bc we don't think any users are actually using this approach?)

**Comment by kwen2501** [comment]
We actually followed the deprecation process (2 release cycles at least), and recently removed `<coll>_multigpu` APIs from the distributed package. So if the distributed package is used per documentation, the assert == 1 would be true.

The problem is in some of our tests, which used unsupported/documented style.

**Comment by wconstab** [comment]
Ok. So more work...

**Comment by wanchaol** [comment]
This is awesome! I think we should probably try to import this and see if internal tests are happy given this is a large refactor?

**Comment by kwen2501** [comment]
@wconstab @wanchaol breaking this into smaller PRs as you suggested:
First one: #119099

**Comment by kwen2501** [comment]
Closing via https://github.com/pytorch/pytorch/pull/119099 and https://github.com/pytorch/pytorch/pull/119421

**Pull request closed without merging**
