### PR TITLE
Rename `btrifact*` to `lu`

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:

- Renames `btrifact` and `btrifact_with_info` to `lu`to remain consistent with other factorization methods (`qr` and `svd`).
- Now, we will only have one function and methods named `lu`, which performs `lu` decomposition. This function takes a get_infos kwarg, which when set to True includes a infos tensor in the tuple.
- Rename all tests, fix callsites
- Create a tentative alias for `lu` under the name `btrifact` and `btrifact_with_info`, and add a deprecation warning to not promote usage.
- Add the single batch version for `lu` so that users don't have to unsqueeze and squeeze for a single square matrix (see changes in determinant computation in `LinearAlgebra.cpp`)

Test Plan:

- All tests should pass to confirm that the patch is correct.

### CODE REVIEW

**Review by ssnl — COMMENTED** [review]
Nice! I would say that this is a good time to get rid of `lu_with_info` API, and use a keyword arg (e.g., `get_info=False`) of `lu` to dispatch to different method in backend.

**Comment by vishwakftw** [comment]
Do you think returning `None` when `get_info=False` and the info tensor when `get_info=True` is reasonable?

**Comment by vishwakftw** [comment]
I removed my earlier comment due to some discrepancy.

I think that removing `lu_with_info` for a keyword arg sounds good.

> and use a keyword arg (e.g., `get_info=False`) of `lu` to dispatch to different method in backend.

Are you suggesting overriding the behavior of `lu` as done for `unique` in `functional.py`?

**Comment by vishwakftw** [comment]
Otherwise, we could always return `infos` (in a 3-tuple:` LU`, `pivots`, `infos`) in the C++ API, but build the output tuple in Python depending on the value of `get_infos`.

**Comment by ezyang** [comment]
Test failure:

```
Mar 26 06:53:23 ======================================================================
Mar 26 06:53:23 FAIL: test_lu (__main__.TestCuda)
Mar 26 06:53:23 ----------------------------------------------------------------------
Mar 26 06:53:23 Traceback (most recent call last):
Mar 26 06:53:23   File "/var/lib/jenkins/workspace/test/common_utils.py", line 318, in wrapper
Mar 26 06:53:23     method(*args, **kwargs)
Mar 26 06:53:23   File "/var/lib/jenkins/workspace/test/common_utils.py", line 129, in wrapper
Mar 26 06:53:23     fn(*args, **kwargs)
Mar 26 06:53:23   File "test_cuda.py", line 2366, in test_lu
Mar 26 06:53:23     _TestTorchMixin._test_lu(self, lambda t: t.cuda())
Mar 26 06:53:23   File "/var/lib/jenkins/workspace/test/test_torch.py", line 1774, in _test_lu
Mar 26 06:53:23     run_test(ms, batch, cast)
Mar 26 06:53:23   File "/var/lib/jenkins/workspace/test/test_torch.py", line 1768, in run_test
Mar 26 06:53:23     self.assertIsNone(nopiv)
Mar 26 06:53:23 AssertionError: tensor([0, 0, 0], device='cuda:0', dtype=torch.int32) is not None
Mar 26 06:53:23 
Mar 26 06:53:23 ----------------------------------------------------------------------
```

**Comment by vishwakftw** [comment]
My bad, fixing it now.

**Comment by vishwakftw** [comment]
I have a local patch that removes the lu_with_info function and add the get_infos argument in lu. Should I push that or just the fix for the test failures?

**Comment by ezyang** [comment]
@vishwakftw If you like, you can stack the diffs using https://github.com/ezyang/ghstack

Otherwise, do what is easiest for you (but with the caveat that the bigger the diff, the harder it is for us to review ;)

**Comment by vishwakftw** [comment]
@ezyang The patch that I was referring to was rather small, which is why I've amended the commit directly. I'll use ghstack for upcoming PRs (renaming btrisolve and btriunpack).

**Comment by vishwakftw** [comment]
Jenkins tests fail with this error:
```
06:50:11 Running test_docs_coverage ... [2019-03-28 06:50:11.781583]
06:50:11 test_tensor (test_docs_coverage.TestDocCoverage) ... ok
06:50:11 test_torch (test_docs_coverage.TestDocCoverage) ... FAIL
06:50:11 
06:50:11 ======================================================================
06:50:11 FAIL: test_torch (test_docs_coverage.TestDocCoverage)
06:50:11 ----------------------------------------------------------------------
06:50:11 Traceback (most recent call last):
06:50:11   File "/var/lib/jenkins/workspace/test/test_docs_coverage.py", line 67, in test_torch
06:50:11     don't want to document?''')
06:50:11 AssertionError: 
06:50:11 List of functions documented in torch.rst and in python are different.
06:50:11 Do you forget to add new thing to torch.rst, or whitelist things you
06:50:11 don't want to document?
06:50:11 
06:50:11 ----------------------------------------------------------------------
06:50:11 Ran 2 tests in 0.003s
06:50:11 
06:50:11 FAILED (failures=1)
```

CircleCI tests pass instead:
```
Mar 28 05:31:23 Running test_docs_coverage ... [2019-03-28 05:31:23.569080]
Mar 28 05:31:23 test_tensor (__main__.TestDocCoverage) ... ok
Mar 28 05:31:23 test_torch (__main__.TestDocCoverage) ... ok
Mar 28 05:31:23 
Mar 28 05:31:23 ----------------------------------------------------------------------
Mar 28 05:31:23 Ran 2 tests in 0.004s
Mar 28 05:31:23 
Mar 28 05:31:23 OK
```

**Comment by vishwakftw** [comment]
@ezyang @SsnL is this good to go?

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
