### PR TITLE
[Inductor][Quant] Change the QConv output scale name

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #125207
* __->__ #124246
* #124041

**Summary**
Change the name of QConv output scale from `inv_output_scale` to `output_scale` after we move the optimization of quant/dequant from decomposition to lowering phase.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by peterbell10 — COMMENTED** [review]
backward_compat failure is real. Assuming these are internal operators only used by the quantization `fx_passes` though, you can just add an exception.

**Review by jgong5 — APPROVED** [review]

**Comment by leslie-fang-intel** [comment]
> backward_compat failure is real. Assuming these are internal operators only used by the quantization `fx_passes` though, you can just add an exception.

Hi @peterbell10, thanks for the comment. I think they are internal operators only used by the Inductor quantization `fx_passes`. May I know more suggestion about how to add the exception? Did you mean keep the original operators with implementation of just throw exception and add the new operators' schema?

**Comment by leslie-fang-intel** [comment]
I guess I know what did you mean. Modify `check_forward_backward_compatibility.py` to pass the backward_compat testing. Please kindly help to take a look again.

**Comment by leslie-fang-intel** [comment]
Hi @jerryzh168, could you kindly help to take a look of this PR and the previous one per the discussion in https://github.com/pytorch/pytorch/pull/123444?

**Review by peterbell10 — APPROVED** [review]

**Pull request closed without merging**
