### PR TITLE
Remove unused type traits in  torch/csrc/utils

### PR DESCRIPTION
**Pull request by cyyever**
Follows  #127852

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Aren't these technically public API for our cpp API?

**Comment by cyyever** [comment]
But I think they should be replaced by STL trails, and in deed all uses have been replaced.

**Comment by albanD** [comment]
Sure we should migrate, just asking if we did all the checks that there is no more use and assessment if we need a deprecation cycle.

**Comment by cyyever** [comment]
Can't find other uses in GitHub projects. But I don't know if there are still references inside META.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
