### PR TITLE
Fix profiling with record_shapes=True and nested tensor

### PR DESCRIPTION
**Pull request by ngimel**
We probably want more systematic fix for other tensorImpls that don't support sizes (and also there are other places in profiler that call sizes unchecked, which should be fixed), but this is to unblock Transformer profiling.

### CODE REVIEW

**Comment by robieta** [comment]
Is the goal to actually get shapes out, or just to not break? Because if it's the latter I think we should just change
```
if (t.defined()) {
```
to
```
if (t.defined() && !t.is_nested()) {  // TODO: Handle this better
```
The reason is that we're looking at better support in https://github.com/pytorch/pytorch/pull/81824 (currently being refactored to use the underlying data for better overhead) and then we could handle `SizesStridesPolicy` in a fully robust way. WDYT?

**Comment by ngimel** [comment]
Yeah the goal is to just not break, looking forward to proper support.

**Review by robieta — APPROVED** [review]
LGTM. (You'll need to rip out the unit test?)

**Comment by ngimel** [comment]
Unit test passes as it should (nested tensors call regular mm underneath, and regular mm has correct sizes), and I'd rather not rip it out because otherwise #81824 will break nested tensor profiling again.

**Comment by robieta** [comment]
> Unit test passes as it should (nested tensors call regular mm underneath, and regular mm has correct sizes), and I'd rather not rip it out because otherwise #81824 will break nested tensor profiling again.

Gotcha. Thanks for the explanation.

**Pull request closed without merging**
