### PR TITLE
Changed value constraint of exponential dist

### LINKED ISSUE #67183: Exponential distribution constraint should be non-negative rather than positive
## 🐛 Bug

The exponential distribution has a constraint of `support = constraints.positive`, which doesn't allow for a value of zero, even though zero should be a valid value. Instead, the constraint should be `support = constraints.nonnegative`

## To Reproduce

`torch.distributions.Exponential(0.5).log_prob(torch.Tensor([0]))`

The above line of code produces an error:
```
ValueError: Expected value argument (Tensor of shape (1,)) to be within the support (GreaterThan(lower_bound=0.0)) of the distribution Exponential(rate: 0.5), but found invalid values:
tensor([0.])
```

Rather than produce the error, the output should be: `tensor([-0.6931])`

## Environment

PyTorch version: 1.10.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.6rc1 (tags/v3.8.6rc1:08bd63d, Sep  7 2020, 23:10:23) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1650
Nvidia driver version: 462.31
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] torch==1.10.0
[pip3] torchvision==0.11.1
[conda] Could not collect

cc @fritzo @neerajprad @alicanb @nikitaved

### PR DESCRIPTION
**Pull request by JAEarly**
Fixes #67183.

cc @fritzo @neerajprad @alicanb @nikitaved

### CODE REVIEW

**Comment by neerajprad** [comment]
Could you rebase on to the latest master and try again? I think the failures referenced above should be fixed on master.

**Comment by neerajprad** [comment]
Thanks for the fix!

**Comment by JAEarly** [comment]
> Could you rebase on to the latest master and try again? I think the failures referenced above should be fixed on master.

Sure, I've rebased now.

**Review by neerajprad — APPROVED** [review]

**Comment by neerajprad** [comment]
@albanD - For some reason, I'm unable to import this to phabricator. Could you help do that?

**Pull request closed without merging**
