### PR TITLE
Enable record_stack_traces for make_fx

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84001

cc @ezyang @soumith @EikanWang @jgong5 @wenzhe-nrv

### CODE REVIEW

**Comment by SherlockNoMad** [comment]
cc @Chillee, @bdhirsh, @ezyang 

The UT is failing coz make_fx is tracing out an additional aten.detach node in window-only build. 

For this fn
```
        def f(x):
            a = x.clone()
            a_view = a.view(-1)
            # We shouldn't re-inplace the first add(), because an alias of a is re-used later in the program
            b = a.add(1)
            # Second add() is fine to re-inplace
            c = a_view.add(1)
            return c 
````
In my local machine, reinplace(make_fx(f)(inpt), inpt) would produce 

```
def forward(self, x_1):
    clone_default = torch.ops.aten.clone.default(x_1);  x_1 = None
    view_default = torch.ops.aten.view.default(clone_default, [-1])
    add_tensor = torch.ops.aten.add.Tensor(clone_default, 1);  clone_default = None
    add_tensor_1 = torch.ops.aten.add.Tensor(view_default, 1);  view_default = None
    return add_tensor_1
```

On windows build, it's producing a different trace
```
  def forward(self, x_1):
      clone_default = torch.ops.aten.clone.default(x_1);  x_1 = None
      view_default = torch.ops.aten.view.default(clone_default, [-1])
+     detach_default = torch.ops.aten.detach.default(view_default);  view_default = None
      add_tensor = torch.ops.aten.add.Tensor(clone_default, 1);  clone_default = None
-     add_tensor_1 = torch.ops.aten.add_.Tensor(view_default, 1)
-     return view_default
```

It think this is likely coming from make_fx, not reinplacer. Do you have any hint on why this is only happening on window-only build? 

Would turning on tracing affect the computation in any case? Notice here the aten.detach node is taking the output of an View op. Maybe this is view op specific problem ?

**Comment by ezyang** [comment]
My guess is

```
    def _find_user_frame(self):
        """
        Find the Python stack frame executing the user code during
        symbolic tracing.
        """
        # We have to do a little dance here. Basically, walk up the callstack and
        # record the first frame not in the pytorch source. This is the frame executing
        # the user code during tracing.
        frame = inspect.currentframe()

        pt_files = ['torch/fx/proxy.py',
                    'torch/fx/_symbolic_trace.py',
                    'torch/fx/experimental/proxy_tensor.py',
                    'torch/_ops.py',
                    'torch/_tensor.py',
                    'torch/utils/_python_dispatch.py',
                    'torch/_prims_common/wrappers.py',
                    'torch/_refs/__init__.py',
                    'torch/_refs/nn/functional/__init__.py'
                    ]
        while frame:
            frame = frame.f_back
            if frame and all(not frame.f_code.co_filename.endswith(file) for file in pt_files):
                break

        if not frame:
            return None

        return frame
```

doesn't work on Windows where filepaths are backslashes. Not sure why this would wobble the trace though; you'll need to figure that out

**Comment by ezyang** [comment]
Do you need help with the Windows? My local Windows laptop arrived today so I can repro this now easily

**Comment by SherlockNoMad** [comment]
> Do you need help with the Windows? My local Windows laptop arrived today so I can repro this now easily

Yes, would appreciate if can repro this on windows machine.

**Comment by suo** [comment]
can we resuscitate this PR @SherlockNoMad :)

**Pull request closed without merging**
