### PR TITLE
Update XLA pin

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92806

This should allow re-enabling/reverting https://github.com/pytorch/pytorch/commit/3cc103132205820fc0c571e3e68dd5e9b5b85727

### CODE REVIEW

**Comment by kit1980** [comment]
Here is the XLA PR for background https://github.com/pytorch/xla/pull/4490

**Comment by kit1980** [comment]
> Here is the XLA PR for background [pytorch/xla#4490](https://github.com/pytorch/xla/pull/4490)

I've merged the PR. Probably it's better to update to the hash instead of branch_name?

**Review by kit1980 — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Comment by lezcano** [comment]
I removed the `frobenius_norm` branch before this was merged... lol
I've created it again.

**Comment by kit1980** [comment]
> I removed the `frobenius_norm` branch before this was merged... lol I've created it again.

That's one reason I said hash is better.
The nightly job should update the hash anyway, the branch needs to live unchanged before that.

**Comment by huydhn** [comment]
This is so weird. XLA job on the commit fails with a different error https://hud.pytorch.org/pytorch/pytorch/commit/7560660bd349c07f63ca0a5b10dc34492eca84f9 (landrace from https://github.com/pytorch/pytorch/pull/70988 I suspect).  Things move so fast :)

**Comment by kit1980** [comment]
It's likely that https://github.com/pytorch/pytorch/pull/92806 has the same error on trunk? The recorded error it had is timeout.

**Comment by kit1980** [comment]
> It's likely that #92806 has the same error on trunk? The recorded error it had is timeout.

I mean #92806 probably caused the issue independently of this hash update.

**Pull request closed without merging**
