### PR TITLE
unwrap sizevars passed as args

### PR DESCRIPTION
**Pull request by ngimel**
Undoes int arg wrapping that dynamo does
Generated line:
```
s1 = arg2_1.item() if isinstance(arg2_1, torch.Tensor) else arg2_1
```
Fixes #ISSUE_NUMBER

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
I'm okay to merge this to unblock, but it seems like we ought to figure out why Dynamo is passing tensors where ints should be passed. If nothing else, it should be faster not to allocate a full Tensor

**Comment by ezyang** [comment]
Also, we have a pretty easy mini repro, let's add it to the tests

**Comment by ezyang** [comment]
https://hud.pytorch.org/pr/96045 shows we can trigger an assert failure in AOTAutograd too, methinks

**Comment by ngimel** [comment]
@jansel do you know where int -> tensor wrapping takes place?

**Comment by jansel** [comment]
> @jansel do you know where int -> tensor wrapping takes place?

Perhaps here?
https://github.com/pytorch/pytorch/blob/5dd52e250f66a5e3377eb39228cd929871f1eb5d/torch/_dynamo/variables/builder.py#L807

**Comment by ngimel** [comment]
Test added

**Comment by ngimel** [comment]
> > @jansel do you know where int -> tensor wrapping takes place?
> 
> Perhaps here?
> 
> https://github.com/pytorch/pytorch/blob/5dd52e250f66a5e3377eb39228cd929871f1eb5d/torch/_dynamo/variables/builder.py#L807

Tried to set breakpoint there yesterday, never hit it.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
