### PR TITLE
Reshape decomposition for jagged layout NT

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115842
* #115192
* __->__ #115191

No more segfault from using `reshape()` on jagged NT :)

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Review by soulitzer — APPROVED** [review]

**Comment by jbschlosser** [comment]
Discussed offline: we know the decomp doesn't exactly match the dense analogue - there's more logic there involving computeStride() to determine copy vs. view. We're okay with this for now.

**Review by soulitzer — APPROVED** [review]

**Pull request closed without merging**
