### PR TITLE
Increased hardcoded limit for number of GPUs.

### LINKED ISSUE #115331: Please increase "Number of CUDA devices" recognized by pytorch.
### 🚀 The feature, motivation and pitch

```
RuntimeError: Number of CUDA devices on the machine is larger than the compiled max number of gpus expected (16). Increase that and recompile.
```

https://github.com/pytorch/pytorch/blob/main/c10/cuda/CUDAMacros.h

Current macro is set to 16. We have 19 gpus on a single machine. Please increase this value to 32 or better, 2048 for future proofing.  As virtualization of gpu slices become prevalent, 16 is not enough. For example, even a single 8x A100 node can be MIGed  into more than 16 slices. 

### Alternatives

_No response_

### Additional context

_No response_

cc @ptrblck

### PR DESCRIPTION
**Pull request by tringwald**
Fixes #115331.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM!

**Comment by albanD** [comment]
More clearly, it is actually breaking caffe2 testing
I think we should guard this update behind the BUILD_CAFFE2 flag (which is false for PyTorch builds)

**Comment by albanD** [comment]
Thanks!
I'll confirm that this works fine with caffe2 testing and merge after.

**Comment by tringwald** [comment]
I think I broke your internal import with the update @albanD. You might need to re-import.

**Comment by albanD** [comment]
Thanks for the headsup. I'm just importing to test though so that's ok if I don't have the formatting.

**Pull request closed without merging**
