### PR TITLE
[GPT-fast] Support run spcific model or micro-benchmark

### PR DESCRIPTION
**Pull request by yanboliang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #143607

### CODE REVIEW

**Comment by yanboliang** [comment]
@jerryzh168 To enable autoquant models in the future, simply decorate your function with `register_experiment`. This should be sufficient.

**Review by BoyuanFeng — APPROVED** [review]

**Comment by jerryzh168** [comment]
thanks, there is some issues with my integration right now though, I'd really appreciate if you have time to take a look as well: https://github.com/pytorch/pytorch/pull/141910#issuecomment-2549960408

**Review by jerryzh168 — APPROVED** [review]

**Review by huydhn — APPROVED** [review]
LGTM! Sorry for not looking into this earlier, I just double check that the results are showing up correctly on the dashboard https://hud.pytorch.org/benchmark/llms?startTime=Fri%2C%2013%20Dec%202024%2019%3A53%3A56%20GMT&stopTime=Fri%2C%2020%20Dec%202024%2019%3A53%3A56%20GMT&granularity=hour&lBranch=refs/tags/ciflow/inductor-micro-benchmark/143607&lCommit=805a546317ac8792c4c2de763e5941c481fd3953&rBranch=refs/tags/ciflow/inductor-micro-benchmark/143607&rCommit=805a546317ac8792c4c2de763e5941c481fd3953&repoName=pytorch%2Fpytorch&modelName=All%20Models&backendName=All%20Backends&dtypeName=All%20DType&deviceName=All%20Devices

**Pull request closed without merging**
