### PR TITLE
[ROCm] introduce uint24 specializations for index math

### PR DESCRIPTION
**Pull request by iotamudelta**
Introduce the option to do fast 24 bit integer math on ROCm. Unlike 32 or 64bit integer math, this will run at fp32 speed. The former do, in the absence of dedicated int ALUs, run at significantly lower speed.

Introduce a ROCm specific uint24_t struct that correctly masks the bits and defines some operations on 24bit quantities.

Introduce canUse24BitIndexMath functions to check if index math fits into range of uint24_t (or, by default, signed int24).

Introduce for now specializations for index[Add,Select][Large,Small]Index by using said functions and struct.

### CODE REVIEW

**Comment by iotamudelta** [comment]
CC: @gottbrath FYI

**Review by bddppq — COMMENTED** [review]
Could you attach the benchmark code and the corresponding perf numbers?

**Comment by iotamudelta** [comment]
Happy to do so!

Benchmark was PyTorch DLRM - https://github.com/facebookresearch/dlrm . End-to-end time (note that GPU utilization is not good in this benchmark and only the select kernel uses the fast path there due to size!) improves by up to 5% (depending on config) in my tests on a full gfx906 chip.

More relevant is to observe the ISA difference for get vs get24: https://gcc.godbolt.org/z/gpis2W

Which highlights: uint24 means being able to do integer arithmetic at fp32 throughput. This will also translate to other functions/kernels, of course.

Hope this helps!

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 74bc502f:


**None of the build failures appear to be your fault**.

* **1/4** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=a3dd44653fb5ee16ca36428576217460d4fa4886&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base a3dd4465 since Jan 13
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  Since your merge base is older than `viable/strict`, run these commands:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  
* **3/4** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=74bc502f85b320c7d2b03b28530609d94edc5e2e).

### :snowflake: 3 failures recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4300125) pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build (1/3)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=88343407) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=88343407)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4300145) pytorch_linux_xenial_py3_clang5_android_ndk_r19c_mobile_code_analysis (2/3)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=88343435) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=88343435)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4300129) pytorch_linux_xenial_py2_7_9_build (3/3)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=88343436) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=88343436)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py2.7.9:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py2.7.9:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py2.7.9:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_xla_linux_xenial_py3_6_clang7_build](https://dr.pytorch.org/build-details.html?build_id=88343489) from Jan 13 until Jan 13



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by iotamudelta** [comment]
@bddppq ping :-)

**Comment by ngimel** [comment]
We've discussed internally, and the agreement is that it introduced a lot of ROCm specific code for modest perf gains in a more or less niche usecase (tensors with less than 2^24 elements are not common for embedding tables). We prefer not to go forward with this. cc @dzhulgakov @bddppq

**Comment by iotamudelta** [comment]
@ngimel @bddppq @gottbrath I'd like to point out that we've seen relevant applications where this constitutes a performance uplift. Also note that this could apply to CUDA as well - similar HW considerations are in play there.

**Comment by ngimel** [comment]
Nvidia GPUs have full speed int32 throughput.

**Comment by iotamudelta** [comment]
@ngimel AFAIK only Volta has full rate int32 capability?

**Comment by ngimel** [comment]
Yes. Volta is 2 years old, it's not cutting-edge hard-to-come-by hardware by any means, if you are running on older architecture performance of the int indexing is the least of your problems.

**Comment by iotamudelta** [comment]
Thanks for confirming.

**Pull request closed without merging**
