### PR TITLE
[pt2-bench] pass acc test if ref is NaN

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130005
* #129941
* __->__ #129996

I'm debugging the accuracy failure for training vision_maskrcnn.

Unfortunately I could not succeed to run it locally (I've check pined commits for torchbenchmars/torchvision are correct, and reinstalled torchbenchmark for mask_rcnn). I get this error:
```
eager run fail: AssertionError: targets should not be none when in training mode
```
(Command: time python benchmarks/dynamo/torchbench.py --backend inductor --amp --performance --training --only vision_maskrcnn )

But look at the log from the dashboard
```
E0623 19:17:59.085000 140114670171328 torch/_dynamo/utils.py:1468] RMSE (res-fp64): nan, (ref-fp64): nan and shape=torch.Size([1024, 256, 1, 1]). res.dtype: torch.float32, multiplier: 3.000000, tol: 0.001000
```

We can see both the reference number and the pt2 number are NaN. I change torch._dynamo.utils.same to return true if both RMSE values are NaN.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
The users should pass in `equal_nan=True` for this case. Can we add a specific config for vision_maskrnn instead of globally allowing ?  fp in general does not consider nan == nan by default

**Comment by shunting314** [comment]
>  fp in general does not consider nan == nan by default

Agreed. I think the point here is more like: if baseline is NaN, then pt2 result can not be 'worse' than baseline so we make it pass.

I'll only enable this for vision_maskrcnn

**Review by jansel — APPROVED** [review]

**Comment by shunting314** [comment]
>Can we add a specific config for vision_maskrnn instead of globally allowing ?

Our benchmark script already globally enable `equal_nan` for non-fp32 cases (amp/fp16/bf16)
https://github.com/pytorch/pytorch/blob/main/benchmarks/dynamo/common.py#L2263-L2268

I'll just add a check for the flag. No need to specifically enable for visioin_maskrcnn

**Comment by shunting314** [comment]
@jeanschmidt I'll work on fixing the test. But TBH I think our CI can be improved a bit. The test failures causing my PR being reverted falls in the 'UNSTABLE' category. If these tests should not fail, we should make them block merging rather than put then in 'UNSTABLE'

**Pull request closed without merging**
