### PR TITLE
[quant] Remove unused quantize handler definitions

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #83360

Summary:
CommonQuantizeHandler This was added previously to make some of the refactor to use reference quantized model flow easier, now we have
fully migrated to use reference quantized model flow, it's no longer needed, so we can remove it

Also updated some comments

Test Plan:
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps
python test/test_quantization.py TestQuantizeFxModels

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by andrewor14 — APPROVED** [review]
By the way I saw there's another TODO to remove `DefaultNodeQuantizeHandler` as well. What is the longer term plan?

**Comment by jerryzh168** [comment]
> By the way I saw there's another TODO to remove `DefaultNodeQuantizeHandler` as well. What is the longer term plan?

the test can be removed actually, we do not need to use DefaultNodeQuantizeHandler outside of fx codebase.

**Pull request closed without merging**
