### PR TITLE
[ROCm] Enable sparse functionality and tests

### PR DESCRIPTION
**Pull request by iotamudelta**
* Enable sparse functions for ROCm

* Reenable test_sparse unit tests that are now passing in ROCm

@ezyang @bddppq

### CODE REVIEW

**Comment by bddppq** [comment]
triggered tests:
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/423/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/424/

**Comment by iotamudelta** [comment]
test job can be found here: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/432/

**Review by bddppq — APPROVED** [review]
LG

**Pull request closed without merging**
