### PR TITLE
lshift and rshift stop support floating types

### LINKED ISSUE #74358: lshift and rshift are supported for non-integral inputs and shifts
Pytorch quite nonsensically supports rshift/lshift on non-integral inputs and shifts:
```
In [13]: a=torch.randn(4)

In [14]: a.bitwise_right_shift(2) #there's nothing bitwise about this shift
Out[14]: tensor([-0.0470, -0.0847,  0.0964,  0.0141])

In [15]: a.bitwise_right_shift(1.5) #what does this even mean?
Out[15]: tensor([-0.0664, -0.1198,  0.1363,  0.0200])
```
numpy sensibly errors out in these cases

cc @ezyang
cc @mruberry @rgommers @nairbv

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes #74358

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Test failures are real (I don't know what TestLazyOps is doing, must be some silly stuff)

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
xla failure is also real, and they also for some reason testing lshift on float

**Comment by JackCaoG** [comment]
I will draft a xla pr for this.

**Comment by ngimel** [comment]
Thanks! Note that it can (and should) be landed without waiting for this PR, because lshift/rshift should work on integral inputs only.

**Comment by JackCaoG** [comment]
@ngimel XLA PR is merged, we should be good to go for this one.

**Comment by JackCaoG** [comment]
ehh, sorry press the wrong bottom when I tried to comment.

**Comment by zasdfgbnm** [comment]
Adding `topic:bc_breaking` label as floating-point types support was previously mistakenly enabled and is now removed.

**Pull request closed without merging**
