### PR TITLE
Conservatively move all suitable prim ops from full-jit to mobile, and make them selective.

### PR DESCRIPTION
**Pull request by iseeyuan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58353 Conservatively move all suitable prim ops from full-jit to mobile, and make them selective.**

There are long tail operators in register_prim_ops_fulljit.cpp, that may be used in mobile build. In this PR
1. All of the ops that are likely to be used in mobile are moved to register_prim_ops.cpp.
2. Note that this move is conservative. If an op is likely to have fulljit dependency, or cannot be selective, it will be kept. Later if there's need to be used in mobile (rare), it will be adapted and moved case by case. 
3. All the moved ops are marked selective. The registration function is changed from `Operator()` to `OperatorGenerator()`. Size regression is not expected.

Tests:
* Internal size tests
* CI

Differential Revision: [D28463158](https://our.internmc.facebook.com/intern/diff/D28463158)

### CODE REVIEW

**Comment by iseeyuan** [comment]
@iseeyuan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28463158).

**Comment by iseeyuan** [comment]
@iseeyuan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28463158).

**Comment by iseeyuan** [comment]
@iseeyuan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28463158).

**Comment by iseeyuan** [comment]
@iseeyuan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28463158).

**Comment by cccclai** [comment]
Curious where the list comes from?

**Comment by iseeyuan** [comment]
> Curious where the list comes from?

Since all the prim ops are selectively built, in theory all the operators can be built in mobile. However, because some operators are full-jit dependent, some of them are kept in register_prim_ops_fulljit.cpp. It's really tedious manual tries.

**Pull request closed without merging**
