### PR TITLE
fix is_float_scale_factor warning (python and c++)

### PR DESCRIPTION
**Pull request by divideconcept**

### CODE REVIEW

**Comment by vincentqb** [comment]
@yf225 -- could you review this PR?

**Comment by yf225** [comment]
@divideconcept Thanks for the patch! The C++ implementation is written to exactly mirror the Python implementation: https://github.com/pytorch/pytorch/blob/0eb26fb01e673beef118af9c70c61582f7c4585a/torch/nn/functional.py#L2870. Wondering do you mind checking whether the Python implementation also erroneously prints this warning? Thanks!

**Comment by divideconcept** [comment]
@yf225 sorry I don't use python at all (that's why I love libtorch !)
But I would guess that yes, the same problem is very likely to occur in python, as it's a very simple and straightforward logic here.

**Comment by divideconcept** [comment]
@yf225 any chance you could authorize the commit so libtorch stop sending me those warnings at runtime ? thanks :)

**Comment by yf225** [comment]
@eellison I saw that you added the following line in https://github.com/pytorch/pytorch/pull/34514:
https://github.com/pytorch/pytorch/blob/c3abcf83aa02d2ac442636ec04239b17d197bf35/torch/nn/functional.py#L2885
Do you mind double-checking whether this logic is correct? (Should it be `is_float_scale_factor = math.floor(scale) != scale`?) If a correction is needed, we would like to update both Python and C++ implementation. Thanks!

**Comment by eellison** [comment]
Yea I think I made a mistake there

**Comment by yf225** [comment]
@divideconcept Would you like to also fix the Python equivalent code? We can merge this fix afterward, thanks a lot for your help!

**Comment by divideconcept** [comment]
@yf225 Sure ! Here's the pull request for the python equivalent : https://github.com/pytorch/pytorch/pull/35938

**Comment by yf225** [comment]
@divideconcept Thanks a lot for your help! Sorry to ask: can you merge that PR into this PR, so that we fix this problem together in both frontends at the same time? Thanks!

**Comment by yf225** [comment]
@divideconcept No worries - I can do it on my end :D

**Comment by divideconcept** [comment]
@yf225 hi, anything preventing this commit to be merged ?

**Comment by yf225** [comment]
Thanks for the reminder! Importing it now and will merge it after running internal CI :)

**Review by yf225 — APPROVED** [review]

**Pull request closed without merging**
