### PR TITLE
Update Exceptions.cpp

### PR DESCRIPTION
**Pull request by co63oc**
Fix a typo in Exceptions.cpp

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@co63oc thank you for fixing typos in this and other PRs.
I'm merging your PRs that wasn't merged 5 days ago because of an outage.

But in future, it would be better if you can combine fixes in several files into one PR.
Too many tiny simple PRs create unnecessary load for the CI infrastructure.

**Comment by co63oc** [comment]
> @co63oc thank you for fixing typos in this and other PRs. I'm merging your PRs that wasn't merged 5 days ago because of an outage.
> 
> But in future, it would be better if you can combine fixes in several files into one PR. Too many tiny simple PRs create unnecessary load for the CI infrastructure.

Thank you, then I know

**Pull request closed without merging**
