### PR TITLE
Updating miniz library from version 2.0.8 -> 2.1.0

### PR DESCRIPTION
**Pull request by MdAamirRaihan**
Summary:
This PR updates the miniz library from version 2.0.8 to 2.1.0.

### CODE REVIEW

**Comment by albanD** [comment]
Could please take care of the CLA before this can be merged?

cc @malfet

**Comment by MdAamirRaihan** [comment]
> Could please take care of the CLA before this can be merged?
> 
> cc @malfet

Just signed the CLA

**Comment by albanD** [comment]
It seems that the CLA was registered as the bot didn't post here.
Can you double check that you did it with the right github handle/email as the one on your github account?

**Comment by MdAamirRaihan** [comment]
> It seems that the CLA was registered as the bot didn't post here. Can you double check that you did it with the right github handle/email as the one on your github account?

Yes, I  did it with the correct email and account name.  Should I do it again?

**Review by albanD — APPROVED** [review]
SGTM thanks for the update

**Pull request closed without merging**
