### PR TITLE
Add docstring type formatting guidelines to `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by ProGamerGov**
This PR builds on the following past PRs, and serves to help improve the consistency of PyTorch's docstring formatting.

* `boolean` -> `bool` and `string` -> `str`: https://github.com/pytorch/pytorch/pull/82410

* Don't use plural of types: https://github.com/pytorch/pytorch/pull/82474

* Capitalize the Callable type, `callable` -> `Callable` : https://github.com/pytorch/pytorch/pull/82487

### CODE REVIEW

**Review by H-Huang — APPROVED** [review]
Overall the notes look good to me. 

I wonder if the format / content of docstrings is also something we can automatically lint? I'm not sure if we can count on everyone following these conventions.
cc @suo

**Review by albanD — APPROVED** [review]
That sounds good!
note that we're also ramping up on xdoctest https://github.com/pytorch/pytorch/pull/83317 and so that will help for ensuring the code part remains clean.

**Comment by albanD** [comment]
@ProGamerGov FYI, you can now merge your PRs directly after they've been accepted by a maintainer! Just ask the bot to do so once everything is ready:

**Pull request closed without merging**
