### PR TITLE
Fix _saved_tensors argument issue in test

### PR DESCRIPTION
**Pull request by lyoka**
Summary:
fix broken test in

https://github.com/pytorch/pytorch/issues/103460

Test Plan: pytest ./generated/test_pabloppp_pytorch_tools.py -k test_015

Differential Revision: D46723640

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @msaroufim

### CODE REVIEW

**Comment by lyoka** [comment]
the lint failure is fixed in https://github.com/pytorch/pytorch/commit/7a2a006c9e5ebf7c2d56bd29286a7ebd10817a0c

**Review by yanboliang — COMMENTED** [review]
Can you add unit test in test/dynamo/test_misc.py

**Comment by lyoka** [comment]
> Can you add unit test in test/dynamo/test_misc.py

Done.

**Comment by lyoka** [comment]
Root cause:
when we first call save_for_backward, it adds a new data member _saved_tensors in AutogradFunctionContextVariable (https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/misc.py#L456)
later when we call mark_non_differentiable, it will clone the AutogradFunctionContextVariable. However, in the constructor it doesn't know _saved_tensors. (https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/variables/misc.py#L419)

**Review by yanboliang — APPROVED** [review]

**Pull request closed without merging**
