### PR TITLE
[foreach][mta] Inplace `maximum` and `minimum`

### PR DESCRIPTION
**Pull request by crcrpar**
### Description

Implement `torch._foreach_maximum_` and `torch._foreach_minimum_` mainly for `_multi_tensor_adam` and `_multi_tensor_adamw` with `amsgrad=True` to correctly update their `max_exp_avg_sqs`.

### Issue

- https://github.com/pytorch/pytorch/issues/78807
- https://github.com/pytorch/pytorch/pull/81894
- https://github.com/pytorch/pytorch/pull/81348
- https://github.com/pytorch/pytorch/pull/81705
- https://github.com/pytorch/pytorch/issues/58833
- https://github.com/pytorch/pytorch/issues/68041

### Testing

Updated `test_foreach.py::TestForeach::_minmax_test` to compare the outputs of `_foreach_maximum_` (and `_foreach_minimum_`) against those of `[torch.maximum(a, b) for a, b in zip(tensors1, tensors2)]`

cc @ngimel @albanD @mikaylagawarecki

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Somewhat related: https://github.com/pytorch/pytorch/issues/54216

**Review by albanD — APPROVED** [review]
Awesome! Thanks for the quick fix

**Comment by crcrpar** [comment]
@albanD thanks but give me a sec, the failure of [test_cuda.py::test_graph_adam_adamw](https://github.com/pytorch/pytorch/runs/7590436776?check_suite_focus=true#step:10:3028) looks real

**Comment by albanD** [comment]
I would expect this to change the numerics for sure ;) 
cc @mikaylagawarecki if you have an idea?

**Comment by mikaylagawarecki** [comment]
Hm does the failing test `test_graph_adam_adamw` test parity between adam and adamw, I'm guessing the same change might be needed [here](https://github.com/pytorch/pytorch/blob/master/torch/optim/adamw.py#L400 ) if that is the case as AdamW has a similar bug

**Comment by mikaylagawarecki** [comment]
Additionally we need to update `https://github.com/pytorch/pytorch/blob/master/torch/optim/adam.py#L408` as well (the `max_exp_avg_sqs` under the capturable=False branch) I think this might be causing the failure

**Comment by crcrpar** [comment]
Thank you @mikaylagawarecki. I got ahead of myself and forgot running test_cuda.py :)

**Review by albanD — APPROVED** [review]
Perfect!

Thanks @mikaylagawarecki for your fast input on this!

**Comment by crcrpar** [comment]
could you move forward this unless there's TODOs for me?

**Comment by albanD** [comment]
@crcrpar FYI, for future PRs, you can ask the bot to merge yourself (by doing exactly what Natalia did) once the PR is accepted by a maintainer!

**Pull request closed without merging**
