### PR TITLE
[Quant] Fixed errors in test_embedding introduced by https://github.com/pytorch/pytorch/pull/69768

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71387

Differential Revision: [D33808593](https://our.internmc.facebook.com/intern/diff/D33808593)

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]
is this test running now?

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33808593).

**Comment by dzdang** [comment]
> is this test running now?

yup just confirmed it's running

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33808593).

**Pull request closed without merging**
