### PR TITLE
[CUDA] Workaround shmem limit for certain input sizes in `AdaptiveAvgPool1D`

### PR DESCRIPTION
**Pull request by eqy**
Reference issue #68248 

CC @ptrblck @malfet @xwang233 

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @ptrblck

### CODE REVIEW

**Comment by eqy** [comment]
Also related: #70701

**Review by mikaylagawarecki — APPROVED** [review]
Looks ok to me and failures look unrelated let's maybe hold off on merging till @marcmk6 verifies that it fixes the issue

**Comment by marcmk6** [comment]
@eqy @mikaylagawarecki  
Hi, I couldn't figure out how to build pytorch from source code. I did try to follow the instructions but got cpp compilation errors that I don't understand. So I'm sorry I may not be able to verify the fix, assuming I have to build it by myself.

**Comment by marcmk6** [comment]
@eqy I got RTX A5000 and an old Tesla P4

**Comment by eqy** [comment]
I've verified that this is fixed on P100 and A40 (the closest GPUs I have access to compared to P4 and A5000), merging.

@pytorchmergebot merge

**Pull request closed without merging**
