### PR TITLE
Docs/cpp misc features and fixes

### PR DESCRIPTION
**Pull request by svenevs**
CC: @goldsborough 

- [x] Use the shiny new feature just for `pytorch` like we talked about (`"listingExclude"`) to mitigate some of the PIMPL clutter.
- [x] Fix a few errors on `index.rst`.
- [x] Fix some broken `.. code-block::` directives.
- [x] Fix Markdown link by way of using intersphinx (can't use markdown linking style inside an `\rst` block, but intersphinx is super sweet).  More info on using intersphinx with exhale [here](https://my-favorite-documentation-test.readthedocs.io/en/latest/using_intersphinx.html).
- [x] Make sure `torch::detail::CursorBase` reliably gets correct defining file assigned by skipping forward declarations (previously exhale was breaking a tie between `cursor.h` and `optimizer.h`, and was "accidentally" getting `cursor.h` correct, now it will reliably get `cursor.h`).
- [ ] There is a slight snag right now: `[~] Manually setting file definition of typedef disable_if_module_holder_t to [torch/csrc/api/include/torch/nn/module.h]`.  It's _used_ in `module.h`, but is actually defined in `pimpl-inl.h`.  However, currently the following exclude for `Doxyfile` means this can't be recovered:

    ```make
    EXCLUDE = ../../../torch/csrc/api/include/torch/nn/pimpl-inl.h \
              ../../../torch/csrc/api/include/torch/detail
    ```

    Six on one hand, half dozen on the other.  There's no documentation on it, so it's not super important either way in my opinion.

P.S. Where the `.. code-block::` errors are concerned, there's a not-so-well-known way to quickly find out if these errors exist when you run `make html`.  I'm attaching a picture because it's a color-based approach.  Because of the unfortunate state of affairs with breathe and sphinx cpp domain, there's a lot of red text flying around.  That can make it next to impossible to find actual errors you can do something about because it all bleeds together.  But the ones that you can potentially fix are in a dim red (see picture), whereas the ones that are coming from breathe / sphinx tension are in bold red.

finding_code_block_problems

Note of course this isn't a hard rule, for example there are some dim red ones that cannot be fixed (but apparently aren't actually a problem?), specifically

```
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1a105c2a8ef81c6faa82a01cf35ce9f3b1.rst:6: WARNING: Unknown target name: "normal".       
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1a5978fcc257460475f635b5960e892a8e.rst:6: WARNING: Unknown target name: "orthogonal".   
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1a77eb9bba76a93da5b33e7770f9113015.rst:6: WARNING: Unknown target name: "eye".          
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1a82f2e5810880c7cc60c84516eb283be6.rst:6: WARNING: Unknown target name: "sparse".       
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1a86191a828a085e1c720dbce185d6c307.rst:6: WARNING: Unknown target name: "xavier_normal".
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1a9c886724aac3a487553dc0a406565c83.rst:6: WARNING: Unknown target name: "constant".
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1a9dcc2051aadbe8ddb37d58bbd2b7943a.rst:6: WARNING: Unknown target name: "ones".
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1ab0aeccca28b2225ee9aab809ec38a801.rst:6: WARNING: Unknown target name: "uniform".
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1ab9fa9ea51c05df8a5c9dcca7a54dd628.rst:6: WARNING: Unknown target name: "dirac".
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1ace282f75916a862c9678343dfd4d5ffe.rst:6: WARNING: Unknown target name: "xavier_uniform"
.
/home/sven/Desktop/pytorch/docs/cpp/source/api/function_namespacetorch_1_1nn_1_1init_1af7e7736ba2d050adc0523d84285564e8.rst:6: WARNING: Unknown target name: "zeros".
```

Those are dim red warnings, but the docs for them (`torch/csrc/api/include/torch/nn/init.h`) are valid.  It's because of the trailing underscore in those function names, but should be safe to ignore for now.

### CODE REVIEW

**Comment by svenevs** [comment]
Hmmmmm.  I'll wait til Peter's back in town, `check-doxygen.sh` seems to be [acting up again](https://travis-ci.org/pytorch/pytorch/jobs/444435727)?

```
Warning: tag INCLUDE_PATH: include path `../../../build/aten/src' does not exist
Warning: tag INPUT: input source `../../../aten/src/c10/util/Exception.h' does not exist
Warning: tag INPUT: input source `../../../build/aten/src/ATen/Functions.h' does not exist
warning: source ../../../aten/src/c10/util/Exception.h is not a readable file or directory... skipping.
```

**Review by goldsborough — APPROVED** [review]
The cpp docs check is currently broken (not related to this PR). I've submitted a fix for it. Let's wait for that fix to land and then rebase this PR, just to make sure

**Comment by svenevs** [comment]
Sounds good, ping me when I should rebase off `master` :slightly_smiling_face:

**Comment by svenevs** [comment]
I think this can be closed now :slightly_smiling_face:

**Pull request closed without merging**
