### PR TITLE
Tag dynamo backends as debug/experimental

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #93878
* #93871
* #93870
* #93863
* #93822
* #93821
* #93818

Hides debug/experimental backends by default.

Before:
```
torch._dynamo.list_backends()
['aot_eager', 'aot_eager_decomp_partition', 'aot_torchxla_trace_once', 'aot_torchxla_trivial', 'aot_ts', 'aot_ts_nvfuser', 'cudagraphs', 'dynamo_accuracy_minifier_backend', 'dynamo_minifier_backend', 'eager', 'inductor', 'ipex', 'nvprims_aten', 'nvprims_nvfuser', 'onnxrt', 'tensorrt', 'torchxla_trace_once', 'torchxla_trivial', 'ts', 'tvm']
```

After:
```
torch._dynamo.list_backends()
['aot_ts_nvfuser', 'cudagraphs', 'inductor', 'ipex', 'nvprims_nvfuser', 'onnxrt', 'tensorrt', 'tvm']
```

Fixes https://github.com/pytorch/pytorch/issues/93733

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Comment by JackCaoG** [comment]
Hi @jansel What's standard of being an non-debug backend? Last time I check we can run 70% of the torchbench model without crash and most of them with reasonable->great performance.

**Comment by jansel** [comment]
Which backend are you talking about?

Debug backends are intended for debugging (for example "eager" and "aot_eager"), they don't make your program go faster -- but mainly intended to debug issues.

**Comment by JackCaoG** [comment]
I am talking about xla backends, so `torchxla_trace_once` and `aot_torchxla_trace_once`. `torchxla_trivial` and `aot_torchxla_trivial` are only for debugging purpose so they should stay in the debug backends.

**Comment by jansel** [comment]
@JackCaoG the XLA ones are tagged "experimental" not "debug".  Feel free to submit a PR to reclassify them as debug if you think that is better or remove any ones that aren't useful anymore.

For torchxla_trivial:
https://github.com/pytorch/pytorch/blob/9d4d66f3f4950dcf5389e1dd16015559897fadf5/torch/_dynamo/backends/torchxla.py#L9-L11

There is a potential "gotcha" where if the user only does:
```
torch.compile(backend="torchxla_trivial")
```
they won't actually get XLA, since the backend is identical to the "eager" backend.  There are some extra XLA-related incantations the user must do to actually get XLA.  I didn't want users seeing that in the list, and naively trying to turn it on.

I'd suggest adding at least something like:
```
if any(x.device.type != "xla" for x in inputs):
   raise RuntimeError(... link to docs explaining how to use the XLA backend ...)
```

I mainly marked them experimental to try to avoid that user gotcha, not making some larger statement about the state of XLA+Dynamo.

Feel free to submit PRs to change the XLA backends, remove them, or reclassify them.  

cc @alanwaketan

**Pull request closed without merging**
