### PR TITLE
Fix the compare logic in function `overflows` for MSVC

### LINKED ISSUE #15497: vs2015 + windows 10 Error C4146
## 🐛 Bug
Get error C4146 in release mode with visual studio 2015.
 Error "C4146: unary minus operator applied to unsigned type, result still unsigned"
it occur at libtorch\include\c10/Half.h(396):
```
 if (!limit::is_signed && std::numeric_limits<From>::is_signed) {
    // allow for negative numbers to wrap using two's complement arithmetic.
    // For example, with uint8, this allows for `a - b` to be treated as
    // `a + 255 * b`.
    return f > limit::max() ||
        (f < 0 && -static_cast<uint64_t>(f) > limit::max());<----- error occored here
  } else {
    return f < limit::lowest() || f > limit::max();
  }
```

## To Reproduce

1.wirter example code from https://pytorch.org/tutorials/advanced/cpp_export.html with vs2015
2.select release mode \ x64 architecture 
3.import torch.lib and torch\include
4.generate than get error

## environment
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 教育版
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: Quadro K2200
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 388.19
cuDNN version: Probably one of the following:
D:\lib\CUDA\v9.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.0.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

## Additional context
I delete the '-' and then build sucessfully, so it is the last error.

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes https://github.com/pytorch/pytorch/issues/15497.

### CODE REVIEW

**Comment by peterjc123** [comment]
@soumith @ezyang Please have a look.

**Comment by ezyang** [comment]
CC @Maratyszcza 

Do you think the warning is real? The negation of an unsigned quantity does seem kind of dodgy.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
i checked, the warning is not real. we are using the wrap-around semantics of unsigned numbers here on purpose.

**Comment by Maratyszcza** [comment]
@ezyang negation of unsigned number is the only way to guarantee wrap-around for overflow without relying on non-standard compiler flags or UB.

@peterjc123  `#pragma warning( default : 4146 )` is a bit dangerous, especially in a public header, because the code including this header might have used this pragma itself to change defaults before including `c10/Half.h`. A safer way to temporary disable warning is to do

```c
#ifdef _MSC_VER
#pragma warning( push )
#pragma warning( disable : 4146 )
#endif

// .....
// warning-generating code
// .....

#ifdef _MSC_VER
#pragma warning( pop )
#endif
```

**Comment by peterjc123** [comment]
@Maratyszcza Thanks for your suggestion. PR is on the way.

**Pull request closed without merging**
