### PR TITLE
fix device type bug for custom device

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #ISSUE_NUMBER
support  the custom renamed device ,@bdhirsh , please review my changes.

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
thanks!

**Comment by heidongxianhua** [comment]
> @pytorchbot merge

@bdhirsh Hi, I saw it merge failed, It seems that you need add a label like  "topic: not user facing".

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@heidongxianhua I've added the label.
FYI, you can also add labels, using the same comment to pytorchbot as I did.

**Comment by heidongxianhua** [comment]
> @heidongxianhua I've added the label. FYI, you can also add labels, using the same comment to pytorchbot as I did.

@kit1980 yeah, thankyou. I do not kown that I cann do this. hhaha, thank you telling me this.

**Pull request closed without merging**
