### PR TITLE
[ONNX] Minor doc update (#69501)

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69550
* #69548
* #69547
* #72663
* #68491

Fix the wiki URL.

Also minor reorganization in onnx.rst.

Differential Revision: [D32994269](https://our.internmc.facebook.com/intern/diff/D32994269)

### CODE REVIEW

**Comment by BowenBao** [comment]
cc @garymm this one seems to have some CI error with linux-docs / build-docs (python).

@msaroufim please leave out that one and import from #69549

**Comment by garymm** [comment]
> cc @garymm this one seems to have some CI error with linux-docs / build-docs (python).

Sorry about that. Attempting to fix here: https://github.com/pytorch/pytorch/pull/69623

**Comment by BowenBao** [comment]
Should resolve doc CI issues now, squashing the fix from @garymm.

@msaroufim please directly import this PR stack.

**Comment by msaroufim** [comment]
@msaroufim has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32994269).

**Comment by msaroufim** [comment]
@msaroufim has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32994269).

**Comment by msaroufim** [comment]
@msaroufim has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32994269).

**Comment by BowenBao** [comment]
cannot merge this one separately unfortunately due to dependency on #68491

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32994269).

**Pull request closed without merging**
