### PR TITLE
Fix subgradient for element-wise max and min

### LINKED ISSUE #56734: Element-wise max of two Tensors computes the wrong gradient in case of equality
It should get a similar treatment as the reduction version of max that evenly splits the gradients for all values that are equal to the maximum.

`min` most likely have the same issue.

Note that these are aliases and so they are actually defined as `maximum` and `minimum` in derivatives.yaml: https://github.com/pytorch/pytorch/blob/6c65ce8ee14faec577582ecd0e17ba436f32c8b3/tools/autograd/derivatives.yaml#L749-L751

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

### PR DESCRIPTION
**Pull request by Varal7**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59669 Fix subgradient for element-wise max and min**

Summary: Fixes #56734

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D28975531](https://our.internmc.facebook.com/intern/diff/D28975531)

### CODE REVIEW

**Comment by Varal7** [comment]
@varal7 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28975531).

**Comment by Varal7** [comment]
@varal7 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28975531).

**Comment by Varal7** [comment]
@varal7 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28975531).

**Comment by Varal7** [comment]
@varal7 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28975531).

**Review by albanD — APPROVED** [review]
LGTM!
Thanks for the test simplification!

**Comment by Varal7** [comment]
@varal7 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28975531).

**Pull request closed without merging**
