### PR TITLE
[pytorch] refine dispatch keys in native_functions.yaml (1/N)

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#45010 [pytorch] refine dispatch keys in native_functions.yaml (1/N)**

The motivation of this change is to differentiate "backend specific" ops
and "generic" ops.

"backend specific" ops are those invoking backend specific kernels thus
only able to run on certain backends, e.g.: CPU, CUDA.

"generic" ops are those not *directly* invoking backend specific kernels.
They are usually calling other "backend specific" ops to get things
done. Thus, they are also referred to as "composite" ops, or "math" ops
(because they are usually pure C++ code constructed from math formula).

The other way to see the difference is that: we have to implement new
kernels for the "backend specific" ops if we want to run these ops on a
new backend. In contrast, "generic"/"composite" ops can run on the new
backend if we've added support for all the "backend specific" ops to
which they delegate their work.

Historically we didn't make a deliberate effort to always populate
supported backends to the "dispatch" section for all the "backend specific"
ops in native_functions.yaml. So now there are many ops which don't have
"dispatch" section but are actually "backend specific" ops. Majority
of them are calling "DispatchStub" kernels, which usually only support
CPU/CUDA (via TensorIterator) or QuantizedCPU/CUDA.

The ultimate goal is to be able to differentiate these two types of ops
by looking at the "dispatch" section in native_functions.yaml.

This PR leveraged the analysis script on #44963 to populate missing
dispatch keys for a set of "backend specific" ops. As the initial step,
we only deal with the simplest case:
* These ops don't already have dispatch section in native_functions.yaml;
* These ops call one or more DispatchStub (thus "backend specific");
* These ops don't call any other aten ops - except for some common
  ones almost every op calls via framework, e.g. calling aten::eq via
  Dispatcher::checkSchemaCompatibility. Calling other nontrivial aten
  ops is a sign of being "composite", so we don't want to deal with this
  case now;
* These ops don't call Tensor::is_quantized() / Tensor::is_sparse() / etc.
  Some ops call thse Tensor::is_XXX() methods to dispatch to quantized /
  sparse kernels internally. We don't deal with this case now.

Differential Revision: [D23803951](https://our.internmc.facebook.com/intern/diff/D23803951)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by bhosmer — APPROVED** [review]
Nice, and the PR description is great! 

One thing that might be worth adding to the description is a note that since the kernels for these formerly-generic ops aren't changed in this PR (just the generated op registrations), the kernels will still be doing device detection, which is now redundant. Depending on implementation details, there might be some nice followup refactoring opportunities: situations that now look like
```
dispatch:
  CPU, CUDA: op

op(args) {
  device = compute from args
  if (device == CPU) { ... cpu impl ... }
  else if (device == CUDA) { ... cuda impl ... }
  else error
}
```
could be turned into
```
dispatch:
  CPU: op_cpu
  CUDA: op_cuda

Tensor op_cpu(Tensor t) { ... cpu impl ... }
Tensor op_cuda(Tensor t) { ... cuda impl ... }
```

**Comment by ljk53** [comment]
> One thing that might be worth adding to the description is a note that since the kernels for these formerly-generic ops aren't changed in this PR (just the generated op registrations), the kernels will still be doing device detection, which is now redundant.

Right - but I think most ops in this batch are doing CPU/CUDA dispatch via DispatchStub. The common pattern is calling the same native::xxx_out() function to do basic checks and to setup TensorIterator, then calling xxx_stub(iter.device_type(), iter) do do the actual computation.

Explicit if-based dispatch usually happens on if(is_quantized()) / if(is_sparse()). Some of them happens at the beginning of the native_xxx() function, for which case we can migrate to the pattern you proposed relatively easily. Some of them happens in the middle of the native_xxx() function, after some common checking/setup logic, which will require more effort to refactor.

**Comment by bhosmer** [comment]
> Right - but I think most ops in this batch are doing CPU/CUDA dispatch via DispatchStub. The common pattern is calling the same native::xxx_out() function to do basic checks and to setup TensorIterator, then calling xxx_stub(iter.device_type(), iter) do do the actual computation.
> 
> Explicit if-based dispatch usually happens on if(is_quantized()) / if(is_sparse()). Some of them happens at the beginning of the native_xxx() function, for which case we can migrate to the pattern you proposed relatively easily. Some of them happens in the middle of the native_xxx() function, after some common checking/setup logic, which will require more effort to refactor.

Ah yeah you're right, it won't be easy for DispatchStub ops. This great info for forming a richer sense of the landscape BTW, thanks for all the detail!

**Comment by lw** [comment]
This PR is introducing several failures in the master branch across multiple tests, all of them in the `test_neg_negative` testcase of the `Test(Cuda)?(Uncoalesced)?Sparse` classes of `test_sparse.py`.

See for example:
https://app.circleci.com/pipelines/github/pytorch/pytorch/217256/workflows/267aebb2-1863-42af-bc08-b4b627385d98/jobs/7657648

I'll be reverting this, sorry.

**Comment by ljk53** [comment]
> This PR is introducing several failures in the master branch across multiple tests, all of them in the `test_neg_negative` testcase of the `Test(Cuda)?(Uncoalesced)?Sparse` classes of `test_sparse.py`.
> 
> See for example:
> https://app.circleci.com/pipelines/github/pytorch/pytorch/217256/workflows/267aebb2-1863-42af-bc08-b4b627385d98/jobs/7657648
> 
> I'll be reverting this, sorry.

Thanks! There might be some conflict with the PR landed right before this one #44028 - so I didn't see it before hitting land button :)

**Pull request closed without merging**
