### PR TITLE
[Needs someone to complete] torch.einsum()

### LINKED ISSUE #1889: Support for einsum notation
As mentioned [here](https://discuss.pytorch.org/t/einstein-summation-in-pytorch/2492), support for [einsum notation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html) would be useful. It's in fact a feature that I am missing most after transitioning from TensorFlow. What's needed for the implementation is parsing the einsum string and deciding which PyTorch modules to use for which cases as well as automatically reshaping input tensor back and forth like done [here](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/ops/special_math_ops.py#L85).

### PR DESCRIPTION
**Pull request by vlasenkov**
resolves #1889 

- [ ] implement #2116  
- [x] einsum for case when dummy index is summed for two inputs
- [ ] "exp space" einsum
- [ ] tests
- [ ] docs

### CODE REVIEW

**Comment by soumith** [comment]
this is worth adding in tensor.py, we want it to be available not just under autograd, but also for Tensors.

@rockt transpiled TensorFlow code here: https://gist.github.com/rockt/15ee013889d65342088e9260a377dc8f to get an einsum going in PyTorch, but we were hesitant to commit that exact code as-is because we weren't sure about licensing.
You can however lift the tests etc. out of it.

**Comment by vlasenkov** [comment]
Are you talking about `torch/tensor.py`? It defines only base tensor class and does not contain any functional API, adding `einsum` here seems strange...
And how is `torch/functional.py` related to autograd?

**Comment by soumith** [comment]
oh, nevermind i just misread the PR. I thought it went into nn/functional.py

**Comment by giorgiop** [comment]
Is this PR still on progress?

**Comment by t-vi** [comment]
I think this could be closed. (@fmassa ?)

**Pull request closed without merging**
