### PR TITLE
[inductor] Add size, stride, storage_offset to RAIIAtenTensorHandle

### PR DESCRIPTION
**Pull request by aakhundov**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #110766
* __->__ #110764
* #110745
* #110713

Summary: For unbacked SymInts, the C++ wrapper codegen can generate expressions like `buf123.size()` or `.stride()` or `.storage_offset()`:

https://github.com/pytorch/pytorch/blob/7cc0020a80527207a1725e6d21ce7c326668fe0d/torch/_inductor/ir.py#L2504-L2520

Here we add corresponding methods to the `RAIIAtenTensorHandle` class so that the above codegen works in the ABI compatibility mode.

Test Plan: CI + the following PR

Reviewers:

Subscribers:

Tasks:

Tags:

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler

### CODE REVIEW

**Comment by chenyang78** [comment]
I have a high-level question. We already have API calls like ```aoti_torch_get_sizes``` that can be used to implement ```aoti_torch_get_size```, e.g.

```
int64_t *sizes;
aoti_torch_get_sizes(..., &sizes, ...);
int64_t sz = sizes[d];
``` 

So, instead of adding new APIs, I am wondering if we could just code-gen a similar code like above by leveraging the existing APIs. One benefit would be that we end up maintaining a minimal set of interfaces.

**Comment by aakhundov** [comment]
> So, instead of adding new APIs, I am wondering if we could just code-gen a similar code like above by leveraging the existing APIs. One benefit would be that we end up maintaining a minimal set of interfaces.

@chenyang78 I agree that reducing the extent of the API is generally good. However, the problem with relying on the existing functions is that it's impossible to do range checking, as they simply provide a pointer to the list of sizes. We've discussed this briefly offline with @desertfire and decided to delegate the range checking (as well as proper error messaging) to ATen ops. And that's the reason for the new functions relying on `tensor->size(d)` and friends instead of `tensor->sizes()` as in the pre-existing API. Does this make sense?

**Comment by chenyang78** [comment]
> > So, instead of adding new APIs, I am wondering if we could just code-gen a similar code like above by leveraging the existing APIs. One benefit would be that we end up maintaining a minimal set of interfaces.
> 
> @chenyang78 I agree that reducing the extent of the API is generally good. However, the problem with relying on the existing functions is that it's impossible to do range checking, as they simply provide a pointer to the list of sizes. We've discussed this briefly offline with @desertfire and decided to delegate the range checking (as well as proper error messaging) to ATen ops. And that's the reason for the new functions relying on `tensor->size(d)` and friends instead of `tensor->sizes()` as in the pre-existing API. Does this make sense?

I see. Make sense. Thanks for the clarification.

**Review by chenyang78 — APPROVED** [review]

**Pull request closed without merging**
