### PR TITLE
[Profiler] Weaken ordering check during post processing.

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #78563

The profiler assembles a call hierarchy by replaying recorded events. There is an assert to ensure that the events form a well structured tree; however many of the inputs are from external sources and small differences (e.g. recording time in a lower precision) leads to traces which violate that assumption. For now this is acceptable; the post processing can handle resolving these descrepencies. As a result, I am relaxing the assert to only test event types where we expect the framework to be able to enforce these strong structural requirements.

Differential Revision: [D36787787](https://our.internmc.facebook.com/intern/diff/D36787787/)

### CODE REVIEW

**Comment by robieta** [comment]
This should resolve https://github.com/pytorch/pytorch/issues/78283. (I'll confirm before submitting.)

**Review by suo — APPROVED** [review]
Thanks for the quick fix!

**Comment by suo** [comment]
cc @clee2000 it does seem to have happened after you merged your change.

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36787787).

**Comment by robieta** [comment]
I confirmed that this fixes https://github.com/pytorch/pytorch/issues/78283, so also re-enabling the test.

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36787787).

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36787787).

**Comment by robieta** [comment]
The underlying issue was also causing large scale kineto failures in prod which is why I skipped the normal process.

**Pull request closed without merging**
