### PR TITLE
Add-o pipefail for all bash scripts

### LINKED ISSUE #142380: Add a bash script linter for -o pipefail
The idea comes from https://github.com/pytorch/pytorch/pull/142377, it's useful to have `-o pipefail` prevent a similar failure in other bash scripts.

There is also `-u` that ExecuTorch is using on their repo that we could adopt too.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang

### PR DESCRIPTION
**Pull request by Grove-YJX**
Fixes #142380
I have added ```-o pipefail``` in all bash scripts in pytorch/.ci/pytorch. Please contact me if there are any problems with this fix^^.

### CODE REVIEW

**Comment by Grove-YJX** [comment]
Can this fix be merged? I'd appreciate it very much! @malfet @ezyang @zou3519

**Comment by ezyang** [comment]
need to remove pytorch submodule

**Review by ezyang — CHANGES_REQUESTED** [review]
.

**Comment by malfet** [comment]
> need to remove pytorch submodule

I wonder if `git submodule update --init --recursive` will delve into infinite recursion with that one :P

**Review by malfet — CHANGES_REQUESTED** [review]
Delete pytorch submodule (wonder if this will work thru codespaces)

**Comment by Grove-YJX** [comment]
> Delete pytorch submodule (wonder if this will work thru codespaces)

In fact, I'm not particularly familiar with github commits, so I made some missteps, and in the new PR I'm submitting files using git add <file>, which may sound a bit silly ^^But I hope I can grow up soon!

**Pull request closed without merging**
