### PR TITLE
Remove Android folder

### PR DESCRIPTION
**Pull request by msaroufim**
This folder is a tutorial that is not packaged in PyTorch that's an example of how to use the now deprecated Lite Interpreter for Android

People should be using Executorch instead and there's already good documentation on it all over our tutorials and main homepage

Testing to see what breaks in CI
1. Removed this from CMakeLists.txt `add_subdirectory(android/pytorch_android)`
2. Remove fbjini from `.gitmodules`

A similar PR was sent here https://github.com/pytorch/pytorch/pull/143398

cc @albanD

### CODE REVIEW

**Comment by albanD** [comment]
Skipping PR sanity because of pure deletion of code not in the PT package! 🥳

**Review by malfet — APPROVED** [review]
LGTM, but make sure to import it as diff , as some of those files might accidentally be used in internal build targets. And make sure to edit out any references to Java in README as well as follow up by deleting the respective tutorials

**Review by albanD — APPROVED** [review]
The test failure feels very unrelated.
Maybe @wconstab has seen it before?

**Comment by msaroufim** [comment]
Hmm this seems involved to remove internally, might revisit

**Pull request closed without merging**
