### PR TITLE
[Profiler] Move legacy profiler out of `torch/csrc/autograd`

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85512
* #85511
* #85510

The legacy profiler is an eyesore in the autograd folder. At this point the implementation is almost completely decoupled from the rest of profiler, and it is in maintaince mode pending deprecation.

As a result, I'm moving it to `torch/csrc/profiler/standalone`. Unfortuantely BC requires that the symbols remain in `torch::autograd::profiler`, so I've put some basic forwarding logic in `torch/csrc/autograd/profiler.h`.

One strange bit is that `profiler_legacy.h` forward declares `torch::autograd::Node`, but doesn't seem to do anything with it. I think we can delete it, but I want to test to make sure.

(Note: this should not land until https://github.com/pytorch/torchrec/pull/595 is landed.)

Differential Revision: [D39108648](https://our.internmc.facebook.com/intern/diff/D39108648/)

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]

**Comment by robieta** [comment]
Note for devinfra: This stack does not have internal changes. I think some of the bzl changes might have confused ghexport.

**Comment by DanilBaibak** [comment]
Here you can find details about the problem [D39108648](https://www.internalfb.com/diff/D39108648).

**Pull request closed without merging**
