### PR TITLE
[doc] typo

### PR DESCRIPTION
**Pull request by stas00**
This PR fixes a typo in the `torch/autograd/function.py` doc

-----------------------

Additionally, the example at https://pytorch.org/docs/master/autograd.html#torch.autograd.Function doesn't quite compile:
```
'builtin_function_or_method' object has no attribute 'exp'
```
even though `i.exp()` is a valid function if `i` is a tensor.

I changed it to:
```
result = torch.exp(i)
```
but python doesn't like it either:
```
TypeError: exp(): argument 'input' (position 1) must be Tensor, not builtin_function_or_method
```

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]
Thanks for the fix!

**Comment by stas00** [comment]
While I agree that having `torch.autograd.Function` as a superclass would be better, I did what you suggested in the first place. You can see that the errors are not about these things. Give it a try and you will see.

**Comment by soulitzer** [comment]
Hmm, it seems to work for me after defining `input=torch.tensor(1.)`. Do you have a repro?

**Comment by stas00** [comment]
Sure, you're adding an additional code - all I'm saying is that the example as it is written doesn't compile.

The example in the doc is the repro, that's why you had to add additional code to make it compile ;)

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
