### PR TITLE
add operation list for AutocastCPU

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
In this PR:
* We have changed the default dtype of `AutocastCPU` from `float16` to `bfloat16` as discussed here `https://github.com/pytorch/pytorch/pull/61002`
* We also update the operation list which needs casting to `lower_precision_fp` or `float32`.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #63552
* __->__ #63534

Differential Revision: [D30644914](https://our.internmc.facebook.com/intern/diff/D30644914)

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
@puririshi98 @ngimel We have changed the default data type for `AutocastCPU` to `bfloat16` in this PR.

**Comment by VitalyFedyunin** [comment]
@ngimel PTAL

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
LGTM, cc @puririshi98 @mcarilli, maybe we should adjust bfloat16 list for cuda amp also (although we probably don't have an infra at this point to have different op lists depending on the type?)

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30644914).

**Pull request closed without merging**
