### PR TITLE
Rework requires_grad on DifferentiableGraphOp

### PR DESCRIPTION
**Pull request by jjsjann123**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57575 Rework requires_grad on DifferentiableGraphOp**
* #57574 fixing DifferentiableGraphOp updating requires_grad on input tensor list; python test added to verify the test

This PR does two things:

1. reverts "Manual revert of D27369251 (#56080)" in commit
   92a09fb87a567100122b872613344d3a422abc9f.

2. fixing DifferentiableGraph output with wrong requires_grad flag

Fixing requires_grad on outputs from DifferentiableGraph, the proper flag is
retrieved from profiling information. We previously only retrieves the profiling
information on the first profile node in all its uses. However, in case where
control flows are present, we need to iteratively search for profile node with
profiling information available, in case the first use is in an inactive code
path.

e.g.
```
  graph(%0 : Tensor,
        %1 : Bool):
  ..., %2 : Tensor = prim::DifferentiableGraph_0(%0)
  %3 : Tensor = prim::If(%1)
    block0():
      %4 : Tensor = prim::DifferentiableGraph_1(%2)
      -> (%4)
    block1():
      %5 : Tensor = prim::DifferentiableGraph_2(%2)
      -> (%5)
  -> (%3)
with prim::DifferentiableGraph_0 = graph(%0 : Tensor):
  ...
  %out : Tensor = aten::operation(...)
  ...
  return (..., %out)
with prim::DifferentiableGraph_1 = graph(%0 : Tensor):
  %temp : Tensor = prim::profile[profiled_type=Tensor](%0)
  ...
with prim::DifferentiableGraph_2 = graph(%0 : Tensor):
  %temp : Tensor = prim::profile[profiled_type=Float(...)](%0)
  ...
```

Differential Revision: [D29038773](https://our.internmc.facebook.com/intern/diff/D29038773)

### CODE REVIEW

**Comment by jjsjann123** [comment]
This is the second part in #56466 that restores the reverted code change, combined with the fixes in #55767

**Comment by Krovatkin** [comment]
@jjsjann123 let me do some extra testing against this stack internally. Fingers crossed.

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by Krovatkin** [comment]
@jjsjann123  could you please rebase?

**Comment by Krovatkin** [comment]
@Krovatkin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29038773).

**Pull request closed without merging**
