### PR TITLE
Add batched sparse CSR/CSC/BSR/BSC to sparse COO conversion support

### LINKED ISSUE #104868: Conversion of a CSR tensor with batches to COO tensor fails
## Issue description

As in the title.

## Code example

```python
>>> torch.tensor([[[0, 1], [2, 3]], [[4, 5], [6, 0]]]).to_sparse_csr().to_sparse()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: crow_indices is supposed to be a vector, but got 2 dimensional tensor.
```

The expected result is the same as in the following example:
```python
>>> torch.tensor([[[0, 1], [2, 3]], [[4, 5], [6, 0]]]).to_sparse_csr().to_dense().to_sparse()
tensor(indices=tensor([[0, 0, 0, 1, 1, 1],
                       [0, 1, 1, 0, 0, 1],
                       [1, 0, 1, 0, 1, 0]]),
       values=tensor([1, 2, 3, 4, 5, 6]),
       size=(2, 2, 2), nnz=6, layout=torch.sparse_coo)
```

## More information

The exception is raised from `convert_indices_from_csr_to_coo` which does not implement batched CSR tensor support. A number of tests (to_sparse tests, reduction tests, binary operation tests) disable the corresponding samples meaning that the issue has existed for a long time.

Now, while adding sparse samples to TestGradients methods in order to enable gradcheck tests for operations with sparse inputs, I realized that there is no straightforward way to disable batched sparse samples for these tests without disabling all sparse samples. So, the issue blocks my task. I suggest resolving it, especially because supporting batched crow_indices in `convert_indices_from_csr_to_coo` ought to be a straightforward task.

## System Info

- PyTorch version: main

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer

### PR DESCRIPTION
**Pull request by pearu**
As in the title.

Fixes https://github.com/pytorch/pytorch/issues/104868

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #116352
* __->__ #116206

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer @jcaip

### CODE REVIEW

**Review by amjames — APPROVED** [review]
LGTM

**Review by lezcano — APPROVED** [review]
Didn't review. Approving to allow merging

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
