### PR TITLE
Update ROCm base docker images to focal (ubuntu20.04)

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@seemethere I think you will need to create new docker tags in the registry? Please create `pytorch-linux-focal-rocm5.0-py3.7` as well as `pytorch-linux-focal-rocm5.1-py3.7`
https://github.com/pytorch/pytorch/runs/6893810090?check_suite_focus=true#step:5:20501
```
+ docker push 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm5.0-py3.7:5e325a9256867d845ff0ff9922eded165458ff97
The push refers to repository [308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm5.0-py3.7]
```

**Comment by kit1980** [comment]
> @seemethere I think you will need to create new docker tags in the registry? Please create `pytorch-linux-focal-rocm5.0-py3.7` as well as `pytorch-linux-focal-rocm5.1-py3.7` https://github.com/pytorch/pytorch/runs/6893810090?check_suite_focus=true#step:5:20501

I'll add the images.

**Review by malfet — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@kit1980 @malfet I'm not sure why the `docker-builds / docker-build (pytorch-linux-focal-py3.7-gcc7)` job fails, but that causes the rocm docker build jobs to be cancelled. I've tried rebasing and it still failed. Can you please suggest a solution?

**Comment by kit1980** [comment]
> @kit1980 @malfet @seemethere I'm not sure why the `docker-builds / docker-build (pytorch-linux-focal-py3.7-gcc7)` job fails, but that causes the rocm docker build jobs to be cancelled. I've tried rebasing and it still failed. Can you please suggest a solution?

As a temporary workaround to unblock you, try changing something inside `.circleci/docker` dir.

**Comment by malfet** [comment]
@jithunnair-amd please manually rebase (looks like there is a conflict of sorts)

**Comment by malfet** [comment]
@jithunnair-amd are you not concerned with the ROCm failure?

**Comment by jeffdaily** [comment]
> @jithunnair-amd are you not concerned with the ROCm failure?

There probably should have been a single PR to build rocm focal images and also switch CI to use them.  There is now an inconsistency in the hard-coded image names in .circleci/docker/build.sh compared to the expected image names in the various workflows.  The build.sh script is attempting to build a missing bionic image and the ROCM_VERSION variable is getting set incorrectly as "5.1" instead of "5.1.1".

**Comment by jeffdaily** [comment]
@malfet can you revert?

**Comment by malfet** [comment]
> @malfet can you revert?

Sure, though I believe you should be able to issue revert command as well (please try next time and ping me if this is not the case)

**Comment by jithunnair-amd** [comment]
@jeffdaily Indeed I was, and was trying to figure out whether we had the upgrade for the docker images and the CI jobs in one PR last time. Didn't expect it would get landed :)

**Pull request closed without merging**
