### PR TITLE
[dynamo] Refine `LocalSource.cell_or_freevar` to `LocalSource.is_input`

### PR DESCRIPTION
**Pull request by StrongerXi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #140155
* #140154
* #140153
* #140435
* #140436
* #140152
* #140330
* #140202
* #140201
* __->__ #140151
* #140150
* #140149
* #140036
* #140035

The `cell_or_freevar` was added in #106403 to help us ensure
Dynamo-export only allows graph input that depends on the frame input
(rather than a captured cell, for instance).

However, when taken literally, the `cell_or_freevar` condition is
actually not accurate, because for frame inputs that are also cells
(i.e., captured by some inner function), we actually set the
`cell_or_freevar` flag to false. This makes sense, because otherwise the
existing implementation would prevent Dynamo-export to add any of these
inputs to the graph.

To help with reasoning, this patch refines the `cell_or_freevar` flag to
what we really want to check -- `is_input`, and updates the relevant use
sites.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by StrongerXi** [comment]
Rebase

**Comment by StrongerXi** [comment]
I lost #140150 while rebasing... So canceling this merge.

**Comment by StrongerXi** [comment]
Rebase

**Pull request closed without merging**
