### PR TITLE
[optim] Add support for complex tensors in SparseAdam

### LINKED ISSUE #86340: Add complex support for SparseAdam and LBFGS optimizers
As per title
These optimizers are less high priority than the other in https://github.com/pytorch/pytorch/issues/65711 and so are not being worked on by the core team right now.
Feel free to pick this up if you're interested.

### PR DESCRIPTION
**Pull request by fzimmermann89**
Fixes #86340

### CODE REVIEW

**Comment by fzimmermann89** [comment]
This is based on #118184

**Review by janeyx99 — COMMENTED** [review]
Looks good, though please wait for the other PR to land so we could rebase + merge this one.

~You can also install ghstack to stack this PR on top of that one, and be able to land it sooner!~  Never mind, it looks like ghstack will only work for those with write access. I'm merging the other PR now so this should be okay for a rebase soon.

**Comment by janeyx99** [comment]
@fzimmermann89 ahhh sorry for the delay! Do you still have interest pushing this over the finish line? If so, could you rebase the PR + ping me so I could review?

If not, can I take over the PR to finish it up? Thanks for the contribution!

**Comment by fzimmermann89** [comment]
I also forgot about it.. 

Will have time to finish it up end of the week.

**Comment by janeyx99** [comment]
Sounds good

**Pull request closed without merging**
