### PR TITLE
Add utility report_compile_source_on_error

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91069

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Review by albanD — COMMENTED** [review]
I'm a bit confused, how are you using this?
Is the plan to get dynamo to populate the globals and enable this?

**Comment by ezyang** [comment]
@albanD yeah so I was trying to kick off a discussion about this in dynamo execution, but let's replay it here.

There are a few cases where we eval/exec code in PyTorch today:
* Dynamo guards
* forward call on FX GraphModule
* Inductor generated Triton kernels

And also some hypothetical new cases I have been thinking about adding:
* Python dispatcher (for backtraces that tell you which dispatch keys / ops you went through)
* `__torch_dispatch__` and other dispatch modes (for backtraces that tell you what ops you wen tthrough)

This utility offers one possible way of handling this. But there are other possibilities. In particular, similar to how Inductor generated Triton kernels are unconditionally written to disk, we could also just always write, e.g,. compiled FX graph code to disk and then get accurate backtraces that way. This seems... distasteful? But it's certainly a lot simpler than this code! Thus looking for guidance.

The utility itself is fairly self contained and harmless, so we can also just land it anyway and see if people use it or not.

**Review by albanD — COMMENTED** [review]
Thanks for the explanation. This is pretty cool!
I agree we should merge it to be able to use it as needed. This will not be tested if we leave the tests here though. Could you move them before merging?

**Review by albanD — APPROVED** [review]
SGTM!
Just lint needs fixing

**Pull request closed without merging**
