### PR TITLE
[JIT] Improve May Contain Alias Using Contained Elements

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32326 [JIT] Improve May Contain Alias Using Contained Elements**
* #32251 [JIT] Use Type Level Granularity in Alias Analysis Wildcards

Now that we have type-level granularity we can improve `mayContainAlias` queries. Each new values is initialized as containing the wildcard set of each contained mutable type. Whenever a value is added to a container it is set to the wildcard set. Now, to check if any two values contain overlapping values, we can just check if the `containedMemoryLocations` of two sets overlap.

Differential Revision: [D19563262](https://our.internmc.facebook.com/intern/diff/D19563262)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 24c357ba:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=24c357ba23c66f728c0b9ca1fd577ed05164eec6).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4285305) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_legacy_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=87439720) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=87439720))
<details>
<summary>
<code>Jan 16 23:37:19 RuntimeError: test_jit_legacy failed!</code>
</summary>

```
Jan 16 23:37:19 Ran 2335 tests in 124.253s 
Jan 16 23:37:19  
Jan 16 23:37:19 FAILED (errors=1, skipped=62, expected failures=1) 
Jan 16 23:37:19  
Jan 16 23:37:19 Generating XML reports... 
Jan 16 23:37:19 Traceback (most recent call last): 
Jan 16 23:37:19   File "test/run_test.py", line 456, in <module> 
Jan 16 23:37:19     main() 
Jan 16 23:37:19   File "test/run_test.py", line 449, in main 
Jan 16 23:37:19     raise RuntimeError(message) 
Jan 16 23:37:19 RuntimeError: test_jit_legacy failed! 
Jan 16 23:37:19 + cleanup 
Jan 16 23:37:19 + retcode=1 
Jan 16 23:37:19 + set +x 
Jan 16 23:37:19 =================== sccache compilation log =================== 
Jan 16 23:37:19 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 16 23:37:19 Compile requests               250 
Jan 16 23:37:19 Compile requests executed        0 
Jan 16 23:37:19 Cache hits                       0 
Jan 16 23:37:19 Cache misses                     0 
Jan 16 23:37:19 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by suo — APPROVED** [review]
very nice!

**Comment by eellison** [comment]
after talking with @Krovatkin, disabling the failing test because it's using a deprecated executor that isn't exposed in OSS or internally

**Comment by eellison** [comment]
fix windows build here: https://github.com/pytorch/pytorch/pull/32762

**Pull request closed without merging**
