### PR TITLE
Add check that groups, in_channels and out_channels are positive to Convolution C++ API 

### LINKED ISSUE #108219: C++ API `torch::nn::Conv*` modules crash by div0 with `groups==0`
### 🐛 Describe the bug

`torch::nn::{Conv1d, Conv2d, Conv3d, ConvTranspose1d, ConvTranspose2d, ConvTranspose3d}` crash with `groups==0`, rather than emit appropriate error message. Note that Python API emits correct error message `ValueError: groups must be a positive integer` when `groups` is zero.

Test code:
```C++
#include <stdint.h>
#include <stddef.h>
#include <c10/util/irange.h>
#include <cassert>
#include <torch/torch.h>

using namespace torch::nn;

int main() {
  try {
    torch::TensorOptions toptions = torch::TensorOptions();

    auto moptions = torch::nn::Conv1dOptions(1,1,{1}).groups(0);

    auto m = torch::nn::Conv1d(moptions);

    auto result = m->forward(torch::randn({1,1,1}, toptions));
  } catch (::c10::Error& e) {
    std::cout << "PyTorch exception: " << e.what();
  }

  return 0;
}
```
Error log:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3319772==ERROR: AddressSanitizer: FPE on unknown address 0x7f298da2a063 (pc 0x7f298da2a063 bp 0x7fff39af3a30 sp 0x7fff39af2f60 T0)
    #0 0x7f298da2a063 in torch::nn::ConvNdImpl<1ul, torch::nn::Conv1dImpl>::reset() /home/sehoon/pytorch-latest-asan/torch/csrc/api/include/torch/nn/modules/conv.h:34:5
    #1 0x7f298da29464 in torch::nn::ConvNdImpl<1ul, torch::nn::Conv1dImpl>::ConvNdImpl(torch::nn::detail::ConvNdOptions<1ul>) /home/sehoon/pytorch-latest-asan/torch/csrc/api/include/torch/nn/modules/conv.h:30:5
    #2 0x7f298da20419 in torch::nn::Conv1dImpl::Conv1dImpl(torch::nn::ConvOptions<1ul>) /home/sehoon/pytorch-latest-asan/torch/csrc/api/src/nn/modules/conv.cpp:41:7
    #3 0x408a4e in torch::nn::ModuleHolder<torch::nn::Conv1dImpl>::ModuleHolder<torch::nn::ConvOptions<1ul>&, void>(torch::nn::ConvOptions<1ul>&) /home/sehoon/pytorch-latest-asan/torch/csrc/api/include/torch/nn/pimpl.h:65:19
    #4 0x406d3c in torch::nn::Conv1d::Conv1d<torch::nn::ConvOptions<1ul>&, void>(torch::nn::ConvOptions<1ul>&) /home/sehoon/pytorch-latest-asan/torch/csrc/api/include/torch/nn/modules/conv.h:196:1
    #5 0x405a0a in main /home/sehoon/pytorch-latest-asan/test/cpp/reproduce/Conv1d_div0.cpp:15:14
    #6 0x7f296bd66d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #7 0x7f296bd66e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #8 0x405484 in _start (/home/sehoon/pytorch-latest-asan/build/bin/reproduce_Conv1d_div0+0x405484)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE /home/sehoon/pytorch-latest-asan/torch/csrc/api/include/torch/nn/modules/conv.h:34:5 in torch::nn::ConvNdImpl<1ul, torch::nn::Conv1dImpl>::reset()
==3319772==ABORTING
```
[Error location](https://github.com/pytorch/pytorch/blob/3a79621c9dce17f77fbddc06aab21f6bc477f313/torch/csrc/api/include/torch/nn/modules/conv.h#L34-L39):
```C++
TORCH_CHECK(
    options.in_channels() % options.groups() == 0,
    "in_channels must be divisible by groups");
TORCH_CHECK(
    options.out_channels() % options.groups() == 0,
    "out_channels must be divisible by groups");
```
We need a check to guarantee `groups > 0` before above code, like [how Python frontend does](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/conv.py#L86-L91):
```Python
if groups <= 0:
    raise ValueError('groups must be a positive integer')
if in_channels % groups != 0:
    raise ValueError('in_channels must be divisible by groups')
if out_channels % groups != 0:
    raise ValueError('out_channels must be divisible by groups')
```

### Versions

PyTorch version: 2.1.0a0+git5e0ec03
Is debug build: True
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 12.0.1 (git@github.com:starlab-unist/llvm-project.git 2a8037cf73a0379212f2e04e19e17e3082432d5d)
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.86.10
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.2
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          96
On-line CPU(s) list:             0-95
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
Stepping:                        7
CPU max MHz:                     4000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        6000.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       1.5 MiB (48 instances)
L1i cache:                       1.5 MiB (48 instances)
L2 cache:                        48 MiB (48 instances)
L3 cache:                        71.5 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.1.0a0+git5e0ec03
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-include               2023.1.0         h06a4308_46342  
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] torch                     2.1.0a0+git5e0ec03           dev_0    <develop>

cc @jbschlosser @albanD @mruberry @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes https://github.com/pytorch/pytorch/issues/108219
add check for torch_arg marco, as for inchannel/outchannel/groups, it should be greater than 0.

### CODE REVIEW

**Comment by heidongxianhua** [comment]
@mikaylagawarecki could you have a look again?

**Review by mikaylagawarecki — COMMENTED** [review]
Thanks for the change! Could we instead add a check here that `options.groups() > 0`

https://github.com/pytorch/pytorch/blob/559e17a08aa63bfb886ce3d10d5a8e5b547e9051/torch/csrc/api/include/torch/nn/modules/conv.h#L34-L39

that way I think we only have to make one update :)

**Comment by heidongxianhua** [comment]
> Thanks for the change! Could we instead add a check here that `options.groups() > 0`
> 
> https://github.com/pytorch/pytorch/blob/559e17a08aa63bfb886ce3d10d5a8e5b547e9051/torch/csrc/api/include/torch/nn/modules/conv.h#L34-L39
> 
> that way I think we only have to make one update :)

yeah, I have add this check. and I have a small question, if we add check at `ConvNdImpl`, then it only raise error when we run case with convNd rather than init `ConvNdOptions`, but maybe it should raise error directly when init `ConvNdOptions`? @mikaylagawarecki

**Review by mikaylagawarecki — APPROVED** [review]
Hm I suppose we will indeed raise the error later. However, since the existing `TORCH_CHECK`s are in ConvNdImpl I think this is ok

**Pull request closed without merging**
