### PR TITLE
Forward-mode AD support for torch.split, torch.split_with_sizes

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#68566 Forward-mode AD support for torch.split, torch.split_with_sizes**

These are just auto-linear as pointed out by Jeffrey.

Test Plan:
- Run OpInfo tests.

Differential Revision: [D32520239](https://our.internmc.facebook.com/intern/diff/D32520239)

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32520239).

**Review by soulitzer — APPROVED** [review]

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32520239).

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by zou3519** [comment]
@soulitzer @albanD interestingly after a rebase the codegen for this fails to build. I need to dig more into this, but please let me know if you guys know what is up.

**Comment by soulitzer** [comment]
Ahhh, that was due to https://github.com/pytorch/pytorch/pull/68535. I should've tested for TensorList outputs, sorry!

Would you mind applying the following in this PR? https://gist.github.com/soulitzer/bcdf25cc46b866684dd48b4148d256bb

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32520239).

**Comment by zou3519** [comment]
> Ahhh, that was due to #68535. I should've tested for TensorList outputs, sorry!
> 
> Would you mind applying the following in this PR? https://gist.github.com/soulitzer/bcdf25cc46b866684dd48b4148d256bb

Thanks, that worked!

**Pull request closed without merging**
