### PR TITLE
OpInfos for torch.atleast_{1d, 2d, 3d}

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #67555
* __->__ #67355

Differential Revision: [D32649416](https://our.internmc.facebook.com/intern/diff/D32649416)

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Cool!

Made a small tweak suggestion. Otherwise this looks great as long as the tests pass. I added the labels for extra testing.

**Comment by mruberry** [comment]
Looks like the functorch test will need to be skipped. How to skip that test depends, I think, on whether this goes in before or after https://github.com/pytorch/pytorch/pull/67520.

**Comment by mruberry** [comment]
ping @anjali411 -- I think this just needs a tweak to the skips and it's good to go

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32649416).

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32649416).

**Pull request closed without merging**
