### PR TITLE
[functorch] fix fbcode tests

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #86936

Differential Revision: [D40358418](https://our.internmc.facebook.com/intern/diff/D40358418)

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40358418).

**Review by samdow — APPROVED** [review]
Approving but super nit that it might be nice to keep the comment about testing twice on GPUs next to the onlyCPU decorator

**Comment by zou3519** [comment]
NB: This PR by itself doesn't fix the internal functorch tests, I need to rewire the internal configuration to line up with PyTorch's (otherwise, the IS_FBCODE env variable doesn't actually get defined)

**Pull request closed without merging**
