### PR TITLE
[TensorExpr] Make CacheReplacer and IndexFlattener mutate stmts/exprs inplace.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #63216
* __->__ #63527
* #63526

Differential Revision: [D30411411](https://our.internmc.facebook.com/intern/diff/D30411411)

### CODE REVIEW

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30411411).

**Review by navahgar — APPROVED** [review]
LGTM

Thanks for fixing this. I was starting to look into transformations one by one to find such places where we explicitly clone. Good that you got started already. :)

**Comment by ZolotukhinM** [comment]
Yeah, I'm trying to fix subtle bugs preventing from switching to shared_ptrs and these are some of them :)

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30411411).

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30411411).

**Pull request closed without merging**
