### PR TITLE
[LTC] Remove view

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This pull request removes the last view ops, the original view.

Test Plan:
./build/bin/test_lazy --gtest_filter=LazyOpsTest.TestView*

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]

**Review by antoniojkim — APPROVED** [review]

**Comment by alanwaketan** [comment]
Thanks Jack and Antonio.

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Pull request closed without merging**
