### PR TITLE
Test that tlparse understands the structured logs we output

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120658

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by ezyang** [comment]
So apparently adding tlparse to the docker install configuration causes dependency resolution to stop picking up the pyyaml prebuilt wheel so idk just installing it in the test script now. One less site to update now too, and updating the rev doesn't force everything to update.

**Comment by tinglvv** [comment]
Hi @ezyang, we are running into an issue in our CI on MtSnow ARM nodes, issue is with **pip install tlparse**, error log - 
Could you help check this? Thanks!

```
Collecting tlparse==0.3.5
  Downloading tlparse-0.3.5.tar.gz (13 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tinglvv** [comment]
> I guess I need to build ARM binaries for tlparse. This is Linux, is that right?

Thanks for the prompt response. Yes it is Linux.

**Comment by tinglvv** [comment]
@ezyang thanks for cc me in the PR, but was wondering if 0.3.6 includes the ARM binaries? I still get this error when installing
```
root@a5951b14bb2f:/workspace# pip install tlparse==0.3.6
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting tlparse==0.3.6
  Downloading tlparse-0.3.6.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

**Comment by ezyang** [comment]
OOPS. Use 0.3.7, not 0.3.6 lol

**Pull request closed without merging**
