### PR TITLE
Fix torch::hash for MSVC

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by apaszke** [comment]
What exactly is the MSVC error? I’m ok with changing removing the nicer overload, as it should work with gcc and clang as well

**Comment by peterjc123** [comment]
```CMD
C:\pytorch\torch/csrc/utils/hash.h(56): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
C:\pytorch\torch/csrc/utils/hash.h(56): error C2187: syntax error: '{' was unexpected here
```
It just complains about the unrecognized syntax here.

**Comment by colesbury** [comment]
We needed to do this for GCC 4.8 as well

23ca19ae3d1d62600185214dfbf5c0d98d754b6c

**Comment by apaszke** [comment]
Oh yeah, I'm not sure why it even built. I think adding a pair of parenthesis after the conditional type would be enough to fix it, but this works as well

**Comment by stefan-it** [comment]
Hi,

with GCC 7.2 on Arch Linux I get the following error message:

```bash
/mnt/Repositories/pytorch/torch/csrc/jit/python_arg_flatten.h:28:80:   required from here
/mnt/Repositories/pytorch/torch/csrc/utils/hash.h:75:39: error: call of overloaded 'dispatch_hash(const at::ScalarType&)' is ambiguous
     return _hash_detail::dispatch_hash(o);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/mnt/Repositories/pytorch/torch/csrc/utils/hash.h:52:6: note: candidate: decltype ((std::hash<_Tp>()(o), std::size_t())) torch::_hash_detail::dispatch_hash(const T&) [with T = at::ScalarType; decltype ((std::hash<_Tp>()(o), std::size_t())) = long unsigned int; std::size_t = long unsigned int]
 auto dispatch_hash(const T& o) -> decltype(std::hash<T>()(o), std::size_t()) {
      ^~~~~~~~~~~~~
/mnt/Repositories/pytorch/torch/csrc/utils/hash.h:59:68: note: candidate: typename std::enable_if<std::is_enum<_Tp>::value, long unsigned int>::type torch::_hash_detail::dispatch_hash(const T&) [with T = at::ScalarType; typename std::enable_if<std::is_enum<_Tp>::value, long unsigned int>::type = long unsigned int]
 typename std::enable_if<std::is_enum<T>::value, std::size_t>::type dispatch_hash(const T& o) {
                                                                    ^~~~~~~~~~~~~
```

I can reproduce the error message on x64 and ARM64.

**Comment by peterjc123** [comment]
@stefan-it Here is my second PR, you can take it as an example. #3767

**Pull request closed without merging**
