### PR TITLE
[ROCm] Fix largeIndexBlockSize

### PR DESCRIPTION
**Pull request by pragupta**
On ROCm, hipification converts std::min to ::min, but ::min is not returning the right result. This impacts index_add_ operation on a large tensor, we end up picking the large values instead of max supported block size (128). This leads to GPU accessing memory out of bounds.

While we wait for ::min to be fixed, we can use < operator to compare instead of relying on ::min.

Example Code w/ failure:
```
D=6144
hidden_states = torch.zeros([16384, 6144],           device="cuda:0", dtype=torch.bfloat16)
index         = torch.randint(0, 16384, (1, 32, 16384), device="cuda:0", dtype=torch.int64)
output        = torch.empty([1, 32, 16384, 6144],    device="cuda:0", dtype=torch.bfloat16)
hidden_states.index_add_(0, index.view(-1), output.view(-1, D))
```

```
Traceback (most recent call last):
RuntimeError: HIP error: invalid configuration argument
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Review by pruthvistony — APPROVED** [review]

**Review by eqy — COMMENTED** [review]
If there is a reproducer snippet, add a test case please

**Comment by pragupta** [comment]
> If there is a reproducer snippet, add a test case please

@eqy -- I've added the reproducer code and the error generated with it in the PR description.


Example Code w/ failure:

```
D=6144
hidden_states = torch.zeros([16384, 6144],           device="cuda:0", dtype=torch.bfloat16)
index         = torch.randint(0, 16384, (1, 32, 16384), device="cuda:0", dtype=torch.int64)
output        = torch.empty([1, 32, 16384, 6144],    device="cuda:0", dtype=torch.bfloat16)
hidden_states.index_add_(0, index.view(-1), output.view(-1, D))
```
```
Traceback (most recent call last):
RuntimeError: HIP error: invalid configuration argument
```

**Comment by pragupta** [comment]
> If there is a reproducer snippet, add a test case please

@eqy  -- I misunderstood earlier. Added UT for this edge case. Thanks

**Comment by pragupta** [comment]
@eq -- if the UT looks good now, can you please provide your review on this one?

**Pull request closed without merging**
