### PR TITLE
[CI] change conda to miniforge for XPU images

### PR DESCRIPTION
**Pull request by chuanqi129**
The `.ci/docker` change with `ciflow/xpu` label will trigger docker images rebuild on xpu runner, but xpu runner can't use miniconda, change to miniforge. Works for https://github.com/pytorch/pytorch/issues/114850

### CODE REVIEW

**Comment by chuanqi129** [comment]
Refer the xpu test failure https://github.com/pytorch/pytorch/actions/runs/10553984824/job/29236258127?pr=134074

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
