### PR TITLE
Add torch.distributed.DistBackendError exception type, thrown from C10D_NCCL_CHECK

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#88134 Add torch.distributed.DistBackendError exception type, thrown from C10D_NCCL_CHECK**

Currently all of the distributed errors are thrown from the `TORCH_CHECK` macro which throws a generic `RuntimeError`. This change introduced a new error type `DistBackendError` which derives from `RuntimeError` to signify there was an error with the backend communication library. This allows for better error handling and analysis at higher levels in the stack. Motivation: https://docs.google.com/document/d/1j6VPOkC6znscliFuiDWMuMV1_fH4Abgdq7TCHMcXai4/edit#heading=h.a9rc38misyx8

Changes:
- introduce new error type
- Update `C10D_NCCL_CHECK`

Sample script to demonstrate new error type

```python
# python -m torch.distributed.run --nproc_per_node=2 <script>.py

import torch
import torch.distributed as dist

if __name__ == "__main__":
    dist.init_process_group("nccl")
    dist.broadcast(torch.tensor([1, 2, 3]).cuda(), 0)
```

Differential Revision: [D40998803](https://our.internmc.facebook.com/intern/diff/D40998803)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
LGTM! It seems that we only throw DistBackendError when failing in C10D_NCCL_CHECK. Had a couple of questions:

1. Is this a common point that captures all sources of NCCL / PG nccl failures? 
2. Are we planning to throw DistBackendError from other places in PT-D? Is there guidance to decide whether we should throw this error or regular runtime error?

**Comment by H-Huang** [comment]
> 1. Is this a common point that captures all sources of NCCL / PG nccl failures?

For the most part yes, this macro is also responsible for getting the error code / last error message from NCCL, so we use it for operations regarding NCCL (e.g. setting up communicators, collective failure, etc.)

2. Are we planning to throw DistBackendError from other places in PT-D? Is there guidance to decide whether we should throw this error or regular runtime error?

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40998803).

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40998803).

**Pull request closed without merging**
