### PR TITLE
improve F.adaptive_avg_pool2d error messages on mps

### LINKED ISSUE #123725: Doc feature request: add notes to ops that have major different behaviors on difference devices like between cpu and mps
### 📚 The doc issue

A bit of context: 

When I tried to port code that has `F.interpolate` from cpu to mps, I saw this error.
```
Adaptive pool MPS: input sizes must be divisible by output sizes.
```
Before finding #96056, I expected this op should behave exactly the same, so I thought it's a bug in PyTorch.

If we can't expect ops behave exactly the same (I don't mean precision-wise), I think we can add more notes about behavior discrepancies to the documentation.

### Suggest a potential alternative/fix

I think at least when throwing errors that are specific to devices, PyTorch should point to tracking issues.

### PR DESCRIPTION
**Pull request by ifsheldon**
Gives better error messages on mps. Partially fixes #123725 in the case of `F.adaptive_avg_pool2d`. This also relates to #96056.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Perfect, thanks!

**Comment by ifsheldon** [comment]
OK, fixed.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@pytorhcbot merge -f "Lint + Mac tests are green"

**Pull request closed without merging**
