### PR TITLE
[nn] full_backward{_pre}_hook: warning for Module returning dict, list, etc

### LINKED ISSUE #87540: `register_full_backward_hook` doesn't fire on module returning `List[Tensor]` or `Dict[Any , Tensor]`
### 🐛 Describe the bug

Backward hooks don't fire when a module returns `List` or `Dict` objects but they *do* fire when a module returns `Tuple`. Here's a repro script:

```python
import torch
import torch.nn as nn

def print_hook(module: nn.Module, _inputs, _outputs):
    print('hook triggered on', module)

class TestModule(nn.Module):
    def __init__(self, s):
        super().__init__()
        self.linear = nn.Linear(s, s)

    def forward(self, x):
        x = self.linear(x)
        return {'x': x}
        #return [x, x]
        #return x, x

x = torch.ones([10, 10])
model = TestModule(10)
model.register_full_backward_hook(print_hook)
y = model(x)['x']
loss = (y**2).sum()

print('backward started')
loss.backward()
print('backward complete')
```

Here's the output from the above script:

```
backward started
backward complete
```

It produces the same output when the `return [x, x]` version is run instead. When the `return x, x` version is run, we get the correct output:

```
backward started
hook triggered on TestModule(
  (linear): Linear(in_features=10, out_features=10, bias=True)
)
backward complete
```

All three should produce the same output -- with the hook triggering.

### Versions

```
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-124-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.3.58
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.12.1+cu113
[pip3] torchvision==0.13.1+cu113
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.12.1+cu113             pypi_0    pypi
[conda] torchvision               0.13.1+cu113             pypi_0    pypi
```

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

### PR DESCRIPTION
**Pull request by kshitij12345**
Fixes https://github.com/pytorch/pytorch/issues/87540

### CODE REVIEW

**Review by albanD — CHANGES_REQUESTED** [review]
None of the autograd/nn APIs unpack data structure. I don't think we should do it here either.

It is very easy for the user to do this if they need to.

**Comment by sharvil** [comment]
In many cases it's easy for a user to make changes to the code. But hooks are a great way to inspect the network and provide diagnostics even in a black-box environment.

@albanD, what would it take to get you to a "yes" on this request?

**Comment by albanD** [comment]
The thing is that we would need to plan to add a similar feature to all of the APIs to keep consistency.
Unfortunately, doing so would be breaking backward compatibility quite badly and could lead to user code being silently different.

While this is something we want to do for the future functional-style APIs we're working on. Changing the existing APIs is not in the plans right now.

**Comment by kshitij12345** [comment]
@albanD after reading the context on issue and here, I have two questions

* Is this change really BC-breaking? Given that we will support the previous behavior while adding new support.
* Assuming, it is BC-breaking, should we add a warning when output is not a tuple or tensor and a backward hook is present? I think it is would be better to atleast warn the user than silent ignore the hook.

**Comment by albanD** [comment]
> Is this change really BC-breaking? Given that we will support the previous behavior while adding new support.

It is BC-breaking in the sense that it changes the behavior for users. And this is not considered a "bug-fix" as this is the expected default for all functions in the APIs.
I do agree though that this one is unlikely to be a big issue in practice, but other APIs that we would have to change for consistency would be a lot more BC-breaking and definitely impact users (`autograd.Function` and `Module.__setattr__` for example).

> should we add a warning when output is not a tuple or tensor and a backward hook is present? I think it is would be better to atleast warn the user than silent ignore the hook.

Sure we can add such warning (for inputs as well btw).

**Comment by kshitij12345** [comment]
@albanD sorry this got under my radar. Have updated to raise a warning. 

Also, forward hooks work fine irrespective of the types of the input. Have added a test with that in mind.

**Review by albanD — APPROVED** [review]
SGTM

**Pull request closed without merging**
