### PR TITLE
[Discussion] Monitor CI/CD Windows jobs

### PR DESCRIPTION
**Pull request by cristianPanaite**
# Goal
The main goal is to create an automatic system that increases awareness of the state of CI/CD pipelines. The system should trigger a notification every time a Windows related job fails.  

# Proposed solution (only for GitHub Actions)

Using a GitHub Action Plugin, every time a job fails, there is an automatic message received in a Slack channel, in the official Slack workplace (this can be further discussed).

# Required configurations

## Slack configurations
Following the steps described in [Technique 2/Setup](https://github.com/marketplace/actions/slack-send)

## Workflow modifications
This plugin can be integrated following the steps described in [Technique 2/Usage](https://github.com/marketplace/actions/slack-send) with slight modifications. The modifications in this PR worked on my fork with a mock workflow. 
The `if: failure()` line will send the notification only if the job fails, so the channel is not spammed with passed situations which do not represent any concern for future development. 

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @pytorch/pytorch-dev-infra

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
This will bombard the channel with notification. You should limit this step to just pushes to trunk.

Also, perhaps a better mechanism for implementing a notification would be either to subscribe to webhook by a separate daemon or make some changes to pytorch bot, that listens to those

**Comment by ZainRizvi** [comment]
> This will bombard the channel with notification. You should limit this step to just pushes to trunk.
> 
> Also, perhaps a better mechanism for implementing a notification would be either to subscribe to webhook by a separate daemon or make some changes to pytorch bot, that listens to those

+1 having something subscribing to a "workflow failed" webhook would decouple the workflow from potential future issues with the slackbot messaging (e.g. the token expiring).

Retry bot here shows an example of how to listen to workflow completion via webhooks, and you could create another bot next to it for alerting on trunk failures. It could read the workflow status and post to slack from there

Code: https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/retryBot.ts

**Pull request closed without merging**
