### PR TITLE
[dynamo] Config to not emit runtime asserts

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122603

Repetition on squashed & merged by mistake https://github.com/pytorch/pytorch/pull/122406

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

Differential Revision: [D55312394](https://our.internmc.facebook.com/intern/diff/D55312394)

### CODE REVIEW

**Comment by IvanKobzarev** [comment]
@IvanKobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D55312394).

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
