### PR TITLE
Refactor and add VS 14.16 and 2019 CI for Windows

### PR DESCRIPTION
**Pull request by peterjc123**
Changes according to https://github.com/pytorch/pytorch/issues/18319.

### CODE REVIEW

**Comment by ezyang** [comment]
cc @zpao, this is going to aggravate our CircleCI on Windows spend.

@peterjc123 do you think maybe for these CI, we can only run builds (and not tests)? Since we are just trying to flush out compiler bugs. We could run tests on master only, if you still want them.

**Comment by peterjc123** [comment]
I guess the tests are still needed because it helps me to detect issues with VS2017 15.6 and VS2019 and then do commit 1fd76d6 and 51db97e. But it is okay to run only on master.

**Comment by ezyang** [comment]
Running only on master sounds great. Do you need me to adjust the CI or do you know how to do it?

**Comment by peterjc123** [comment]
Sorry, I have no idea how to do that. Could you please do me a favor?

**Review by ezyang — APPROVED** [review]

**Comment by zhangguanheng66** [comment]
Have to revert the PR because several Windows CI tests are broken.

**Pull request closed without merging**
