### PR TITLE
[ONNX] Add skip decorator for related tests

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #82040
* #82039
* #82038
* __->__ #82037

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]

**Comment by BowenBao** [comment]
@garymm cc for approval

**Comment by justinchuby** [comment]
Why were the tests skipped?

**Comment by BowenBao** [comment]
> Why were the tests skipped?

Both depend on optional lib within PyTorch.

**Review by garymm — APPROVED** [review]

**Pull request closed without merging**
