### PR TITLE
Build pytorch_android using Gradle wrapper.

### PR DESCRIPTION
**Pull request by H1Gdev**
[Here](https://docs.gradle.org/current/userguide/gradle_wrapper.html), there is the following description.
`The recommended way to execute any Gradle build is with the help of the Gradle Wrapper`

I took a little time to prepare Gradle for `pytorch_android` build. (version etc.)

I think using Gradle wrapper will make `pytorch_android` build more seamless.

Gradle wrapper version: 4.10.3

https://github.com/pytorch/pytorch/blob/250c71121b8ac2ef1899a2414c939d4d45fc2be4/.circleci/scripts/build_android_gradle.sh#L13

### CODE REVIEW

**Review by IvanKobzarev — APPROVED** [review]
Lint check fails on having +x permission for gradlew

Run (! find . \( -path ./third_party -o -path ./.git -o -path ./torch/bin -o -path ./build \) -prune -o -type f -executable -regextype posix-egrep -not -regex '.+(\.(bash|sh|py|so)|git-pre-commit|git-clang-format)$' -print | grep . || (echo 'The above files have executable permission; please remove their executable permission by using `chmod -x`'; false))
./android/gradlew
The above files have executable permission; please remove their executable permission by using `chmod -x`
Error: Process completed with exit code 1.

Need to check if without this it will run correctly

**Comment by H1Gdev** [comment]
@IvanKobzarev

> Need to check if without this it will run correctly

An error occurred if did not have execute permission.

```
Feb 05 01:51:24 /var/lib/jenkins/workspace/.circleci/scripts/../../android/build_test_app_custom.sh: line 32: /var/lib/jenkins/workspace/android/gradlew: Permission denied
```

Do you want to revert  d4076d2 commit ?

**Comment by IvanKobzarev** [comment]
@H1Gdev 
> Do you want to revert [d4076d2](https://github.com/pytorch/pytorch/commit/d4076d2eec40cca2708cf2876009abc08a8acde5) commit ?

Yes, please revert that commit. 
We will try to add gradlew to whitelist to avoid lint failure.
After that it should be good to land.

**Comment by IvanKobzarev** [comment]
@H1Gdev 
After reverting chmod -x,
Could you also rebase on the top of master once https://github.com/pytorch/pytorch/pull/51796 will be landed.

**Pull request closed without merging**
