### PR TITLE
[c10d] Build with -Werror

### PR DESCRIPTION
**Pull request by teng-li**
Also fixed a warning

As a thought while trying to solve #12854

### CODE REVIEW

**Comment by pietern** [comment]
-O2 should be already set (and overridable) with the CMake build type. It shouldn't be hardcoded.

**Comment by teng-li** [comment]
@pietern  I am not seeing -O2 is set in the actual compile command for c10d

**Comment by pietern** [comment]
@anderspapitto @Yangqing How is the optimization flag set? Following CMake guidelines, this flag should follow from the `CMAKE_BUILD_TYPE` setting. This way you can set it to `DEBUG` and have all targets automatically compiled with -O0 or something.

**Comment by teng-li** [comment]
Never mind, changed to -Werror only.

**Comment by teng-li** [comment]
Ninja log is hard to see build command, here we go:

```
/private/home/tengli/ccache/lib/c++  -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMAGMA_V2 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_CUDA=1 -DUSE_GCC_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -I../aten/src -I. -I../ -I../third_party/protobuf/src -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../aten/src/TH -I../aten/src/THC -Iaten/src -Icaffe2/aten/src -Icaffe2/aten/src/THC -I../torch/lib/c10d/.. -I../torch/lib/c10d/../../.. -Iinclude -I../c10/.. -Inccl/include -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem /private/home/tengli/miniconda3/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /private/home/tengli/miniconda3/include/python3.6m -isystem /private/home/tengli/miniconda3/lib/python3.6/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /public/apps/openmpi/2.1.1/gcc.5.4.0/include -isystem ../cmake/../third_party/cub -isystem ../third_party/ideep/include -isystem /public/apps/cuda/9.0/include -isystem /public/apps/cudnn/v7.0/cuda/include -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -fPIC   -DCUDA_HAS_FP16=1 -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -Wno-maybe-uninitialized -DTH_HAVE_THREAD -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wpessimizing-move -std=c++11 -std=gnu++11 -MD -MT caffe2/torch/lib/c10d/CMakeFiles/c10d.dir/ProcessGroup.cpp.o -MF caffe2/torch/lib/c10d/CMakeFiles/c10d.dir/ProcessGroup.cpp.o.d -o caffe2/torch/lib/c10d/CMakeFiles/c10d.dir/ProcessGroup.cpp.o -c ../torch/lib/c10d/ProcessGroup.cpp
```

It was set to O3

**Review by pietern — APPROVED** [review]

**Pull request closed without merging**
