### PR TITLE
[pytree] reorganize submodule structure for C++ and Python pytree

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #113258
* #113257
* #113256
* #113255
* __->__ #112278
* #112485

Reorganized the two C++ and Python pytree submodules into a subpackage. I think this would be easier to implement the abstract `PyTreeAPI` class with two implementations. And it will be much easier for the user to switch between the two implementations.

Before:

```text
torch
├── utils
│   ├── _pytree.py
│   ├── _cxx_pytree.py
│   ...
...
```

After:

```text
torch
├── utils
│   ├── _pytree
│   │   ├── __init__.py
│   │   └── api
│   │       ├── __init__.py
│   │       ├── cxx.py
│   │       └── python.py
│   ...
...
```

The `torch.utils._pytree` module will import all APIs from `torch.utils._pytree.api.python`.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @zou3519 @kiukchung @d4l3k @lucasllc

### CODE REVIEW

**Review by zou3519 — DISMISSED** [review]
Thanks for the refactor!

**Comment by mthrok** [comment]
@XuehaiPan Please also note that PyTorch Lightening uses the following items from `_pytree`.

```
from torch.utils._pytree import SUPPORTED_NODES, LeafSpec, PyTree, TreeSpec, _get_node_type, tree_unflatten
```

https://github.com/Lightning-AI/lightning/blob/1c86011dabaca211386be6acbee402c7bbda1f8c/src/lightning/pytorch/utilities/_pytree.py#L3

This commit went to the yesterday's nightly and torchaudio's test failed with the following stacktrace.

I am not sure what should be a public interface, but considering that PyTorch Lightning is popular framework, perhaps it is a good idea to keep exposing them via `torch.utils._pytree` for certain release cycles with warning, before completely removing them.

https://github.com/pytorch/audio/actions/runs/6814330080/job/18530958214

```
2023-11-09T16:16:07.7858323Z /opt/conda/envs/ci/lib/python3.10/importlib/__init__.py:126: in import_module
2023-11-09T16:16:07.7859178Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-11-09T16:16:07.7859909Z torchaudio_unittest/example/emformer_rnnt/test_mustc_lightning.py:13: in
2023-11-09T16:16:07.7860691Z     from asr.emformer_rnnt.mustc.lightning import MuSTCRNNTModule
2023-11-09T16:16:07.7861372Z ../examples/asr/emformer_rnnt/mustc/lightning.py:17: in
2023-11-09T16:16:07.7861954Z     from pytorch_lightning import LightningModule
2023-11-09T16:16:07.7862890Z /opt/conda/envs/ci/lib/python3.10/site-packages/pytorch_lightning/__init__.py:27: in
2023-11-09T16:16:07.7863775Z     from pytorch_lightning.callbacks import Callback  # noqa: E402
2023-11-09T16:16:07.7864787Z /opt/conda/envs/ci/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py:14: in
2023-11-09T16:16:07.7865798Z     from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
2023-11-09T16:16:07.7866950Z /opt/conda/envs/ci/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py:24: in
2023-11-09T16:16:07.7867918Z     from pytorch_lightning.callbacks.callback import Callback
2023-11-09T16:16:07.7868917Z /opt/conda/envs/ci/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py:22: in
2023-11-09T16:16:07.7869838Z     from pytorch_lightning.utilities.types import STEP_OUTPUT
2023-11-09T16:16:07.7870836Z /opt/conda/envs/ci/lib/python3.10/site-packages/pytorch_lightning/utilities/__init__.py:25: in
2023-11-09T16:16:07.7871895Z     from pytorch_lightning.utilities.combined_loader import CombinedLoader  # noqa: F401
2023-11-09T16:16:07.7873111Z /opt/conda/envs/ci/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py:22: in
2023-11-09T16:16:07.7874285Z     from pytorch_lightning.utilities._pytree import _map_and_unflatten, _tree_flatten, tree_unflatten
2023-11-09T16:16:07.7875462Z /opt/conda/envs/ci/lib/python3.10/site-packages/pytorch_lightning/utilities/_pytree.py:3: in
2023-11-09T16:16:07.7876629Z     from torch.utils._pytree import SUPPORTED_NODES, LeafSpec, PyTree, TreeSpec, _get_node_type, tree_unflatten
2023-11-09T16:16:07.7878299Z E   ImportError: cannot import name '_get_node_type' from 'torch.utils._pytree' (/opt/conda/envs/ci/lib/python3.10/site-packages/torch/utils/_pytree/__init__.py)
2023-11-09T16:16:07.7879825Z _ ERROR collecting test/torchaudio_unittest/example/emformer_rnnt/test_tedlium3_lightning.py _
2023-11-09T16:16:07.7881234Z ImportError while importing test module '/pytorch/audio/test/torchaudio_unittest/example/emformer_rnnt/test_tedlium3_lightning.py'.
```

**Comment by XuehaiPan** [comment]
I have added `_get_node_type` to `torch/utils/_pytree/__init__.py`. Now it should works as expected.

**Comment by PaliC** [comment]
@pytorchbot revert -m "Reverting this pr as the one under it in the stack is causing regressions in torchrec" -c ghfirst

On a side note, this pr is also causing regressions internally due to changing around the PyTreeAPI.  I'm unsure if you'd consider this bc-breaking? cc: @zou3519

**Comment by zou3519** [comment]
@XuehaiPan, we are going to need another approach for this. If everyone is depending on the details of torch.utils._pytree, then we shouldn't continue to refactor it and move pieces around.

**Comment by XuehaiPan** [comment]
> we are going to need another approach for this. If everyone is depending on the details of torch.utils._pytree, then we shouldn't continue to refactor it and move pieces around.

@zou3519 I found a solution to keep this refactoring (and follow-up `PyTreeAPI`) without bc-breaking. We can implement a `__getattr__` function in the `_pytree` module to fallback to the Python pytree submodule.

**Comment by zou3519** [comment]
@XuehaiPan the easiest way to not break anything is to leave the original API surface alone. It is possible for us to leave the original code alone but still implement a nice split in the python and C++ pytree APIs?

**Comment by XuehaiPan** [comment]
> It is possible for us to leave the original code alone but still implement a nice split in the python and C++ pytree APIs?

IMO, the `_cxx_pytree` and `_pytree` module names are a bit confusing. So I did this refactoring.

If we want the `_pytree.py` file to be kept untouched, we may need a new subpackage name under `torch.utils` which should be different from `_pytree`. Then we can have a symbolic link between the organized Python pytree API and the original `_pytree.py` file.

I think the current `__getattr__` function in the top module level should be enough to keep backward-compatibility.

**Comment by XuehaiPan** [comment]
> I think the current `__getattr__` function in the top module level should be enough to keep backward-compatibility.

Any thoughts about this? If we are not going to accept this refactoring, I can remove this in the ghstack.

**Comment by zou3519** [comment]
> > I think the current `__getattr__` function in the top module level should be enough to keep backward-compatibility.
> 
> Any thoughts about this? If we are not going to accept this refactoring, I can remove this in the ghstack.

I would prefer to not have the `__getattr__` function, because there's not a good way to test that we broke BC or not. It's easier to leave everything alone. 

> IMO, the _cxx_pytree and _pytree module names are a bit confusing. So I did this refactoring.

In the long term, it won't be confusing. We'll have a public torch.utils.pytree API, C++ pytree will hopefully be the default, and we will figure out how to do torch.compile support for pytrees to the point where we can eliminate most of the Python pytree implementation. It's OK for the current state to be a little confusing as long as we're working towards the long-term state.

**Pull request closed without merging**
