### PR TITLE
Fixed nondeterministic RG for ORT RNN tests

### PR DESCRIPTION
**Pull request by neginraoof**
Relaxing tolerance for ORT RNN tests

### CODE REVIEW

**Comment by neginraoof** [comment]
cc @dzhulgakov for review

**Comment by dzhulgakov** [comment]
It's up to you folks, but 10% difference (i.e. 0.1 rtols) sounds like a lot

**Comment by neginraoof** [comment]
@dzhulgakov Changing tolerance is not necessary actually. I changed that back. RG is deterministic now so tests should not be flaky anymore.

**Comment by neginraoof** [comment]
@dzhulgakov @bddppq Can we merge this small PR? CI failures that will be prevented.

**Review by lara-hdr — APPROVED** [review]

**Comment by lara-hdr** [comment]
@houseroad can we please merge this?

**Review by houseroad — APPROVED** [review]
LGTM, will merge it soon.

**Pull request closed without merging**
