### PR TITLE
[quant][core][docs] Add docs for torch.quantize_per_tensor_dynamic

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72311

Summary:
att

Test Plan:
doc page in github

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D33996034](https://our.internmc.facebook.com/intern/diff/D33996034)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33996034).

**Review by bdhirsh — APPROVED** [review]
thanks! don't forget to cherry-pick into the release branch!

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33996034).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33996034).

**Pull request closed without merging**
