### PR TITLE
Link BLAS privately

### PR DESCRIPTION
**Pull request by hmaarrfk**
We've some users report that they are getting symbol collisions when linking to blas.

I don't see a need to re-export the blas library symbols.

I figured I would share here for other packagers to be able to benefit too.

xref: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/116
xref: https://github.com/conda-forge/openblas-feedstock/issues/134

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Let me know if there is a usecase I'm missing. However, it seems natural that each library links to the source of the symbol, instead of linking through libraries generated by pytorch.

**Review by ezyang — APPROVED** [review]
assuming binary tests work ok

**Comment by hmaarrfk** [comment]
Thank you for the fast review. It is really appreciate and gives me confidence that this patch is correct.

**Comment by hmaarrfk** [comment]
I presume some of the failures are not due to my changes. let me know if you need me to merge or something.

**Comment by hmaarrfk** [comment]
Is there a way for you to let me test on your CIs without being close to automatically merging?

**Comment by hmaarrfk** [comment]
I would like to try adding these 3 lines:

```patch
diff --git a/caffe2/CMakeLists.txt b/caffe2/CMakeLists.txt
index eda99a7668..53355b548a 100644
--- a/caffe2/CMakeLists.txt
+++ b/caffe2/CMakeLists.txt
@@ -2008,6 +2008,9 @@ if(BUILD_PYTHON)
 
   target_link_libraries(caffe2_pybind11_state PRIVATE
       torch_library python::python pybind::pybind11)
+  if(CAFFE2_USE_MKLDNN)
+      target_link_libraries(caffe2_pybind11_state PRIVATE caffe2::mkldnn)
+  endif()
   if(WIN32)
     target_link_libraries(caffe2_pybind11_state PRIVATE onnx_proto)
   endif(WIN32)
```

it is not as clean as I would want it, but I think it is worth a shot.

I'm just really confused why we don't see this build error at conda-forge:
https://github.com/conda-forge/pytorch-cpu-feedstock/pull/116

**Comment by hmaarrfk** [comment]
After seeing https://github.com/pytorch/pytorch/blob/master/caffe2/python/CMakeLists.txt#L10 i'm more convinced of my added additions.

**Pull request closed without merging**
