### PR TITLE
[.github] Fix typo in job name

### PR DESCRIPTION
**Pull request by malfet**
Also add spaces, job name does not have to be a single world

### CODE REVIEW

**Review by zengk95 — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Review by janeyx99 — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by malfet** [comment]
> Merge failed due to Command `git -C /home/runner/work/pytorch/pytorch push origin master` returned non-zero exit code 1
> 
> Raised by https://github.com/pytorch/pytorch/actions/runs/1854193427

Wow, I like new error message, need to update PAT for mergebot to allow workflow changes

**Pull request closed without merging**
