### PR TITLE
Update Dockerfile to use Ubuntu 17.04, GCC 6.3, and CUDA 9.0

### PR DESCRIPTION
**Pull request by FuriouslyCurious**
I have been testing this Dockerfile mod for past two weeks, and speed + stability are great.  Users can benefit from newer CUDA 9.0 and GCC 6.3 (included with Ubuntu 17.04).  

Base image provided by Felix @ NVidia: 
https://gitlab.com/nvidia/cuda/issues/9

### CODE REVIEW

**Comment by ngimel** [comment]
You need to install cuda 9 version of libnccl https://github.com/FuriouslyCurious/pytorch/blob/master/Dockerfile#L12-L13, and also comment out this line https://github.com/FuriouslyCurious/pytorch/blob/master/Dockerfile#L28, because magma for cuda 9 is not yet available, and cuda 8 magma causes hangs on multi-GPU systems. 
Also would be nice if you add compling for 7.0 compute capability for those lucky ones who have voltas https://github.com/FuriouslyCurious/pytorch/blob/master/Dockerfile#L27

**Comment by ngimel** [comment]
Also, looks like the base image does not have cudnn in it?

**Comment by FuriouslyCurious** [comment]
cuDNN is in this Dockerfile : https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/devel/cudnn7/Dockerfile

But looks like the resulting image is not available on NVidia official repo.  Let me work on that and update the Dockerfile next week.

**Comment by ngimel** [comment]
You've linked to the Dockerfile for 9.0-devel-cudnn7-ubuntu16.04, and you are using 9.0-devel-ubuntu17.04 as your base image. Both are available on the dockerhub, but the latter does not have cudnn in it, the reason being that cudnn does not officially support ubuntu 17.04. It can run there, in all probability, but nobody has tested it.

**Comment by FuriouslyCurious** [comment]
Hi @ngimel Felix@NVidia confirmed that cuDNN is not officially supported on Ubuntu 17.04.  I am using it for an internal image and cuDNN is working without a glitch, but it would be risky to switch PyTorch official image to 17.04 without NVidia support.   

I am closing this PR for now.

**Pull request closed without merging**
