### PR TITLE
[BE] And delete `DeprecatedTypeProperties` cast

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #139358

Differential Revision: [D65549001](https://our.internmc.facebook.com/intern/diff/D65549001)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D65549001).

**Pull request merged**
