### PR TITLE
Updated docs to include environment var required on Windows

### PR DESCRIPTION
**Pull request by davidbrownellWork**

### CODE REVIEW

**Comment by soumith** [comment]
@davidbrownellMS that environment var is dependent on what GPU you have.

cc: @peterjc123 do we absolutely require this env var? I thought it is auto-detected

**Comment by peterjc123** [comment]
@davidbrownellMS I don't think this line is needed. Maybe the auto-detection logic is broken? What error did you get?

**Comment by peterjc123** [comment]
The reason outlaid by @TJ XU from the conversion:
> One observation is that in Pytorch's ci script it's forcing TORCH_CUDA_ARCH_LIST=5.2, but as soon as we use an arch>=5.3, the native f16 support functions in Eigen/src/Core/arch/CUDA/Half.h would cause the failure David was seeing.
one thing we can do is to patch Half.h to see if CUDA version is >=9, then use this signature:  return __hadd(::__half(a), ::__half(b));
  instead of   return __hadd(a, b);
So we need to patch that submodule to make it work, just like what we do [here](https://github.com/pytorch/pytorch/blob/master/aten/src/THCUNN/THCHalfAutoNumerics.cuh#L199).

**Comment by ezyang** [comment]
Yes, this PR is not the right way to go about doing things. Instead, we should fix the MSVC build on newer architectures.

@yf225 Do you think we should do a build-only run for a newer CUDA arch, on both Windows and Linux?

**Comment by Tixxx** [comment]
@peterjc123 Wrong TJ tagged :) I use a different handle on Github.
FYI, i tested below patch on my machine and it worked with any arch level:

diff --git a/Eigen/src/Core/arch/CUDA/Half.h b/Eigen/src/Core/arch/CUDA/Half.h
index 2bb3d0d9b..b9f1fe6cf 100644
--- a/Eigen/src/Core/arch/CUDA/Half.h
+++ b/Eigen/src/Core/arch/CUDA/Half.h
@@ -209,7 +209,11 @@ namespace half_impl {
 // conversion steps back and forth.
 
 EIGEN_STRONG_INLINE __device__ half operator + (const half& a, const half& b) {
+#if defined(EIGEN_CUDACC_VER) && EIGEN_CUDACC_VER >= 90000
+  return __hadd(::__half(a), ::__half(b));
+#else
   return __hadd(a, b);
+#endif
 }
 EIGEN_STRONG_INLINE __device__ half operator * (const half& a, const half& b) {
   return __hmul(a, b);
@@ -218,9 +222,13 @@ EIGEN_STRONG_INLINE __device__ half operator - (const half& a, const half& b) {
   return __hsub(a, b);
 }
 EIGEN_STRONG_INLINE __device__ half operator / (const half& a, const half& b) {
+#if defined(EIGEN_CUDACC_VER) && EIGEN_CUDACC_VER >= 90000
+  return __hdiv(a, b);
+#else
   float num = __half2float(a);
   float denom = __half2float(b);
   return __float2half(num / denom);
+#endif
 }
 EIGEN_STRONG_INLINE __device__ half operator - (const half& a) {
   return __hneg(a);

**Pull request closed without merging**
