### PR TITLE
Add meta functions for `lerp`, `addcmul`, and `addcdiv`.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136909

This PR adds new meta functions for `lerp`, `addcmul`, and `addcdiv` (including their
respective inplace versions).

These functions only had refs implementations, which was being the root cause of a
significant overhead ([issue][1]) when running `AdamW` optimizer step on PyTorch/XLA
backend. Running the meta functions resulted in the following improvements:

- `lerp` calls: 1,550ms to 140ms (10x)
- `addcdiv` calls: 640ms to 350ms (1.8x)
- `addcmul` calls: 620ms to 300ms (2.05x)

[1]: https://github.com/pytorch/xla/issues/7923

cc @miladm @JackCaoG

### CODE REVIEW

**Review by amjames — COMMENTED** [review]
Tests? I would expect that we could at least remove a skip for these missing metafuncs?

**Comment by ysiraichi** [comment]
I think they were already running. But, I believe their refs were being run as meta functions. From this PR on, the actual meta functions are running (I had a few CI failures on their tests due to faulty implementation).

**Review by jansel — APPROVED** [review]

**Comment by albanD** [comment]
@pytorchbot revert -m "breaks trunk jobs" -c nosignal

See https://github.com/pytorch/pytorch/actions/runs/11173115116/job/31061370721 for details.

**Comment by ysiraichi** [comment]
@albanD trunk CI is green even though I didn't modify anything. Is it okay to assume there was some fix on `main` branch and re-land this PR? Or is the CI failure still there, it's just that we can't see it, here?

**Comment by albanD** [comment]
On the link I shared above, you can see that the ci is failing in the lerp function.

**Comment by JackCaoG** [comment]
@ysiraichi should we try to merge this one again?

**Comment by ysiraichi** [comment]
Yeah. I have just rebased. Once the CI is green, I will merge it.

**Comment by ysiraichi** [comment]
This last CI failure is odd. It looks completely unrelated to this PR. However, this PR seems to be the only branch hitting this error. I will try rebasing once again, and see if the error goes away.

**Pull request closed without merging**
