### PR TITLE
Remove CUDA 11.6 from nightly builds

### PR DESCRIPTION
**Pull request by atalman**
Remove CUDA 11.6 from nightly builds.
Following the Release readme here: https://github.com/pytorch/pytorch/blob/master/RELEASE.md#release-compatibility-matrix

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Can we stop/migrate CI first?

**Comment by atalman** [comment]
PR to remove from CI: https://github.com/pytorch/pytorch/pull/93406

**Review by malfet — APPROVED** [review]
Looks fine, now that we have https://github.com/pytorch/pytorch/pull/93406

**Pull request closed without merging**
