### PR TITLE
Raise error in clip_grad when no grad found

### PR DESCRIPTION
**Pull request by innerlee**
This serves as more of an issue rather than pr.

Currently if no grad is found, it errors anyway because of `stack([])` in later steps.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Should it instead just be a no-op?

**Comment by innerlee** [comment]
Good idea, however the hard part is how to determine the device of the result tensor when parameters are empty?

**Comment by innerlee** [comment]
Namely, we need to define what to return when there is no parameters (with grad)

**Comment by ezyang** [comment]
You can't tell, unless the user also specifies device/etc explicitly in the function call (like in factories). Honestly, giving an earlier error seems better to me. If you agree I'm happy to merge this. We should have a test for it though.

**Comment by vadimkantorov** [comment]
If I understand this PR, it would create a behavior difference between clip_by_norm and clip_by_value wrt if no parameters have grads.

> Good idea, however the hard part is how to determine the device of the result tensor when parameters are empty?

Are you talking about the norm to return? Can't it just be None or python zero? in that case

**Comment by ezyang** [comment]
I mean, we could... but is that what the user expects in that case? (If it is, OK!)

**Comment by innerlee** [comment]
The trouble here is that when there is no grads, the behavior is undefined. So this is an API design issue

**Comment by jbschlosser** [comment]
Closing this PR as out-of-date, as #38615 changed the function to return 0 total_norm when the parameter list is empty.

**Pull request closed without merging**
