### PR TITLE
Silu support Complex for CUDA

### LINKED ISSUE #89382: Feature request: complex CUDA nn.silu()
### 🐛 Describe the bug

Test on the CPU:

    import torch
    m = torch.nn.SiLU()
    input = torch.rand([2], dtype=torch.complex64)
    print(m(input))

result: tensor([0.0490+0.3563j, 0.0439+0.1437j])

Test on the GPU:

    import torch
    m = torch.nn.SiLU().cuda()
    input = torch.rand([2], dtype=torch.complex64).cuda()
    print(m(input))

result: RuntimeError: "silu_cuda" not implemented for 'ComplexFloat'

The test code runs successfully on the torch.nn.SiLU() CPU, but throws an exception on the GPU.

The same situation exists for torch.nn.functional.silu.
### Versions

pytorch: 1.8
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel @ezyang @anjali411 @dylanbespalko @Lezcano @nikitaved

### PR DESCRIPTION
**Pull request by fffrog**
Fixes #89382

Silu support Complex for CUDA

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Why can't you use the same code in both cases there?

For testing, https://github.com/pytorch/pytorch/blob/6af6b8f728426fb7551630e28148c0017fa501bc/torch/testing/_internal/common_methods_invocations.py#L13481 is where the tests are. So if these are not failing about un-expected success. This is most likely not fixing it.

**Comment by FFFrog** [comment]
> Why can't you use the same code in both cases there?
> 
> For testing,
> 
> https://github.com/pytorch/pytorch/blob/6af6b8f728426fb7551630e28148c0017fa501bc/torch/testing/_internal/common_methods_invocations.py#L13481
> 
> is where the tests are. So if these are not failing about un-expected success. This is most likely not fixing it.

Thank you.
The new commit is ready, please have a look at it

**Comment by albanD** [comment]
Thanks!
The test failure look relevant right?

**Comment by FFFrog** [comment]
> Thanks! The test failure look relevant right?

Yes, fixed it now.

**Review by albanD — COMMENTED** [review]
That looks good. I'm still surprised that the opinfo test is not complaining https://github.com/pytorch/pytorch/blob/6af6b8f728426fb7551630e28148c0017fa501bc/torch/testing/_internal/common_methods_invocations.py#L13481 
Are these tests not testing complex dtypes at all?

**Comment by FFFrog** [comment]
> That looks good. I'm still surprised that the opinfo test is not complaining
> 
> https://github.com/pytorch/pytorch/blob/6af6b8f728426fb7551630e28148c0017fa501bc/torch/testing/_internal/common_methods_invocations.py#L13481
> 
> 
> Are these tests not testing complex dtypes at all?

I submitted a new commit to enable complex test about cuda in opinfo test

**Comment by FFFrog** [comment]
> That looks good. I'm still surprised that the opinfo test is not complaining
> 
> https://github.com/pytorch/pytorch/blob/6af6b8f728426fb7551630e28148c0017fa501bc/torch/testing/_internal/common_methods_invocations.py#L13481
> 
> 
> Are these tests not testing complex dtypes at all?

I'm not sure if this modification has something to do with your question

**Review by albanD — APPROVED** [review]
Thanks!

**Pull request closed without merging**
