### PR TITLE
Revert D47143445: Multisect successfully blamed D47143445 for test or build failures

### PR DESCRIPTION
**Pull request by huydhn**
Summary:
This diff is reverting D47143445
D47143445: [dynamo] Lazy disable_dynamo API out-of-dynamo  (#104317) by anijain2305 has been identified to be causing the following test or build failures:

Tests affected:
- [caffe2/caffe2/fb/predictor/trt_bc:tensorrt_backwards_compatibility_test - TensorRTBackwardsCompatibilityTest.InlineCvrFp32](https://www.internalfb.com/intern/test/844424999929568/)

Here's the Multisect link:
https://www.internalfb.com/multisect/2375498
Here are the tasks that are relevant to this breakage:

We're generating a revert to back out the changes in this diff, please note the backout may land if someone accepts it.

If you believe this diff has been generated in error you may Commandeer and Abandon it.

Test Plan: check D47216591

Reviewed By: 842974287

Differential Revision: D47166892

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Comment by huydhn** [comment]
I'm exporting this one from the internal revert diff D47166892 (cc @zyan0).  Let me know if this one is needed or a forward fix is preferred

**Comment by zyan0** [comment]
Let's land the revert to unblock since it's a holiday. We can do forward fix once people are back. cc @anijain2305

**Comment by huydhn** [comment]
@pytochbot rebase -m main

**Comment by huydhn** [comment]
The original PR has been reverted https://github.com/pytorch/pytorch/pull/104317

**Pull request closed without merging**
