### PR TITLE
Check canary_models for models too in torchbench.py

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101081

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by desertfire — APPROVED** [review]

**Review by desertfire — COMMENTED** [review]
Do you also plan to bump up the torchbench pin?

**Comment by ezyang** [comment]
yeah, that's a separate pr

**Pull request closed without merging**
