### PR TITLE
Add output_mask

### PR DESCRIPTION
**Pull request by to-mi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66071
* #66070
* #66069
* __->__ #66068

Differential Revision: [D31431802](https://our.internmc.facebook.com/intern/diff/D31431802)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Looks good!

**Comment by albanD** [comment]
As you're changing the signature of an op here, you will need to update the backward compatibility tests to say that it is expected in https://github.com/pytorch/pytorch/blob/master/test/backward_compatibility/check_backward_compatibility.py#L56

The other CI failures are due to a broken master, you can rebase on top of latest master to make sure they are fixed?


Also, when using ghstack, to modify a PR below, you should do an interactive rebase, update the commit you want (make sure that after the update you still have 4 commits). And then run ghstack again to update github.

**Comment by to-mi** [comment]
Thanks for the instructions! Seems all the of the checks now passed.

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31431802).

**Pull request closed without merging**
