### PR TITLE
Port softplus activation to Aten(CPU+CUDA)

### LINKED ISSUE #24633: Migrate `softplus` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by XiaobingSuper**
@VitalyFedyunin, This PR is about port Softplus activation to Aten:
**Test script:**
```
import torch
import torch.nn as nn
import time

torch.manual_seed(0)
def _time():
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    return time.time()

device = "cpu"
m = nn.Softplus()
if torch.cuda.is_available():
    device = "cuda"
    m = m.cuda()

#warm up
for n in [100, 10000]:
    input = torch.randn(128, n, requires_grad=True, device=device)
    grad_output = torch.ones(128, n, device=device)
    for i in range(1000):
        output = m(input)
        output.backward(grad_output)

for n in [100, 10000]:
    input = torch.randn(128, n, requires_grad=True, device=device)
    grad_output = torch.ones(128, n, device=device)
    fwd_t = 0
    bwd_t = 0
    for i in range(10000):
        t1 = _time()
        output = m(input)
        t2 = _time()
        output.backward(grad_output)
        t3 = _time()
        fwd_t = fwd_t + (t2 -t1)
        bwd_t = bwd_t + (t3 - t2)
    fwd_avg = fwd_t / 10000 * 1000
    bwd_avg = bwd_t / 10000 * 1000
    print("input size(128, %d) forward time is %.2f (ms); backwad avg time is %.2f (ms)."
          % (n, fwd_avg, bwd_avg))
```
Test Device: CPU: skx-8180, GPU: Tesla P40.
Perfromance:
Before:
```
GPU:
input size(128, 100) forward time is 0.06 (ms); backwad avg time is 0.12 (ms).
input size(128, 10000) forward time is 0.06 (ms); backwad avg time is 0.18 (ms).
CPU:
input size(128, 100) forward time is 1.16 (ms); backwad avg time is 0.69 (ms).
input size(128, 10000) forward time is 60.19 (ms); backwad avg time is 31.86 (ms).
```
After:
```
GPU:
input size(128, 100) forward time is 0.05 (ms); backwad avg time is 0.11 (ms).
input size(128, 10000) forward time is 0.06 (ms); backwad avg time is 0.17 (ms).
CPU:
input size(128, 100) forward time is 0.43 (ms); backwad avg time is 0.16 (ms).
input size(128, 10000) forward time is 1.65 (ms); backwad avg time is 0.83 (ms).
```
`OMP_NUM_THREADS=1:`
```
Before:
input size(128, 100) forward time is 0.53 (ms); backwad avg time is 0.28 (ms).
input size(128, 10000) forward time is 51.33 (ms); backwad avg time is 25.48 (ms).
After:
input size(128, 100) forward time is 0.44 (ms); backwad avg time is 0.16 (ms).
input size(128, 10000) forward time is 42.05 (ms); backwad avg time is 13.97 (ms).
```

Fix #24633, #24634, #24766, #24767.

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
#24633 Migrate softplus from the TH to Aten (CUDA)
 #24634 Migrate softplus_backward from the TH to Aten (CUDA)
 #24766 Migrate softplus from the TH to Aten (CPU)
 #24767 Migrate softplus_backward from the TH to Aten (CPU)

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin, @ezyang, please first see https://github.com/pytorch/pytorch/issues/31110 before review this code. Note: the Implementation of forward and backward just according to the old TH code in this PR.

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 0c7a3e2:
* **2/2** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=0c7a3e27bf9799354f3097d21d99cb235d4b07e9).

### :detective: 2 new failures recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4013746) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_legacy_test (1/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=77223492) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=77223492))
<details>
<summary>
<code>Dec 19 03:47:31 RuntimeError: test_jit_legacy failed!</code>
</summary>

```
Dec 19 03:47:31 Ran 2307 tests in 149.637s 
Dec 19 03:47:31  
Dec 19 03:47:31 FAILED (failures=1, errors=1, skipped=59, expected failures=1) 
Dec 19 03:47:31  
Dec 19 03:47:31 Generating XML reports... 
Dec 19 03:47:31 Traceback (most recent call last): 
Dec 19 03:47:31   File "test/run_test.py", line 456, in <module> 
Dec 19 03:47:31     main() 
Dec 19 03:47:31   File "test/run_test.py", line 449, in main 
Dec 19 03:47:31     raise RuntimeError(message) 
Dec 19 03:47:31 RuntimeError: test_jit_legacy failed! 
Dec 19 03:47:31 + cleanup 
Dec 19 03:47:31 + retcode=1 
Dec 19 03:47:31 + set +x 
Dec 19 03:47:31 =================== sccache compilation log =================== 
Dec 19 03:47:31 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 19 03:47:31 Compile requests               304 
Dec 19 03:47:31 Compile requests executed        0 
Dec 19 03:47:31 Cache hits                       0 
Dec 19 03:47:31 Cache misses                     0 
Dec 19 03:47:31 Cache timeouts                   0 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4013745) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test (2/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=77228086) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=77228086))
<details>
<summary>
<code>Dec 19 03:48:24 RuntimeError: test_jit_simple failed!</code>
</summary>

```
Dec 19 03:48:24 Ran 2307 tests in 89.334s 
Dec 19 03:48:24  
Dec 19 03:48:24 FAILED (failures=1, errors=1, skipped=77, expected failures=1) 
Dec 19 03:48:24  
Dec 19 03:48:24 Generating XML reports... 
Dec 19 03:48:24 Traceback (most recent call last): 
Dec 19 03:48:24   File "test/run_test.py", line 456, in <module> 
Dec 19 03:48:24     main() 
Dec 19 03:48:24   File "test/run_test.py", line 449, in main 
Dec 19 03:48:24     raise RuntimeError(message) 
Dec 19 03:48:24 RuntimeError: test_jit_simple failed! 
Dec 19 03:48:24 + cleanup 
Dec 19 03:48:24 + retcode=1 
Dec 19 03:48:24 + set +x 
Dec 19 03:48:24 =================== sccache compilation log =================== 
Dec 19 03:48:24 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 19 03:48:24 Compile requests                56 
Dec 19 03:48:24 Compile requests executed        0 
Dec 19 03:48:24 Cache hits                       0 
Dec 19 03:48:24 Cache misses                     0 
Dec 19 03:48:24 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by XiaobingSuper** [comment]
Just rebased.

**Pull request closed without merging**
