### PR TITLE
Better function annotations for `nn.functional`

### LINKED ISSUE #102768: Incomplete type annotations for `Callable`s in `nn.functional`
### 🐛 Describe the bug

In `torch/nn/functional.pyi` (which is generated from `...pyi.in`), there's a list of annotations like
```python
max_pool1d: Callable
max_pool2d: Callable
max_pool3d: Callable
...
logsigmoid: Callable
softplus: Callable
softshrink: Callable
...
```
These are not quite useful as type hints, except for telling us they're callable objects (instead of tensors etc.).

It would be better to annotate them with the signature of each function.

### Versions

master

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

### PR DESCRIPTION
**Pull request by lkct**
Fixes #102768

- Provides proper function declarations in generated `torch/nn/functional.pyi`.
- Moves some functions from manually defined in `functional.pyi.in` to generated code, in order to single-source the signature.
- Includes some of the functions in `torch._C._nn` into its `.pyi.in`, but not exhaustive (only what's already there).

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

### CODE REVIEW

**Comment by lkct** [comment]
Hi @albanD @jbschlosser @mikaylagawarecki 
(also if anyone else may help, please)

Regarding the mypy error, any ideas on how we should annotate the overloads?
An example from my current implementation that mypy complains:
```python
@overload
def max_pool1d(input: Tensor, ..., ceil_mode: bool = False, return_indices: Literal[False] = False) -> Tensor: ...
@overload
def max_pool1d(input: Tensor, ..., ceil_mode: bool = False, return_indices: Literal[True] = ...) -> Tuple[Tensor, Tensor]: ...
```
(of course, there's a fallback option to mark the return as `Union`, but type checkers will never know which exactly it is)

---

A related example is
https://github.com/pytorch/pytorch/blob/85efacee07072f81d09735ec93e954aed74c42d7/tools/pyi/gen_pyi.py#L621-L624
but the flag is kw-only.

**Comment by lkct** [comment]
Resolved this by splitting positional arg and kw arg into two overloads. Locally tested with `reveal_type` and they work properly in both cases.

**Comment by drisspg** [comment]
Thank you for the hardwork. I think this approvable but one thing I am curious about - https://github.com/pytorch/pytorch/issues/102428 We have this issue. The hope is to embed more types directly into the .py files instead of the .pyi stubs. Do you think that this PR gets us closer to the resolution described in this issue?

**Comment by lkct** [comment]
Thanks for recognizing my work. And thanks for indirectly hinting at a minor bug (I noticed it when looking into the following question).

> Do you think that this PR gets us closer to the resolution described in this issue?

My answer is YES. At least those I touched on in this PR can be ported into `functional.py` without much effort. I'm sure `_add_docstr` can be easily handled, while dispatching of `max_pool`s may need some treatment but should be doable.

However, I'm unsure whether other parts of this .pyi template can be merged into the `functional.py` file.
https://github.com/pytorch/pytorch/blob/main/torch/nn/functional.pyi.in
It would be good if someone who knows more about these files could lend a hand.

Can you please open an issue if we are going to address this for `nn/functional.py`? Further discussion can go on there.

**Comment by lkct** [comment]
@drisspg Any updates? Thanks.

**Comment by drisspg** [comment]
@lkct hey sorry I thought I approved already, I think this looks good and I do think we want to get as many things as possible into functional.py But for now I think this shud be good to land

**Review by drisspg — APPROVED** [review]

**Comment by lkct** [comment]
@drisspg Thanks! BTW, do we need some more appropriate tags for this?

**Comment by drisspg** [comment]
Just added, if you wanted to take a stab at creating that issue for consolidating the typing information into functional.py type hints, that would be great!

**Review by malfet — APPROVED** [review]
It would be nice to have some sort of test automation for those types of changes to prevent future regressions. I.e. it should be possibel to call `reveal_type` from `test_typing` to check the signature, isn't it?

**Comment by lkct** [comment]
> is it covered by mypy at the moment

Yes, there're mypy checks against the consistency throughout the repo, but No, there isn't any dedicated checks.

Previously these functions were interpreted by mypy as `Callable[..., Any]` so everything would pass.
Now the `lintrunner` guarantees the newly generated .pyi files are still consistent with all uses in the repo.

**Comment by malfet** [comment]
> Previously these functions were interpreted by mypy as `Callable[..., Any]` so everything would pass. Now the `lintrunner` guarantees the newly generated .pyi files are still consistent with all uses in the repo.

I could easily missed some changes, which lintrunner linter checks type annotation consistency?

**Comment by lkct** [comment]
> which lintrunner linter checks type annotation consistency?

MYPY. It would run on after .pyi files are generated.

**Comment by lkct** [comment]
> I.e. it should be possibel to call `reveal_type` from `test_typing` to check the signature, isn't it?

@malfet 
Please take a look at the comment I left at #103376. The same problem. I don't think `test_typing.py` works.

**Comment by lkct** [comment]
@malfet Please see the update in #103376. `test_typing` is not in CI and is broken.

**Pull request closed without merging**
