### PR TITLE
Improve python3 discovery code in CMake

### PR DESCRIPTION
**Pull request by cyyever**
The improvement is based on my comments in #124613 and it also fixes the current linux-s390x-binary-manywheel  CI failures.
 

cc @malfet @seemethere

### CODE REVIEW

**Comment by cyyever** [comment]
@Skylion007 Help verify it?

**Comment by Skylion007** [comment]
@cyyever It seems to be creating a ton of failures?

**Comment by cyyever** [comment]
> @cyyever It seems to be creating a ton of failures?

No, the current failures can be tried later as usual, the important thing is that linux-s390x-binary-manywheel tests have passed.

**Comment by cyyever** [comment]
@Skylion007 I will rerun the failed tests after the running ones finish.

**Comment by cyyever** [comment]
@Skylion007 There are only ROCM failures at the present, which are unrelated.

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
