### PR TITLE
[Bug fix for JIT pass - GraphFuser]

### PR DESCRIPTION
**Pull request by jjsjann123**
passing FusionCallback and Symbol to recursive GraphFuser calls. It ensures
consistent fusion in nested Blocks.

### CODE REVIEW

**Comment by jjsjann123** [comment]
This fixes issue #22734

**Comment by jjsjann123** [comment]
cc @ngimel @csarofeen

**Comment by ngimel** [comment]
cc @bwasti

**Review by bwasti — APPROVED** [review]
great catch -- sorry for the delay on review

**Comment by ezyang** [comment]
Sorry, this was stuck long enough trying to land that it merge conflicted :(

**Comment by jjsjann123** [comment]
No worries, should be all good now.

**Pull request closed without merging**
