### PR TITLE
[quant][fx] Support conv1d and its fusion variants in QAT

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74506
* #74505

Summary:
This PR supports qat Conv1d, ConvBn1d, ConvBnReLU1d, ConvReLU1d in qat in FX Graph Mode Quantization

Test Plan:
python test/test_quantization.py TestQuantizeFx.test_conv_bn_relu

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D35032995](https://our.internmc.facebook.com/intern/diff/D35032995)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35032995).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35032995).

**Comment by vkuzo** [comment]
what's the plan for Eager mode workflow support?  Can we also add it either in this PR or in a follow-up PR?

**Review by vkuzo — APPROVED** [review]

**Comment by jerryzh168** [comment]
> what's the plan for Eager mode workflow support? Can we also add it either in this PR or in a follow-up PR?

we should support it, but not sure if it is P0 or not, the tests in eager mode could be refactored to be more general so that adding test is easier

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35032995).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35032995).

**Comment by vkuzo** [comment]
> we should support it, but not sure if it is P0 or not, the tests in eager mode could be refactored to be more general so that adding test is easier

I think that it should ideally be added at the same priority, both Eager mode and FX graph mode are first class citizens.

**Pull request closed without merging**
