### PR TITLE
[Inductor] Update AttrsDescriptor instantiation for Triton changes

### PR DESCRIPTION
**Pull request by alexbaden**
The `AttrsDescriptor` class has been present in Triton for almost a year now (introduced [here](https://github.com/triton-lang/triton/commit/72c983392749d31fef953beae5d983db9d778b41)), so we should be able to rely on it existing. I am in the process of supporting the new `AttrsDescriptor` class and @jansel suggested I split changes to the existing class out separately to make sure nothing breaks removing the legacy attribute descriptor attributes. 

Initially I attempted to remove the branching around detecting whether `AttrsDescriptor` exists but that breaks because PyTorch must build without Triton. So, I went back and updated for the naming introduced in the commit linked above, and also removed two unused attributes `divisible_by_8` and `ids_to_fold` which were removed in Feb 2024 (https://github.com/triton-lang/triton/pull/3122 and https://github.com/triton-lang/triton/pull/3080 respectively).

With these changes only the internal workings of the `AttrsDescriptor` class will differ between supported Triton versions, but the data stored will remain consistent.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by jansel** [comment]
Tests are failing, you can't import triton in global scope since PyTorch needs to run without it installed.

**Comment by alexbaden** [comment]
@jansel I updated this PR to leave the branch in case Triton is not installed but to remove deprecated attributes and naming.

**Comment by alexbaden** [comment]
Pushed a fix for the lint error, all other tests passed.

**Review by jansel — APPROVED** [review]

**Comment by alexbaden** [comment]
@jansel I do not think the failing test is related to this PR. On the previous commit (prior to the lint fix) the result was:
```
PASS: benchmark ('add_loop_inductor_gpu', 'compile_time_instruction_count') pass, actual result 22443112811 +1.23% is within expected 22171041650 ±1.50%
```
but on the lint fix commit we're getting 
```
REGRESSION: benchmark ('add_loop_inductor_gpu', 'compile_time_instruction_count') failed, actual result 22510259893 is 1.53% higher than expected 22171041650 ±+1.50% if this is an expected regression, please update the expected results.
```
just slightly above expected. It looks like a few recent commits on main have similar results (right around 1.50% with some just barely exceeding the threshold). What do you think?

**Comment by jansel** [comment]
Let's see if a rebase fixes that test failure.

**Comment by jansel** [comment]
It looks like the regression did not go away.  Is there any reason why this would make compile time worse?

We could also update the expected time for the test.

**Comment by alexbaden** [comment]
I looked last night and the failure was still there - but today it looks like it went away? Or am I misreading the latest run?

**Comment by jansel** [comment]
Not sure what happened there...

**Pull request closed without merging**
