### PR TITLE
Enable mypy check in torch/_inductor/optimize_indexing.py

### PR DESCRIPTION
**Pull request by fffrog**
Fixes #105230

```shell
$ lintrunner init && lintrunner -a torch/_inductor/optimize_indexing.py
...
ok No lint issues.
Successfully applied all patches.
```

```shell
$ mypy torch/_inductor/optimize_indexing.py
Success: no issues found in 1 source file

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
nice! you'll need to remove `optimize_indexing` from the mypy exclude list

**Comment by FFFrog** [comment]
> nice! you'll need to remove `optimize_indexing` from the mypy exclude list

Thank you. Have removed it.

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
