### PR TITLE
Skip test_mem_leak on Windows (v1.6.0)

### PR DESCRIPTION
**Pull request by peterjc123**
(cherry picked from commit 3fb6f038256a3a5ce43e857409ce4ffb807d93a5)

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
I guess this happened because nvidia driver version has been updated.

**Comment by peterjc123** [comment]
@malfet You mean the nvidia driver has been updated in the circleci image?

**Comment by malfet** [comment]
@peterjc123 yes, otherwise there are no reason why should have started failing in 1.6.0 branch as it was cut before the regression.

**Comment by peterjc123** [comment]
But this test has just been introduced several days ago.

**Pull request merged**
