### PR TITLE
Run compat test against both current parent and parent of the reverted commit

### PR DESCRIPTION
**Pull request by huydhn**
This false alarm happens every time we revert a commit with schema change, for example https://hud.pytorch.org/pytorch/pytorch/commit/60bf851931f58e528be927d96115272248f531fd.  In such case, the schema is back to where it was, but would still be falsely marked as breaking compatibility.

So the fix here is to:

* On pull and trunk, perform the current `forward_backward_compatibility` against the merge base and parent commit as usual 
* On trunk, if the test fails, check if it's a reverted commit using the PR_BODY heuristic where `REVERTED_SHA` is empty for a normal commit:
```
SHA_REGEX="This reverts commit ([a-zA-Z0-9]+)\."
REVERTED_SHA=$(echo "${PR_BODY}" | grep -E "${SHA_REGEX}" | awk '{print $NF}' | sed 's/.$//')
```
* If it's a reverted commit, perform another `forward_backward_compatibility` check against the base of the reverted SHA extracted by the regex above

Also I get rid of `pip install -r requirements.txt` in the test to avoid any possibility of getting networking issue there

### CODE REVIEW

**Comment by janeyx99** [comment]
Some thoughts:
- Is the main motivation here to remove red on trunk? Otherwise, I don't think it's necessarily a false alarm that the bc test fails when an aten API is no longer existent.
- Instead of rerunning on fail, should we be checking whether something is a revert PR on trunk as the first run?
- Thanks for removing the pip install reqs!

**Comment by huydhn** [comment]
>     * Is the main motivation here to remove red on trunk? Otherwise, I don't think it's necessarily a false alarm that the bc test fails when an aten API is no longer existent.

Yeah, that's my main motivation.  To run one more check if 1) PR is a reverted commit and 2) it fails the first BC check on turnk

>     * Instead of rerunning on fail, should we be checking whether something is a revert PR on trunk as the first run?

I thought a bit on this.  A reverted PR might or might not change the schema.  Only those that originally change the schema does.  So comparing against the parent commit is still a valid thing.  The proposed change here is to do an additional check against the parent of the reverted commit.  In a sense, there are 2 kinds of reverted commits in this context 1) those that don't change any schema (the majority I guess), they would need to be compared against their parent and 2) those that change the schema (the minority), bc compat fails for this group but would be green if we do another check here against the parent of the reverted commit.

I guess I don't have a good way to separate these two categories, thus I come up with an additional check approach.  Thoughts?

**Comment by ZainRizvi** [comment]
> > ```
> > * Instead of rerunning on fail, should we be checking whether something is a revert PR on trunk as the first run?
> > ```
> 
> A reverted PR might or might not change the schema. Only those that originally change the schema does. So comparing against the parent commit is still a valid thing.

I don't why you'd want to run this test against a revert change which didn't change the schema to begin with.  

Is there a legitimate forward or backwards compatibility break that you're thinking could be introduced by a revert? Otherwise it's prob safe to ignore compat checks during reverts

**Comment by huydhn** [comment]
> I don't understand why you'd want to run this test against a revert
> 
> Is there a legitimate forward or backwards compatibility break that you're thinking could be introduced by a revert? Otherwise it's prob safe to ignore compat checks during reverts

True.  I kind of agree that we don't really care about forward or backwards compatibility break for reverted commits, so this test could be ignored.  That's a valid solution.

I guess I'm just being more careful not to miss anything here by still running the check.  Reverting a schema update commit would reset the schema to its state before that commit, so the test is updated to do just that.

**Comment by ZainRizvi** [comment]
> > I don't understand why you'd want to run this test against a revert
> > Is there a legitimate forward or backwards compatibility break that you're thinking could be introduced by a revert? Otherwise it's prob safe to ignore compat checks during reverts
> 
> True. I kind of agree that we don't really care about forward or backwards compatibility break for reverted commits, so this test could be ignored. That's a valid solution.
> 
> I guess I'm just being careful not to miss anything here by still running the check. Reverting a schema update commit would reset the schema to its state before that commit, so the test is updated to do just that in addition to what it currently does.

In the case of a legitimate schema break, doesn't the test continue to fail on every succeeding commit? So that even in the remote chance of a revert introducing a legitimate error, commits that come after that one would all continue to show the failure?

Assuming the above is correct, I'd be inclined to keeping with a conceptually simple architecture than cover for an unlikely corner case (at least until we start seeing that corner case actually occurring)

**Comment by huydhn** [comment]
> In the case of a legitimate schema break, doesn't the test continue to fail on every succeeding commit? So that even in the remote chance of a revert introducing a legitimate error, commits that come after that one would all continue to show the failure?
> 
> Assuming the above is correct, I'd be inclined to keeping with a conceptually simple architecture than cover for an unlikely corner case (at least until we start seeing that corner case actually occurring)

Ah nope, the test won't fail on succeeding commit.  So here is how it works with and without this change:

1. The test `forward_backward_compatibility` behaves differently between running in PR and running in trunk.  This change doesn't torch the former, so how it runs in PR remains the same
1. When running in trunk:
    1. In the current state without the change, the test compares the current commit and the immediate commit before it that they are compatible.  Note that it will always be the immediate commit before it.
    2. The previous step can fail when a schema breakage is introduced.  Because it only compares against the immediate commit before it, it wrongly fail when reverting a schema update change, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/92e03cd583c027a4100a13682cf65771b80569da.  It shouldn't fail because the schema is back to where it was before.  The test doesn't know that because it only looks into the immediate commit before it
    3. Thus come in this PR, `forward_backward_compatibility` is updated to handled the case of reverted commit, so that it also compare against the schema before the breaking change.

Here is a concrete example from HUD:

1. OLD SCHEMA: [	Fix convit_base (#95174)](https://hud.pytorch.org/pytorch/pytorch/commit/7ca623c2e106926fea2c500b12b3b13bcf293fec).  Test passes (OLD SCHEMA (1) == OLD SCHEMA (2))
1. OLD SCHEMA: [Revert "Add torch.empty_permuted (#95069)"](https://hud.pytorch.org/pytorch/pytorch/commit/92e03cd583c027a4100a13682cf65771b80569da) **fails `forward_backward_compatibility` check** because the schema is back to be the OLD SCHEMA (8), and OLD SCHEMA (8) is not forward/backward compatible with the NEW SCHEMA (3). In this case, a function is removed (no backward compatible)
1. NEW SCHEMA: [Add a check for n<0 and a test for it (#95144)](https://hud.pytorch.org/pytorch/pytorch/commit/079476c6b20166a8f876328c53c98c27cd1a260d).  Test passes (NEW SCHEMA (3) == NEW SCHEMA (4))
2. NEW SCHEMA: [Revert "Introduce constrain_range](https://hud.pytorch.org/pytorch/pytorch/commit/4e88547c957cdc3a3c87e7b873520638ccfbd667).  Test passes (NEW SCHEMA (4) == NEW SCHEMA (5))
3. NEW SCHEMA: [code is clean enough that some warnings](https://hud.pytorch.org/pytorch/pytorch/commit/1ab112cfab5e9e5b3ec2521f0b4e6b93b6ff90d9).  Test passes (NEW SCHEMA (5) == NEW SCHEMA (6))
4. ....
5. NEW SCHEMA: [Add torch.empty_permuted (#95069)](https://hud.pytorch.org/pytorch/pytorch/commit/bedeb1f014795c497f11942ff4c772431d1c157a).  NEW SCHEMA (7) != OLD SCHEMA (8), but the test passes because adding a new op is forward backward compatible
6. OLD SCHEMA: [fix 'sympy.core.logic' has no attribute 'boolalg'](https://hud.pytorch.org/pytorch/pytorch/commit/50ec4ddb70a52dbc52bc009fe2d5703acb09e7fc)

So the change here detects that 2 is a reverted commit of 7, and it compares the OLD SCHEMA (2) with the OLD SCHEMA (8), parent of 7.  This ensures that the schema is back to what it was before.

**Pull request closed without merging**
