### PR TITLE
Enable torch._prims.amax/amin for nvFuser executor

### PR DESCRIPTION
**Pull request by IvanYashchuk**
This PR adds nvFuser implementations for `torch._prims.amax` and `torch._prims.amin` reduction functions. Currently, nvFuser refuses to reduce the 0d tensor, so these inputs are skipped in tests for now.

An accompanying fix replaces `collections.Sequence` -> `collections.abc.Sequence` in refs because `collections.Sequence` is deprecated and removed in Python 3.10

Many ops that were skipped for the nvFuser executor test are now enabled.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by IvanYashchuk** [comment]
XLA and ONNX CI failures are unrelated.

**Pull request closed without merging**
