### PR TITLE
[JIT] IRParser: optionally create name->value map of the parsed IR.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#19551 [JIT] IRParser: optionally create name->value map of the parsed IR.**

Differential Revision: [D15028056](https://our.internmc.facebook.com/intern/diff/D15028056)

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Comment by eellison** [comment]
I think it would be pretty simple to have a pass decoupled from IRParser that does this. I think that would be better.

**Comment by ZolotukhinM** [comment]
> I think it would be pretty simple to have a pass decoupled from IRParser that does this. I think that would be better.

IRParser already creates such a map, this PR just exposes it through API. Also, I'm not sure it would be possible to recreate the map without parsing again, could you please expand a little on what exactly you meant?

**Comment by eellison** [comment]
Once the graph is created you can query the name of a value with `v->uniqueName()`. Using this api you can create a name -> value mapping that would work on graphs that are not created through parsing. There is a similar api for finding a symbol exposed in python_ir "findNode"

**Comment by ZolotukhinM** [comment]
> Once the graph is created you can query the name of a value with `v->uniqueName()`. Using this api you can create a name -> value mapping that would work on graphs that are not created through parsing. There is a similar api for finding a symbol exposed in python_ir "findNode"

uniqueNames can never be used as keys in a map, since there are no guarantees about them - i.e. it is legit for us to create IR without names at all. Thus, we cannot rely on uniqueName being the same as the name in the input IR string.
In contrast, providing a map from a *user-provided* name to the created value is always correct (modulo the fact that if the same name is used multiple times we will relate the name to only one of the corresponding values).

**Pull request closed without merging**
