### PR TITLE
allow re-assignment if previous type is None

### LINKED ISSUE #44446: [jit] class type optional type annotation not working properly
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by hlahkar**
Fixes #44446

### CODE REVIEW

**Comment by wanchaol** [comment]
can you add a test for this?

**Comment by hlahkar** [comment]
> can you add a test for this?

Test cases are added for the same

**Review by eellison — COMMENTED** [review]
I don't think this is type safe as written. also the example test issue shows that the. real issue here is that we should use class type annotations... i think there's an issue somewhere for that.

**Comment by hlahkar** [comment]
> I don't think this is type safe as written. also the example test issue shows that the. real issue here is that we should use class type annotations... i think there's an issue somewhere for that.

I will check and get back on this

**Comment by Oktai15** [comment]
@suo @wanchaol @ezyang this PR was closed, but the problem still exists. How to fix it?

**Pull request closed without merging**
