### PR TITLE
[xplat] Update XNNPACK to github revision d7111a5

### PR DESCRIPTION
**Pull request by digantdesai**
Summary:

Differential Revision: D33576242

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by digantdesai** [comment]
FYI @kimishpatel

**Review by kimishpatel — APPROVED** [review]
Looks good but bunch of builds are failing

**Comment by digantdesai** [comment]
> Looks good but bunch of builds are failing
Yeah, I need to dig into them. 

Multiple different issues for 15 build failures,
1 - gcc5.4 + aarch32 doesn't understand the array initializer (3 out of 15)
2 - CMake errors about all_microkernels not linking to anything (6 out of 15)
3 - MS VC++ syntax errors in compute.h (4 out of 15)
4 - Missing neon flag for one of the generated files (2 out of 15)

Fun!

**Comment by kimishpatel** [comment]
> > Looks good but bunch of builds are failing
> 
> Yeah, I need to dig into them.
> 
> Multiple different issues for 15 build failures, 1 - gcc5.4 + aarch32 doesn't understand the array initializer (3 out of 15) 2 - CMake errors about all_microkernels not linking to anything (6 out of 15) 3 - MS VC++ syntax errors in compute.h (4 out of 15) 4 - Missing neon flag for one of the generated files (2 out of 15)
> 
> Fun!

Envy you... NOT.

**Pull request closed without merging**
