### PR TITLE
avoid zero seed in init of distributed data loader

### LINKED ISSUE #61289: Zero seed in DistributedSampler
Here you can find zero default seed in the data loader. However, it is recommended to avoid zero seed.
https://github.com/pytorch/pytorch/blob/05c1e5b65571d2fa14b0f06c37ba970fd7cc43d0/torch/utils/data/distributed.py#L61

### PR DESCRIPTION
**Pull request by ferrine**
From docs in https://pytorch.org/docs/stable/generated/torch.Generator.html

> Avoid having many 0 bits in the seed.

Fixes #61289

### CODE REVIEW

**Review by rohan-varma — COMMENTED** [review]
Looks good, but can you move the seed value to be a constant and use that in init:

```
_DIST_SAMPLER_DEFAULT_SEED = ...
....
seed: init = _DIST_SAMPLER_DEFAULT_SEED
```

**Review by VitalyFedyunin — APPROVED** [review]
Looks good, but better use `0b1111111111111111111` notation

**Comment by ferrine** [comment]
I'll add the proposed changes after weekends

**Comment by ferrine** [comment]
> Looks good, but better use `0b1111111111111111111` notation

Nice idea, I'll avoid a full 1111 for this, I'm actually afraid this might lead to overflow instead. I'll just randomly generate bits

**Comment by ejguan** [comment]
You can use this initial seed as a reference.
https://github.com/pytorch/pytorch/blob/44cc873fba5e5ffc4d4d4eef3bd370b653ce1ce1/c10/core/GeneratorImpl.h#L56-L58

**Comment by ferrine** [comment]
I guess I have to rebase

**Pull request closed without merging**
