### PR TITLE
Canonicalize includes in torch, and add tests for it

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#36303 Canonicalize includes in torch, and add tests for it**

Differential Revision: [D20943003](https://our.internmc.facebook.com/intern/diff/D20943003)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
NB there's a decent chance that code merged in the meantime will conflict with this, you'll have to fix things up if that happens.

**Comment by zasdfgbnm** [comment]
@ezyang Sure, the command to quickly fix most files is:
```bash
find torch -type f -exec sed -i 's/#include "\(.*\)"/#include <\1>/g' {} \;
```
Some files needs manual intervention

**Comment by ezyang** [comment]
RIP, this gonna need some internal build system changes.

```
xplat/caffe2/aten/src/ATen/native/quantized/cpu/qnnpack/src/requantization/gemmlowp-scalar.c:16:10: fatal error: 'ATen/native/quantized/cpu/qnnpack/src/requantization/gemmlowp-scalar.h' file not found
#include <ATen/native/quantized/cpu/qnnpack/src/requantization/gemmlowp-scalar.h>
```

**Comment by ezyang** [comment]
oops, wrong PR, it's the one before this one

**Comment by zasdfgbnm** [comment]
@ezyang This is also ready

**Pull request closed without merging**
