### PR TITLE
refactor mm_plus_mm check to pattern match

### LINKED ISSUE #103101: Refactor mm_plus_mm to check conditions upfront
### 🚀 The feature, motivation and pitch

We always lower `x @ y + a @ b` to [tuned_mm_plus_mm](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/fx_passes/post_grad.py#L138-L139) even though we only lower to the fused op in special conditions, see https://github.com/pytorch/pytorch/blob/08c4a442fd589f380ac0dd6f1126d6e144f449e5/torch/_inductor/kernel/mm_plus_mm.py#L154-L159. 

We could refactor this check to occur in the pattern matching pass so that these mms/adds aren't prevented from participating in other patterns or fusions.

### Alternatives

_No response_

### Additional context

_No response_

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225

### PR DESCRIPTION
**Pull request by hgl71964**
Fixes #103101

replace #103253

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel

### CODE REVIEW

**Comment by colesbury** [comment]
@jansel would you please review this?

**Review by jansel — APPROVED** [review]

**Comment by hgl71964** [comment]
I updated the test file, because now pattern-match to mm_plus_mm check input shapes, and if not valid, it rejects the match. The old test file doesn't take into account of this

**Comment by jansel** [comment]
Thanks!

**Pull request closed without merging**
