### PR TITLE
Make .to() methods native functions (to fix JIT tracing)

### PR DESCRIPTION
**Pull request by apaszke**

### CODE REVIEW

**Review by zdevito — APPROVED** [review]
This looks good!

**Comment by zdevito** [comment]
There are some legit test failures

**Comment by gchanan** [comment]
This will conflict with https://github.com/pytorch/pytorch/pull/11497 and also https://github.com/pytorch/pytorch/pull/11489.

**Comment by apaszke** [comment]
@gchanan what's the ETA for those changes? We need this PR to land before we cut the release branch, because currently no type or device casts can be traced

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/pull/11497 is ready to go, just waiting on tests.  This can go in before https://github.com/pytorch/pytorch/pull/11489 -- that may take another day or two to iron out.

**Comment by apaszke** [comment]
That sounds good. Please let me know once you land that change.

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/pull/11497 landed.

**Pull request closed without merging**
