### PR TITLE
IR: Swap a sstream for to_string

### LINKED ISSUE #79583: Torchscript Serialisation is broken for numbers over 1000 if global locale is set
### 🐛 Describe the bug

>   File "/home/sacha/.local/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
>     cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
> RuntimeError: expected ) but found 'number' here:
> Serialized   File "code/__torch__/backbone/sacha.py", line 189
>   softmax2_blocks : __torch__.torch.nn.modules.container.___torch_mangle_550.Sequential
>   last_blocks : __torch__.backbone.common.___torch_mangle_558.sacha_IR
>   def forward(self.1,027: __torch__.backbone.sacha.AttentionModule_stage4,
>                   ~~ <--- HERE
>     argument_1: Tensor) -> Tensor:
>     last_blocks = self.1,027.last_blocks
> 

For deeper models, I can no longer load the serialised model due to the commas placed in numbers >= 1000.

### Versions

1.12.0-dev

cc @ezyang @seemethere @malfet @ngimel

### PR DESCRIPTION
**Pull request by xsacha**
Avoids locale issues. Technically faster anyway.

Fixes #79583

### CODE REVIEW

**Comment by davidberard98** [comment]
Thanks @xsacha - btw did you verify that this fixes your issue locally?

**Comment by xsacha** [comment]
No, technically this should probably done throughout the code generation as stringstream may not make sense here.
The real clean solution is finding where locale set. It isn't being set globally on my system and the same issue doesn't happen in other apps using stringstream.

**Comment by davidberard98** [comment]
@xsacha would you mind checking whether or not this fixes the issue locally?

From: https://en.cppreference.com/w/cpp/string/basic_string/to_string. I see:
```
std::to_string relies on the current locale for formatting purposes, and therefore concurrent calls to std::to_string from multiple threads may result in partial serialization of calls. C++17 provides [std::to_chars](https://en.cppreference.com/w/cpp/utility/to_chars) as a higher-performance locale-independent alternative.
```

^ based on this it seems like std::to_string wouldn't fix the issue?

**Comment by xsacha** [comment]
Thanks, I'll look at a different solution.

**Pull request closed without merging**
