### PR TITLE
Allow replicate/circular padding of single dimension of 4D/5D tensor

### PR DESCRIPTION
**Pull request by cjblocker**
`torch.nn.functional.pad` accepts a flexible number of padding dimensions when doing constant padding, e.g. from the docs
```python
>>> t4d = torch.empty(3, 3, 4, 2)
>>> p1d = (1, 1) # pad last dim by 1 on each side
>>> out = F.pad(t4d, p1d, "constant", 0)  # effectively zero padding
>>> print(out.size())
torch.Size([3, 3, 4, 4])
```
But you cannot pad a single dimension when mode is circular, replicate, or reflect:
```python
>>> out = F.pad(t4d, p1d, "circular")
# AssertionError: 4D tensors expect 4 values for padding
```
You can work around this by appending zeros, `p1d = (1,1,0,0)`.
```python
>>> out = F.pad(t4d,(1,1,0,0), "circular")
>>> print(out.size())
torch.Size([3, 3, 4, 4])
```
These differences are unexpected and unnecessary.
This PR appends the zero entries to the pad if necessary.

I can update docs/tests if interested in merging.
Thanks!

### CODE REVIEW

**Comment by albanD** [comment]
That sounds like a reasonable thing to add. Is there a reason not to add the 3 value case? Does it work for constant padding?

cc @mruberry  does that sound good to you?

**Comment by mruberry** [comment]
If we did do this we'd need a docs update, although I worry it could result in unexpected behavior.

What does NumPy's pad do?

**Comment by cjblocker** [comment]
> Is there a reason not to add the 3 value case?

The docs say you must provide two values per dimension, and there is an assert statement earlier in the function that makes sure `len(pad)` is even. It is unclear what the user would be intending with 3 values.

> What does NumPy's pad do?

In `np.pad`, you provide padding sizes starting from the first dimension and moving forward. Thus if you provide a single padding tuple, you only pad the 0th-dimension. `F.pad` pads in the opposite direction, starting from the last dimension moving backward. [The docs](https://pytorch.org/docs/stable/nn.functional.html#pad) state clearly that if you provide a single value pair, it will be applied to the last dimension:
> For example, to pad only the last dimension of the input tensor, then
   `pad` has the form `(padding_left, padding_right)`
    to pad the last 2 dimensions of the input tensor, then use
    `(padding_left, padding_right, padding_top, padding_bottom)`

which is why I think `F.pad(t4d, (1,1), "circular")` raising an error is unexpected.

The differences between `np.pad` and `F.pad` are a little confusing, and each interface is awkward when trying to pad the last dimension or first dimension respectively. There is a proposal in gh-38000 that I think would be a better format and I would be willing to work on if the original author is not going to. The aim of this PR is just to make the interface of `F.pad` more consistent with itself and its docs.

**Comment by albanD** [comment]
That sounds good to me. Thanks for all the details.
I think you can add the test and doc and it will be ready to go!

**Pull request closed without merging**
