### PR TITLE
Fix docstring in autograd

### PR DESCRIPTION
**Pull request by spzala**
Fix docstrings in autograd files. 

The fix can be verified by running pydocstyle path-to-file --count

Related #112593

**BEFORE the PR:** 
pydocstyle torch/autograd/anomaly_mode.py --count
8
pydocstyle torch/autograd/__init__.py --count
9

**AFTER the PR:** 
pydocstyle torch/autograd/anomaly_mode.py --count
0
pydocstyle torch/autograd/__init__.py --count
0

cc @svekars @brycebortree

### CODE REVIEW

**Comment by spzala** [comment]
@soulitzer @svekars the changes were pretty much approved in the https://github.com/pytorch/pytorch/pull/128248 I have created this separate PR for easier review per discussion there. Thanks!

**Review by soulitzer — APPROVED** [review]
Thanks!

**Pull request closed without merging**
