### PR TITLE
[Easy] Fix todo by enable tests for cuda

### PR DESCRIPTION
**Pull request by zeshengzong**
Fix TODO in `test_tensor_creation_ops.py` file:

```python
# TODO: update to work on CUDA, too
```

**Test Result**

```bash
$ pytest test/test_tensor_creation_ops.py
```

image

```bash
$ lintrunner
```
image

cc @ezyang @albanD

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Change sounds ok. But this is most likely because these tests were failing? Let's see what CI says !

**Comment by zeshengzong** [comment]
Hello, tests running on my local env works as expect, and CI looks good so far. Thanks! :D

**Review by albanD — APPROVED** [review]
Ok then! Thanks for looking it up!

**Pull request closed without merging**
