### PR TITLE
Add indices convertion.

### LINKED ISSUE #9211: [feature request] Convert "indices" variable in "torch.utils.data.dataset.random_split" to list
## Issue description
random_split fills indices variable using torch.randperm function, which returns tensor. Through Subset class its values goes to Dataset.__getitem__. If I override getitem, tensor values are ok for indexing list, but with pandas DataFrame it raises TypeError. Maybe it would be better to convert indices to list variable at start.
## Code example
df = pd.DataFrame([1, 2])
tn = torch.tensor([0, 1])
df.iloc[tn[0]]
...
...
TypeError: len() of unsized object

### PR DESCRIPTION
**Pull request by floatn**
Fix #9211 .

### CODE REVIEW

**Comment by apaszke** [comment]
I'm not entirely convinced that this is a good fix. If Pandas has issues with using scalars to index them then it's their problem, and we shouldn't have all users who didn't need this functionality pay for `.tolist()`. It's really a fairly expensive call.

**Comment by floatn** [comment]
Here's actually a slightly deep problem.
Python recommends an int or a slice object as an argument for __getitem__ method. [](url)https://docs.python.org/3/reference/datamodel.html#object.__getitem__
[https://docs.python.org/3.4/glossary.html#term-slice](url)
A torch.tensor is not an int object but it can be a slice object. To be a slice object it has to have __getitem__ and __len__ methods.
Here, tn2 is a tensor which is a slice object:
> ---tn2 = torch.tensor([1, 2])
> ---tn2.__getitem__(0)
> tensor(1)
> ---tn2.__len__()
> 2 
> 
Here, tn1 is a tensor which is, kind of, not a slice object, and PyTorch (not Pandas) try to use it as an argument for __getitem__:
> ---tn2 = torch.tensor([1, 2])
> ---tn1 = tn2[0]
> ---tn1
tensor(1)
> ---tn1.__getitem__(0)
tensor(1)
> ---tn1.__len__()
>Traceback (most recent call last):
 > File "<stdin>", line 1, in <module>
 > File "/usr/lib/python3.6/site-packages/torch/tensor.py", line 349, in __len__
  >  raise TypeError("len() of a 0-d tensor")
>TypeError: len() of a 0-d tensor

Error output for a '0-d tensor' (a common case for an index) makes this class's instances unfavorable as a __getitem__ argument.
Maybe this requires fixing of the torch.tensor class?

**Comment by ezyang** [comment]
cc @fmassa who originally suggested this strategy

**Comment by fmassa** [comment]
Note that `.tolist()` is only called once in the beginning of the script (to create the random split).
I don't think that runtime-wise it matters.

I don't see any issue in merging this as is. It doesn't break backwards-compatibility, and fixes an issue with pandas (that we don't have control over).

**Comment by apaszke** [comment]
Idk, people can create random subsets multiple times and then it might matter performance wise. There’s really no good reason apart from the bug in pandas which should be reported there. See [PEP 357](https://www.python.org/dev/peps/pep-0357/)

**Comment by fmassa** [comment]
I still think that this doesn't matter, and we have already things like that in the [`RandomSampler`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L51) (for different reasons), so I think this is really a micro-optimization.

Or we just say that it's a bug in pandas and do nothing about it ourselves :-)

**Comment by fmassa** [comment]
(speaking of which, we might probably want to add `.tolist()` to a few other places as well, like [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L98)

**Review by fmassa — APPROVED** [review]

**Comment by floatn** [comment]
When pandas check index value:
[https://github.com/pandas-dev/pandas/blob/1a23779f09abc6ebf908d66ee88b973b767e2e3c/pandas/core/indexing.py#L2075]()
...it comes down here:
[https://github.com/pandas-dev/pandas/blob/1a23779f09abc6ebf908d66ee88b973b767e2e3c/pandas/core/dtypes/inference.py#L283-L284]()
`    return (isinstance(obj, Iterable) and
            not isinstance(obj, string_and_binary_types))`
A 0-d tensor returns True on isinstance(obj, Iterable) call. But returns an error on len() call. It states itself as an iterable, but doesn't have length. /0

**Comment by fmassa** [comment]
@floatn hum... I'm not sure that's the right place where the problem happens, because we are following the same behavior of numpy there.
```python
import numpy as np
from collections import Iterable

a = np.array(1)
print(isinstance(a, Iterable))  # True
iter(a)
# TypeError: iteration over a 0-d array
```

So according to your reasoning it should also fail for numpy arrays.

**Comment by floatn** [comment]
Now I'm convinced it is a pandas problem indeed. :)

**Comment by ezyang** [comment]
@fmassa @floatn What should we do with this PR?

**Comment by fmassa** [comment]
I'm ok with merging this, and avoids us having to index a 1d tensor (which is slow in 0.4)

**Comment by floatn** [comment]
I am new to committing and NN as well. So, with lowest confidence:
1. [PEP 357](https://www.python.org/dev/peps/pep-0357/) - a good reason to refuse. (-1)
2. Fixing the issue with **tolist()** would be user-friendly, I guess. (+1)
3. , but still, it will not fix all the **len(0-d)** Errors, which doesn't seem so hard to pop up. (-1)

-1 in the end.
I have just started a topic at Pandas project. [#21946](https://github.com/pandas-dev/pandas/issues/21946)

**Comment by soumith** [comment]
closed based on the concluded `-1` in the end.

**Pull request closed without merging**
