### PR TITLE
AOT logging: log fw_metadata with each graph

### PR DESCRIPTION
**Pull request by bdhirsh**
Log fw_metadata for each AOT graph. This is helpful for seeing information about subclass graph inputs/outputs/tangents, and lots of other stuff

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #123970
* __->__ #118646
* #118645

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by tugsbayasgalan — APPROVED** [review]

**Review by ezyang — APPROVED** [review]
Thanks, long overdue lol. Instead of controlling it with `enable_log`, consider unconditionally logging with `debug` instead, so it's controllable via TORCH_LOGS

**Comment by ezyang** [comment]
needs a quick test update

**Pull request closed without merging**
