### PR TITLE
meta registration of _linalg_svd

### PR DESCRIPTION
**Pull request by avikchaudhuri**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #92021
* __->__ #92020
* #92019

Differential Revision: [D42457575](https://our.internmc.facebook.com/intern/diff/D42457575/)

### CODE REVIEW

**Review by SherlockNoMad — APPROVED** [review]

**Comment by avikchaudhuri** [comment]
@SherlockNoMad something is messed up here, lots of tests are failing. I suspect it's because this diff somehow changes the behavior of the real op (I think meta op is working fine).

Small repro:
```
import torch

A = torch.randn([1, 0], device="meta")
print(f"A: {A.shape} | {A.stride()}")
U, S, V = torch.linalg.svd(A, full_matrices=True)
print(f"\n[real, full_matrices=True] U: {U.shape} | {U.stride()}")
print(f"[real, full_matrices=True] S: {S.shape} | {S.stride()}")
print(f"[real, full_matrices=True] V: {V.shape} | {V.stride()}")
U, S, V = torch.linalg.svd(A, full_matrices=False)
print(f"\n[real, full_matrices=False] U: {U.shape} | {U.stride()}")
print(f"[real, full_matrices=False] S: {S.shape} | {S.stride()}")
print(f"[real, full_matrices=False] V: {V.shape} | {V.stride()}")
```

BEFORE this diff, we have correct results (please confirm).

```
A: torch.Size([1, 0]) | (1, 1)

[real, full_matrices=True] U: torch.Size([1, 1]) | (1, 1)        # <-------- good?
[real, full_matrices=True] S: torch.Size([0]) | (1,)
[real, full_matrices=True] V: torch.Size([0, 0]) | (1, 1)

[real, full_matrices=False] U: torch.Size([1, 0]) | (1, 1)       # <-------- good?
[real, full_matrices=False] S: torch.Size([0]) | (1,)
[real, full_matrices=False] V: torch.Size([0, 0]) | (1, 1)
```

AFTER this diff, we have incorrect results (please confirm); in particular, see `U` when `full_matrices=False`:

```
A: torch.Size([1, 0]) | (1, 1)

[real, full_matrices=True] U: torch.Size([1, 1]) | (1, 1)
[real, full_matrices=True] S: torch.Size([0]) | (1,)
[real, full_matrices=True] V: torch.Size([0, 0]) | (1, 1)

[real, full_matrices=False] U: torch.Size([1, 1]) | (1, 1)       # <-------- OUCH?
[real, full_matrices=False] S: torch.Size([0]) | (1,)
[real, full_matrices=False] V: torch.Size([0, 0]) | (1, 1)
```

**Comment by avikchaudhuri** [comment]
Do I need to add a meta registration for the "external" `linalg_svd` op (not just the "internal" op `_linalg_svd`)? Or do you think it's something else?

**Comment by avikchaudhuri** [comment]
Hmm, I think I figured out what's off. `native_functions.yaml` declares `full_matrices=False` as the default:
```
- func: _linalg_svd(Tensor A, bool full_matrices=False, bool compute_uv=True, *, str? driver=None) -> (Tensor U, Tensor S, Tensor Vh)
```

Since we might be relying on that (even though it seems like the wrong default), I'm going to match that default in the meta registration.

**Comment by SherlockNoMad** [comment]
> Hmm, I think I figured out what's off. `native_functions.yaml` declares `full_matrices=False` as the default:
> 
> ```
> - func: _linalg_svd(Tensor A, bool full_matrices=False, bool compute_uv=True, *, str? driver=None) -> (Tensor U, Tensor S, Tensor Vh)
> ```
> 
> Since we might be relying on that (even though it seems like the wrong default), I'm going to match that default in the meta registration.

Yes, need to match the default value in native_function.yaml.

**Comment by avikchaudhuri** [comment]
OK, thanks. 

Still getting `xfail` failures. For some reason earlier I found unexpected successes in `test_aotdispatch` which are now errors (same as before), and vice versa in `test_proxy_tensor`. Might have been confused, so fixing and trying again...

**Pull request merged**
