### PR TITLE
Initialize operator versioning tracking files

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65518

Differential Revision: [D31135934](https://our.internmc.facebook.com/intern/diff/D31135934)

### CODE REVIEW

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31135934).

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31135934).

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31135934).

**Review by gmagogsfm — APPROVED** [review]
Looks good. Please fix lint errors though.

**Comment by mruberry** [comment]
@tugsbayasgalan is this PR still relevant with the most recent changes?

**Pull request closed without merging**
