### PR TITLE
Avoid guarding on zero-ness with meta tensors.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #94437
* #94436
* #94435
* #94431
* #94410
* #94408
* #94407
* #94404
* #94400
* __->__ #94399
* #94201
 
This removes one of the == 0 tests that occur when you construct a tensor with SymInts. Unfortunately there are more, so I can't test this.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Test?

**Comment by ezyang** [comment]
@albanD Can't easily test the E2E, because there are other guards on zero-ness that haven't been removed. I wanted to do it all in one go but the patch got too big, so I'm splitting it. Hope that's OK!

**Comment by albanD** [comment]
Sounds good to me.
This code is not touched much so it's unlikely to regress between now and when the full versions lands.

**Comment by voznesenskym** [comment]
What is wrong with guarding on zeroness?

**Comment by ezyang** [comment]
torch.empty(torch.nonzero(x).shape(0)) should work WITHOUT any user constraints, because clearly a shape should always be valid to construct another tensor like. However, if you guard on zero, you need a constraint that nonzero(x) returned a non-zero element tensor.

**Pull request closed without merging**
