### PR TITLE
ns for fx: initial support for int8 shadows fp32

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#60419**

Summary:

Adds support for NS for FX shadowed activations pass to handle int8
modules shadowing fp32 modules. The difficulty here is that in order
to insert the dtype cast, we need the qparams of the input.

For the current PR, we only handle the easy cases where the previous
node is either a `quantize_per_tensor` or an OSS quantized module.
A future PR can handle more complicated cases such as various functions.

Test Plan:

```
python test/test_quantization.py TestFXNumericSuiteCoreAPIs.test_int8_shadows_fp32_simple
```

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D29280050](https://our.internmc.facebook.com/intern/diff/D29280050)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Review by hx89 — COMMENTED** [review]
Thanks for the quick prototype! I'm thinking if it would make it easier if we do "int8 shadows fp32" during convert() or using similar flow as convert()? Since for "int8 shadows fp32" we don't really need a fully quantized model, we may start from prepared and calibrated fp32 model with observers holding the activation stats, and instead of converting fp32 module into int8 one, we can add a quantize op and int8 module as the shadow for fp32 module. It might be hard to explain in the comments, we can have a meeting to chat more about it.

**Comment by vkuzo** [comment]
> Thanks for the quick prototype! I'm thinking if it would make it easier if we do "int8 shadows fp32" during convert() or using similar flow as convert()? Since for "int8 shadows fp32" we don't really need a fully quantized model, we may start from prepared and calibrated fp32 model with observers holding the activation stats, and instead of converting fp32 module into int8 one, we can add a quantize op and int8 module as the shadow for fp32 module. It might be hard to explain in the comments, we can have a meeting to chat more about it.

It could work, but it would increase coupling between convert_fx and numerical suite, which is a downside.

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Comment by hx89** [comment]
> > Thanks for the quick prototype! I'm thinking if it would make it easier if we do "int8 shadows fp32" during convert() or using similar flow as convert()? Since for "int8 shadows fp32" we don't really need a fully quantized model, we may start from prepared and calibrated fp32 model with observers holding the activation stats, and instead of converting fp32 module into int8 one, we can add a quantize op and int8 module as the shadow for fp32 module. It might be hard to explain in the comments, we can have a meeting to chat more about it.
> 
> It could work, but it would increase coupling between convert_fx and numerical suite, which is a downside.

Yes that's one downside if do it inside convert_fx(), do you think if it has any upside? If it can make "int8 shadows fp32" much easier, maybe one options to avoid the coupling between convert_fx and numeric suite is to not modify convert_fx() but have a separate function that does "int8 shadows fp32" using similar flow to convert_fx()?

**Comment by vkuzo** [comment]
> If it can make "int8 shadows fp32" much easier, maybe one options to avoid the coupling between convert_fx and numeric suite is to not modify convert_fx() but have a separate function that does "int8 shadows fp32" using similar flow to convert_fx()?

makes sense.  From my estimations, just finishing the current implementation in this PR would be significantly less work than adding logic to quantize the model again.  Sorry, when I mentioned that "int8 shadows fp32 is difficult", I should have clarified that is doable, just will take some eng time.

**Comment by hx89** [comment]
> > If it can make "int8 shadows fp32" much easier, maybe one options to avoid the coupling between convert_fx and numeric suite is to not modify convert_fx() but have a separate function that does "int8 shadows fp32" using similar flow to convert_fx()?
> 
> makes sense. From my estimations, just finishing the current implementation in this PR would be significantly less work than adding logic to quantize the model again. Sorry, when I mentioned that "int8 shadows fp32 is difficult", I should have clarified that is doable, just will take some eng time.

Make sense, this PR is good to go.

**Review by hx89 — APPROVED** [review]

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29280050).

**Pull request closed without merging**
