### PR TITLE
update type() calling to not use unneeded device

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110163

Previous code path was doing an unnecessary cuda init as well as causing an unnecessary "device" to occur in the jit trace.

### CODE REVIEW

**Review by henryhu6 — APPROVED** [review]

**Comment by albanD** [comment]
Could you give some details on why you want this change?

**Comment by albanD** [comment]
> Previous code path was doing an unnecessary cuda init

The lazy init must be done if you're on cuda. But in this case it should just be a fast noop right? Since this function is called before every single cuda call, I hope it is fast when cuda is already initialized :) 

> as well as causing an unnecessary "device" to occur in the jit trace

Isn't the call to `self_.device();` still happening? Or you meant that `dispatch_to()` is doing another one?

**Comment by eellison** [comment]
The lazy init was being called in the case where only dtype change was specified, so if the tensor was already on cuda, we were calling lazy init again.

> Isn't the call to self_.device(); still happening? Or you meant that dispatch_to() is doing another one?

Sorry to clarify, there was an unnecessary device that appeared in the traced `to` call. See more context here: https://fb.workplace.com/groups/1405155842844877/posts/7481124551914612

```
def forward(self, x=None):
        h = x.type(self.dtype)
        return h
The graph it produces is:
def forward(self,
    x: Tensor) -> Tensor:
  _0 = torch.to(x, torch.device("cuda:0"), 5)
  return _0
```

now, we are omitting the device. not sure why this is needed, deferring to @henryhu6 but the changes here seemed simple enough so I submitted.

**Comment by henryhu6** [comment]
The torchscripted model could be loaded on cuda:0, or cuda:1, etc. Since this inserts a cuda:0 in the graph, model forward would crash due to device mismatch when trying to run on cuda:1.

**Comment by albanD** [comment]
> The lazy init was being called in the case where only dtype change was specified, so if the tensor was already on cuda, we were calling lazy init again.

Sure, but I do hope that calling lazy init again is almost free as we do it in many many places in the codebase :) 

> Sorry to clarify, there was an unnecessary device that appeared in the traced to call.

Ho ok, the problem is that the current device gets baked into the trace! Makes sense. Thanks!

**Review by albanD — APPROVED** [review]
SGTM

**Pull request closed without merging**
