### PR TITLE
[5/N][BE] Remove Replicated Tensor class

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #95949
* #95948
* __->__ #95947

Differential Revision: [D43877081](https://our.internmc.facebook.com/intern/diff/D43877081)

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
Nice! Do you check if internal/external are using this already?

**Comment by fduwjj** [comment]
@wanchaol no internal use case found for `ReplicatedTensor`. I am not sure about external.

**Comment by wanchaol** [comment]
sounds good, yeah let's ship it then ;)

**Comment by fduwjj** [comment]
#pytorchbot merge

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D43877081).

**Pull request closed without merging**
