### PR TITLE
don't use prims.unsqueeze in group_norm

### PR DESCRIPTION
**Pull request by ngimel**
inductor doesn't have prims.squeeze lowering, so this breaks it. Longer term, `squeeze` with multiple dimensions is not a prim, nvfuser implements it with a loop, inductor uses `_squeeze_multiple` helper which turns it into a loop. Prim should accept only a single dimension. 
cc @ezyang @mruberry @Lezcano @fdrocha @peterbell10, @IvanYashchuk

### CODE REVIEW

**Comment by IvanYashchuk** [comment]
> nvfuser implements it with a loop

That's true on PyTorch master, but the new `squeeze` in nvFuser takes multiple dimensions to squeeze at once.

> Prim should accept only a single dimension.

Prim should be general enough for those who can use this generality and it's simple to have a looped helper function for those who can't.

**Review by eellison — APPROVED** [review]

**Comment by ngimel** [comment]
Ok then it can remain as prim, but the general guidance is to use `torch.*` APIs in the decompositions, unless it can't be avoided.

**Comment by IvanYashchuk** [comment]
> Ok then it can remain as prim, but the general guidance is to use `torch.*` APIs in the decompositions, unless it can't be avoided.

previously it was "unless prim offers more functionality over torch"?

**Pull request closed without merging**
