### PR TITLE
`torch.dot` : CPU Complex Support

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference #33152

* Support torch.complex64 and torch.complex128 in `torch.dot`
* Updated the existing CPU to test to verify the support.

### CODE REVIEW

**Comment by kshitij12345** [comment]
@anjali411 Please review:)

Maybe @ngimel as well:)

**Comment by anjali411** [comment]
@kshitij12345 I already have a [PR](https://github.com/pytorch/pytorch/pull/42745) to add `torch.dot` for complex tensors on CPU and CUDA. Sorry, if I was unclear before, but the purpose of [this](https://github.com/pytorch/pytorch/issues/42747) issue is to add a new function `torch.vdot`.

**Comment by kshitij12345** [comment]
@anjali411 Oops. I didn't notice that PR. Sorry.

The issue of `torch.vdot` #42747  is clear. This was in reference to #33152 support for `torch.dot` on CPU.

Closing it in favour of #42745

**Comment by anjali411** [comment]
@kshitij12345 all good! If you are interested in working on other operators, you can work on any other op that doesn't say `WIP` and add me as a reviewer :D

**Pull request closed without merging**
