### PR TITLE
[Reland] Add sym_size/stride/numel/storage_offset to native_function.yaml (#91…

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Pull Request resolved: https://github.com/pytorch/pytorch/pull/91919
Approved by: https://github.com/ezyang

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
ping me if you need more review

**Comment by zhxchen17** [comment]
This diff regressed one pretty important model we have for export, and we did our best to fix forward today. Unfortunately, it seems we need more time to investigate the interaction between this diff and inference mode. Meanwhile to unblock our model enablement work, we may need to revert this diff.

cc @SherlockNoMad

**Pull request closed without merging**
