### PR TITLE
[export] support non-persistent buffers

### PR DESCRIPTION
**Pull request by suo**
Summary:
X-link: https://github.com/pytorch/executorch/pull/1817

Basic support for non-persistent buffers, which are buffers that do not show up in the state dict.

One weird twist is that most of our other systems (FX, aot_export, dynamo) have completely buggy handling of non-persistent buffers. I tried to go on a wild goose chase to fix them all, but it got to be too much. So I introduced some sad rewrite passes in `_export` make the final state dict correctly align with the original module's state dict.

This exposed some bugs/ambiguous handling of parameters/buffers in existing test code. For example, `TestSaveLoad.test_save_buffer` traced over a module that was not in the root module hierarchy and caused some weird behavior. I think we should error explicitly on use cases like this: https://github.com/pytorch/pytorch/issues/118410. For now I just rewrote the tests or skipped them.

As a side effect, this diff tightened up quite a few sloppy  behaviors around state dict handling:
- Tensor attributes were getting promoted to be buffers—bad!
- Tracing through a module not in the children of the root module would add its parameters/buffers to the state dict—bad!

This behavior is unlikely to show up in user code since the model would be totally broken, but did show up in a bunch of tests.

#buildmore

Test Plan:
unit tests
sandcastle

Differential Revision: D53340041

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by guangy10 — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Review by titaiwangms — APPROVED** [review]

**Comment by suo** [comment]
Looks like this broke TestLiftUnlift due to a merge race. I have disabled this test for now. Please don't revert this PR, I will fix forward.

**Comment by suo** [comment]
fix forward for TestLiftUnlift D53367522 landed through codev

**Comment by huydhn** [comment]
The `inductor/test_memory_planning.py::TestMemoryPlanning::test_abi_compatible` failure looks legit as it also happens in trunk.  And did you export D53367522 as I see the diff is committed?  It's still possible to export and land the PR now I think

**Comment by suo** [comment]
yep, I have disabled that one too and I am debugging it now

**Comment by suo** [comment]
fix: https://github.com/pytorch/pytorch/pull/119109

**Pull request closed without merging**
