### PR TITLE
[ONNX] Turn on batch norm related unittest

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105769

As title, add test for ops already supported.
Bump ORT in CI to 1.15.1 release version.

### CODE REVIEW

**Comment by BowenBao** [comment]
Ok, forgot about the ORT in CI still segfaults running `var_mean`.

**Review by titaiwangms — APPROVED** [review]

**Comment by titaiwangms** [comment]
> Ok, forgot about the ORT in CI still segfaults running `var_mean`.

Should we ban the ops leading to SegFault?

**Review by thiagocrepaldi — APPROVED** [review]
LGTM. batch norm tests are enabled because of the onnxscript bump, not because of the fake mode PR on this ghstack, right?

**Comment by BowenBao** [comment]
@thiagocrepaldi correct.

Yesterday updated CI ORT to 1.15.1. Yet segfault happens in onnx shape inference, so need to bump CI onnx to onnx-weekly, and may need onnx inliner.
https://github.com/pytorch/pytorch/pull/105618 does that, so this PR can wait for that.

**Review by thiagocrepaldi — COMMENTED** [review]
Have you seen this CI failure?

```bash
(...)
  File "onnx/test_fx_op_consistency.py", line 689 in <module>
FINISHED PRINTING LOG FILE of onnx/test_fx_op_consistency 1/2 (/var/lib/jenkins/workspace/test/test-reports/onnx-test_fx_op_consistency_p5m8cggy.log)

onnx/test_fx_op_consistency 1/2 failed! Received signal: SIGSEGV
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1681, in <module>
    main()
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1650, in main
    failure_messages = run_tests(
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1559, in run_tests
    raise RuntimeError(
RuntimeError: onnx/test_fx_op_consistency 1/2 failed! Received signal: SIGSEGV
```

**Comment by BowenBao** [comment]
> Have you seen this CI failure?

https://github.com/pytorch/pytorch/pull/105769#issuecomment-1648231439

**Pull request closed without merging**
