### PR TITLE
ppc64le: VSX Support for Inductor

### PR DESCRIPTION
**Pull request by Akashcodes732**
### Description

This PR extends the `VecISA` class to include support for VSX on the `ppc64le` architecture within the Inductor backend. This enhancement enables vectorization support, resulting in performance improvements when using `torch.compile()` on `ppc64le`.

### Fixes

- Resolved the `test_acosh_with_negative_large_input` test case in `test_cpu_repro.py` by implementing `acosh` for VSX.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by Akashcodes732** [comment]
Hi, @jgong5 can you please review ?

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
Looks like there are some failures

**Comment by Akashcodes732** [comment]
Hi @jansel , to resolve the failures we tried rebasing and it reduced the failures as well. The current failure is unrelated to the changed I have made. Could you please help ?

**Pull request closed without merging**
