### PR TITLE
Add Programmable Google Search

### PR DESCRIPTION
**Pull request by svekars**
- Adding the code for the programmable Google search
- Adding the CSS overrides.

cc @brycebortree @sekyondaMeta

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by albanD** [comment]
Can we make it search only within the docs page by default?
Also is it possible to make the links change the current tab instead of opening a new one by default?

**Review by albanD — APPROVED** [review]
Definitely better than the current one.
We can discuss the default page etc depending on the feedback we get!

**Pull request closed without merging**
