### PR TITLE
Forward fix torch package bug - dont depend on dynam in fsdp directly

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #116229

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

Differential Revision: [D52350752](https://our.internmc.facebook.com/intern/diff/D52350752)

### CODE REVIEW

**Comment by voznesenskym** [comment]
This is an insanely annoying issue where we cannot depend on dynamo in FSDP. I am going to apply allow_in_graph in torch patcher as part of https://github.com/pytorch/pytorch/pull/115410/files

**Review by janeyx99 — APPROVED** [review]
unblocking fbcode and cuz i trust

**Comment by voznesenskym** [comment]
@voznesenskym has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D52350752).

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
