### PR TITLE
vulkan: fix gcc build errors

### LINKED ISSUE #96617: Build errors in two Vulkan files
### 🐛 Describe the bug

Build problems occur in two files with GCC 12.2.0:
```
aten/src/ATen/native/vulkan/impl/Arithmetic.cpp:20:1: error: control reaches end of non-void function [-Werror=return-type]
aten/src/ATen/native/vulkan/impl/Registry.cpp:36:27: error: loop variable 'key' of type 'const std::string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char* const' [-Werror=range-loop-construct]
```

### Versions

I am trying to build v2.0.0-rc6 from the release/2.0 branch.

### PR DESCRIPTION
**Pull request by dvrogozh**
Fixes #96617

There was already an attempt to fix this build issue - see #96618. One commit is reused from this attempt (@zboszor) with adjustments to commit message. Another one differs and takes into account provided review feedback (@ezyang).

### CODE REVIEW

**Comment by dvrogozh** [comment]
@SS-JIA, @ezyang, @salilsdesai : can you, please, help review?

**Review by ezyang — APPROVED** [review]
okey dokey

**Pull request closed without merging**
