### PR TITLE
[ci] inline display_ec2 script

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74306
* __->__ #74355

This is purely for forward compatibility reasons. For actions and
workflows, we can pin them to a specific hash in our repo. Doing so
makes the migration smoother, because it means that to do CI we don't
need to reference the local checkout at all (and thus older PRs will not
break even if they are based on a commit that doesn't have the new
workflow files).

The only actually new file we reference is `display_ec2_info.sh`. So for
now, inline it. This incurs a little duplication but is worth it.

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
This change makes sense to me but what did you mean by

"For actions and workflows, we can pin them to a specific hash in our repo." Is this an alternative to this change? I'm curious about how this works.

**Comment by janeyx99** [comment]
> This change makes sense to me but what did you mean by
> 
> "For actions and workflows, we can pin them to a specific hash in our repo." Is this an alternative to this change? I'm curious about how this works.

**Comment by suo** [comment]
I mean that when I commit the new workflows in https://github.com/pytorch/pytorch/pull/74306, I will make them refer to a specific version of the workflows on master, like:
```
- name: foo
  uses: pytorch/pytorch/.github/workflows/_foo.yml@master
```
That way, even PRs based against an old master will still be able to run the workflows, since GHA will download the workflow definitions from master instead of looking in the local checkout. 

But one blocker to this happening is that these workflows can't refer to any *scripts* in the local checkout, since we can't do the same version pinning trick with regular files. Luckily, the only new file I added was `display_ec2_info.sh`, so it's easy to get rid of. Thus this PR.

**Comment by janeyx99** [comment]
Ah, so then I imagine in the future when we want to add a file to be run, there would have to be some period where the file gets introduced to the repo and then later we can add the reference.

**Comment by suo** [comment]
Yeah, to be clear this is true in general today. I'm just being extra careful because https://github.com/pytorch/pytorch/issues/74249

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
