### PR TITLE
[quant][better-engineering][bc-breaking] Removed quant_min/quant_max from fake_quant modules

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #76674

Summary:
FakeQuantize class has quant_min/quant_max and activation_post_process
attributes, the latter of which already includes quant_min/max. As such,
we can remove quant_min/quant_max from FakeQuantize and use
FakeQuantize.activation_post_process.quant_m* directly.

Test plan:
```
python test/test_quantization.py
```

Differential Revision: [D36071417](https://our.internmc.facebook.com/intern/diff/D36071417)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36071417).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36071417).

**Comment by dzdang** [comment]
@vkuzo do we want to keep the `quant_min/max` in `FakeQuantize` for a few releases for backwards compatibility? currently, i've removed those attributes

**Comment by vkuzo** [comment]
> @vkuzo do we want to keep the `quant_min/max` in `FakeQuantize` for a few releases for backwards compatibility? currently, i've removed those attributes

that's a good point, this module is also used in Eager mode quantization which is in OSS beta.  Perhaps we can keep them around for one more release, and delete afterwards?

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36071417).

**Comment by dzdang** [comment]
> > @vkuzo do we want to keep the `quant_min/max` in `FakeQuantize` for a few releases for backwards compatibility? currently, i've removed those attributes
> 
> that's a good point, this module is also used in Eager mode quantization which is in OSS beta. Perhaps we can keep them around for one more release, and delete afterwards?

just added the `quant_min/max` back in for BC. it should be ready for review now @vkuzo

**Review by vkuzo — APPROVED** [review]

**Pull request closed without merging**
