### PR TITLE
Add 2nd shard to ROCm trunk workflow for core distributed UTs

### PR DESCRIPTION
**Pull request by jithunnair-amd**
cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
https://github.com/pytorch/pytorch/actions/runs/8245449318/job/22552622950 ran distributed tests for ~3hr, while the default job https://github.com/pytorch/pytorch/actions/runs/8245449318/job/22552622659 ran for ~1hr15m

**Comment by jithunnair-amd** [comment]
After removing `test_distributed_spawn` from the list of distributed tests for trunk on ROCm, https://github.com/pytorch/pytorch/actions/runs/8791197768/job/24127336540 ran distributed tests for 49m, while the default job https://github.com/pytorch/pytorch/actions/runs/8791197768/job/24127336412 ran for ~1hr25m

**Comment by jithunnair-amd** [comment]
Will merge after CI capacity has been increased for ROCm

**Comment by jithunnair-amd** [comment]
Added 30 more CI nodes for ROCm CI, so this PR should be ready to merge now. Resolved conflicts due to ROCm6.1 CI upgrade and waiting for this round of CI to give a clean signal

**Review by ezyang — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
From https://hud.pytorch.org/pr/121716:
O[ linux-focal-rocm6.1-py3.8 / test (distributed, 1, 1, linux.rocm.gpu)](https://github.com/pytorch/pytorch/actions/runs/9102539339/job/25025246409)
    Queued: 0.0s, Duration: **28.8m**, [Test insights](https://hud.pytorch.org/test/insights?jobName=linux-focal-rocm6.1-py3.8%20%2F%20test%20(distributed%2C%201%2C%201%2C%20linux.rocm.gpu)&workflowId=9102539339&jobId=25025246409), Show artifacts, [Raw logs](https://ossci-raw-job-status.s3.amazonaws.com/log/25025246409)

**Pull request closed without merging**
