### PR TITLE
[DDP] Profile search_unused_parameters

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57376 [DDP] Profile search_unused_parameters**

Having this in profiler/trace outputs will be useful when
investigating performance overhead of find_unused_parameters for certain
workloads, to determine whether it is a bottleneck or not.

Differential Revision: [D28126233](https://our.internmc.facebook.com/intern/diff/D28126233/)

### CODE REVIEW

**Review by zhaojuanmao — APPROVED** [review]
could we get some numbers by running QPS benchmark?

**Comment by rohan-varma** [comment]
> could we get some numbers by running QPS benchmark?

Sure, will add them once i've run the benchmarks.

**Comment by rohan-varma** [comment]
@zhaojuanmao Posted some initial benchmark numbers on the internal diff.

**Comment by rohan-varma** [comment]
filed issue for flaky test - https://github.com/pytorch/pytorch/issues/57469

**Pull request closed without merging**
