### PR TITLE
[dynamo] check buffers when checking accuracy

### PR DESCRIPTION
**Pull request by williamwen42**
Tested by running `python benchmarks/dynamo/torchbench.py --accuracy --float32 -dcuda --output=inductor_torchbench_float32_training_cuda_performance.csv --training --inductor --no-skip --dashboard --only mobilenet_v2 --cold_start_latency` and breakpointing after the changes to inspect buffers.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Comment by williamwen42** [comment]
@anijain2305 more changes than expected were required to pass tests.

**Review by anijain2305 — APPROVED** [review]

**Pull request closed without merging**
