### PR TITLE
Quick fix to unblock buck-build-test

### PR DESCRIPTION
**Pull request by huydhn**
Fix https://github.com/pytorch/pytorch/runs/7397748898. There might be a better way to avoid this type of issue in the future.

### CODE REVIEW

**Comment by huydhn** [comment]
This reveals a weird recursive bug (or feature?) in `//tools/build_defs:glob_defs.bzl:glob` current implementation https://github.com/pytorch/pytorch/runs/7403149141. That can be addressed separately though.

**Comment by kit1980** [comment]
this will probably break internal when synced back.

**Comment by huydhn** [comment]
> this will probably break internal when synced back.

Yup. That's a possibility. This PR is almost the same as reverting https://github.com/pytorch/pytorch/pull/81441. So reverting is definitely a clearer approach here.

**Comment by kit1980** [comment]
Latest commit would be fine, but we're trying to revert the internal diff instead.

**Pull request closed without merging**
