### PR TITLE
Benchmarks for various fusers

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67622

Differential Revision: [D32171063](https://our.internmc.facebook.com/intern/diff/D32171063)

### CODE REVIEW

**Comment by bertmaher** [comment]
I created a small benchmark suite for all the CUDA fusers so that we have a quantitative basis for narrowing the field.  Some results are here (although this isn't perfectly up to date): https://gist.github.com/bertmaher/71612a3156a46274e8f6792ad4678e32

We'd probably also want to run these numbers with some different datatypes (particularly half, but maybe also some int dtypes to make sure no pathologies are introduced).  And possibly also add some benchmarks for concat/chunk (since those are important for some usecases, like the oh-so-important fastrnns lol) and reductions (which legacy and NNC don't handle at all).

While NNC is really the only game in town for CPU fusion, I'm of the opinion that we should switch over to nvFuser for CUDA, since it's better staffed and more feature-complete.  There are a few performance pathologies right now but @jjsjann123 mentions those are fixed in a branch.  So if we can get those fixed I'm happy to support a cut-over.

**Comment by bertmaher** [comment]
cc @jansel @csarofeen @ngimel for input on the nvFuser-as-default; this benchmark suite isn't gating by any means -- I think small perf variances are inevitable -- but is a pretty convenient/efficient way to gather systematic perf data.

**Comment by bertmaher** [comment]
@bertmaher has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32171063).

**Review by eellison — APPROVED** [review]
😍 😍 😍

**Review by navahgar — APPROVED** [review]

**Review by jjsjann123 — APPROVED** [review]
:tada:

**Pull request closed without merging**
