### PR TITLE
[Quant] Add fused linear-tanh op for onednn backend

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #89188
* #88923
* __->__ #88879
* #88668

**Summary**
Post op fusion can reduce data movement overhead and improve inference performance. This PR adds fused `linear-tanh` op for `onednn` backend, which will be used for int8 inference with `onednn` backend. Linear-tanh is found in models like CGAN.
Cannot call this op with other quantization backends otherwise an error is thrown.

**Test Plan**
python test_quantization.py TestQuantizedLinear

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @leslie-fang-intel @VitalyFedyunin @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by jerryzh168 — APPROVED** [review]
lg, please add "Summary" and "Test Plan" as well

**Comment by kimishpatel** [comment]
what is the motivation behind tanh linear fusion?

**Comment by Xia-Weiwen** [comment]
> what is the motivation behind tanh linear fusion?

Fusing activations with root ops can reduce overhead and improve inference performance. Linear-tanh is found in models like CGAN.

**Review by jerryzh168 — APPROVED** [review]

**Pull request closed without merging**
