### PR TITLE
[ONNX] Remove unused patching methods

### LINKED ISSUE #76254: [ONNX] Remove the function _graph_constant in utils if not needed
### 🚀 The feature, motivation and pitch

Four years ago in https://github.com/pytorch/pytorch/blob/ea8a0184b76088c477c7cef4fe36d683d57fd880/torch/onnx/utils.py#L1206: We might not need this anymore, since most scalars now show up as tensors

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by justinchuby**
### Description

Remove unused patching methods:

- `torch._C.Graph.constant`
- unpatch `torch._C.Node.__getitem__` and move the helper function to `symbolic_helper`

Add typing annotations

### Issue

Fixes #76254
Dependent on #81953, #82628

### Testing

Unit tested

### CODE REVIEW

**Comment by AllenTiTaiWang** [comment]
I think the changes are good, but this is failing a lot of tests. Please make sure it isn't about the PR.

**Comment by justinchuby** [comment]
Thanks - fixing errors

**Comment by justinchuby** [comment]
Updated. `_type_utils` is dependent on #81953 which needs reviews

**Comment by BowenBao** [comment]
> Updated. `_type_utils` is dependent on #81953 which needs reviews

ghstack would come in handy. It would be nicer if you could split the annotation part from the patching change.

**Comment by justinchuby** [comment]
> > Updated. `_type_utils` is dependent on #81953 which needs reviews
> 
> ghstack would come in handy. It would be nicer if you could split the annotation part from the patching change.

Thanks, I will use ghstack in the next batch of PRs.

**Comment by AllenTiTaiWang** [comment]
Seems there are complaints from quantization UTs.

**Comment by AllenTiTaiWang** [comment]
> Seems there are complaints from quantization UTs.

Could you also update why you had and how you fix those failed checks after you manage to fix them? I am curious.

**Comment by justinchuby** [comment]
Closed in favor of #83006

**Pull request closed without merging**
