### PR TITLE
[ROCm] libtorch nightly now correctly uses rocm runners

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes nightly rocm libtorch builds.

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@jeffdaily These are all nightly builds, right? So they shouldn't add too much to the ROCm CI workload, but just to avoid bloating the workload if possible, I was wondering if we should keep the wheel builds on linux runners like we had before, and only transition the libtorch workloads to ROCm runners?

**Comment by jeffdaily** [comment]
> @jeffdaily These are all nightly builds, right? So they shouldn't add too much to the ROCm CI workload, but just to avoid bloating the workload if possible, I was wondering if we should keep the wheel builds on linux runners like we had before, and only transition the libtorch workloads to ROCm runners?

Builds are still done on linux GHA runners.  Just the tests are done on ROCm runners, but it's just a smoke test that you can import torch without crashing.

**Review by seemethere — APPROVED** [review]

**Comment by seemethere** [comment]
Looks like these are still failing for the `without-deps` builds. Should we just disable these for ROCM?

**Comment by jeffdaily** [comment]
> Looks like these are still failing for the `without-deps` builds. Should we just disable these for ROCM?

Even though we're now correctly using rocm runners, the deps are not located in /opt/rocm.  The log suggests using rpath but can we set LD_LIBRARY_PATH=/opt/rocm for the `without-deps` tests?  Is that a viable solution?

**Comment by seemethere** [comment]
> > Looks like these are still failing for the `without-deps` builds. Should we just disable these for ROCM?
> 
> Even though we're now correctly using rocm runners, the deps are not located in /opt/rocm. The log suggests using rpath but can we set LD_LIBRARY_PATH=/opt/rocm for the `without-deps` tests? Is that a viable solution?

I think that should be fine, @malfet might also have an opinion on this as well

**Comment by jeffdaily** [comment]
> > > Looks like these are still failing for the `without-deps` builds. Should we just disable these for ROCM?
> > 
> > 
> > Even though we're now correctly using rocm runners, the deps are not located in /opt/rocm. The log suggests using rpath but can we set LD_LIBRARY_PATH=/opt/rocm for the `without-deps` tests? Is that a viable solution?
> 
> I think that should be fine, @malfet might also have an opinion on this as well

It didn't work anyhow.  I have pushed a commit to skip without-deps for libtorch on rocm.

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
You might need to rebase this PR, looks like your upload/download-artifacts needs to be updated

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
