### PR TITLE
Remove DBR quantization from the codebase

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#83642 Remove DBR quantization from the codebase**

Summary:

DBR quantization is a no-go for now because it does not align well with
PyTorch 2.0 plans and we do not want to build yet another tracing system.

Deleting it from the codebase for now since there are no plans to develop
this in the near future. We can bring it back at a later time if necessary.

Test plan:

CI

Differential Revision: [D38839556](https://our.internmc.facebook.com/intern/diff/D38839556)

### CODE REVIEW

**Comment by vkuzo** [comment]
cc @albanD  @seemethere , the PR size linter is asking me to talk to you since this is >2k LOC. This PR is a deprecation of a self-contained prototype which has not been talked about externally and is not used anywhere, is it ok to have an exception to the <=2k LOC rule here, or does this need to be broken up into smaller chunks?

**Comment by albanD** [comment]
Hey!
Is this used anywhere internally? Is there any risk related to merging this?

**Comment by vkuzo** [comment]
Got it, thanks, it should be very low risk since no one is using this.  The PR does need Meta-only changes due to some fbcode build targets.  I just wanted to make sure OSS CI is green before doing the Meta-only part.

I was actually planning to land this from Meta side (due to Meta changes), is it ok to land with the LOC lint broken?

**Comment by vkuzo** [comment]
nm, I guess if it's ok to land from PyTorch with `-f`, it should be ok to do the same from Phabricator.  Thanks!

**Comment by albanD** [comment]
It is ok to bypass that signal when you land internally the diff yes.

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38839556).

**Review by andrewor14 — APPROVED** [review]

**Review by jerryzh168 — APPROVED** [review]

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38839556).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38839556).

**Pull request closed without merging**
