### PR TITLE
Move log_sigmoid to Aten(CPU)

### LINKED ISSUE #24724: Migrate `log_sigmoid_backward` from the TH to Aten (CPU)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by XiaobingSuper**
@VitalyFedyunin, This PR is about port LogSigmoid activation to Aten:
Test script:
```
import torch
import torch.nn as nn
import time

torch.manual_seed(0)

def _time():
    return time.time()

device = "cpu"
m = nn.LogSigmoid()
#warm up
for n in [1, 10, 100, 1000]:
    input = torch.randn(128, n, requires_grad=True, device=device)
    grad_output = torch.randn(128, n, device=device)
    for i in range(1000):
        output = m(input)
        output.backward(grad_output)

for n in [1, 10, 100, 1000]:
    input = torch.randn(128, n, requires_grad=True, device=device)
    grad_output = torch.randn(128, n, device=device)
    fwd_t = 0
    bwd_t = 0
    for i in range(10000):
        t1 = _time()
        output = m(input)
        t2 = _time()
        output.backward(grad_output)
        t3 = _time()
        fwd_t = fwd_t + (t2 -t1)
        bwd_t = bwd_t + (t3 - t2)
    fwd_avg = fwd_t / 10000 * 1000
    bwd_avg = bwd_t / 10000 * 1000
    print("input size(128, %d) forward time is %.2f (ms); backwad avg time is %.2f (ms)."
          % (n, fwd_avg, bwd_avg))
```
**Before:**
```
input size(128, 1) forward time is 0.02 (ms); backwad avg time is 0.02 (ms).
input size(128, 10) forward time is 0.10 (ms); backwad avg time is 0.03 (ms).
input size(128, 100) forward time is 0.90 (ms); backwad avg time is 0.09 (ms).
input size(128, 1000) forward time is 9.04 (ms); backwad avg time is 0.87 (ms).
```
**After:**
```
input size(128, 1) forward time is 0.02 (ms); backwad avg time is 0.02 (ms).
input size(128, 10) forward time is 0.02 (ms); backwad avg time is 0.02 (ms).
input size(128, 100) forward time is 0.04 (ms); backwad avg time is 0.03 (ms).
input size(128, 1000) forward time is 0.28 (ms); backwad avg time is 0.07 (ms).
```
**OMP_NUM_THREADS=1:**
```
Before:
input size(128, 1) forward time is 0.02 (ms); backwad avg time is 0.02 (ms).
input size(128, 10) forward time is 0.10 (ms); backwad avg time is 0.03 (ms).
input size(128, 100) forward time is 0.88 (ms); backwad avg time is 0.10 (ms).
input size(128, 1000) forward time is 8.72 (ms); backwad avg time is 0.81 (ms).
After:
input size(128, 1) forward time is 0.01 (ms); backwad avg time is 0.02 (ms).
input size(128, 10) forward time is 0.02 (ms); backwad avg time is 0.02 (ms).
input size(128, 100) forward time is 0.07 (ms); backwad avg time is 0.03 (ms).
input size(128, 1000) forward time is 0.63 (ms); backwad avg time is 0.15 (ms).
```

Fix #24724, #24725.

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
#24724 Migrate log_sigmoid_backward from the TH to Aten (CPU)
#24725 Migrate log_sigmoid_forward from the TH to Aten (CPU)

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 01b6f33:
* **1/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=01b6f3301720abdc8bdbfa2367cd90d5e5d448f2).

### 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3946657) pytorch_linux_xenial_py3_clang5_mobile_build (1/1)
**Step:** "Build" ([details](https://dr.pytorch.org/build-details.html?build_id=73981056))
```
Dec 13 08:12:32 /var/lib/jenkins/workspace/aten/src/ATen/native/Activation.cpp:482:39: note: in expansion of macro 'LEGACY_CONTIGUOUS_MEMORY_FORMAT' 
Dec 13 08:12:32    auto buffer = at::zeros_like(input, LEGACY_CONTIGUOUS_MEMORY_FORMAT); 
Dec 13 08:12:32                                        ^ 
Dec 13 08:12:32 /var/lib/jenkins/workspace/c10/core/MemoryFormat.h:34:36: note: declared here 
Dec 13 08:12:32  C10_DEPRECATED inline MemoryFormat get_contiguous_memory_format() { 
Dec 13 08:12:32                                     ^ 
Dec 13 08:12:32 /var/lib/jenkins/workspace/aten/src/ATen/native/Activation.cpp:483:64: error: no match for call to '(at::native::log_sigmoid_cpu_stub) (const c10::DeviceType&, at::Tensor&, at::Tensor&, at::Tensor)' 
Dec 13 08:12:32    log_sigmoid_cpu_stub(kCPU, result, buffer, input.contiguous()); 
Dec 13 08:12:32                                                                 ^ 
Dec 13 08:12:32 /var/lib/jenkins/workspace/aten/src/ATen/native/Activation.cpp: In function 'std::tuple<at::Tensor&, at::Tensor&> at::native::log_sigmoid_forward_out_cpu(at::Tensor&, at::Tensor&, const at::Tensor&)': 
Dec 13 08:12:32 /var/lib/jenkins/workspace/aten/src/ATen/native/Activation.cpp:488:51: error: no match for call to '(at::native::log_sigmoid_cpu_stub) (const c10::DeviceType&, at::Tensor&, at::Tensor&, const at::Tensor&)' 
Dec 13 08:12:32    log_sigmoid_cpu_stub(kCPU, result, buffer, input); 
Dec 13 08:12:32                                                    ^ 
Dec 13 08:12:32 caffe2/CMakeFiles/torch_cpu.dir/build.make:1912: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/Activation.cpp.o' failed 
Dec 13 08:12:32 make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/Activation.cpp.o] Error 1 
Dec 13 08:12:32 make[2]: *** Waiting for unfinished jobs.... 
Dec 13 08:12:33 In file included from /var/lib/jenkins/workspace/build_mobile/aten/src/ATen/core/TensorBody.h:5:0, 
Dec 13 08:12:33                  from /var/lib/jenkins/workspace/aten/src/ATen/Tensor.h:11, 
Dec 13 08:12:33                  from /var/lib/jenkins/workspace/aten/src/ATen/Context.h:4, 
Dec 13 08:12:33                  from /var/lib/jenkins/workspace/aten/src/ATen/ATen.h:5, 
Dec 13 08:12:33                  from /var/lib/jenkins/workspace/aten/src/ATen/native/AdaptiveAveragePooling3d.cpp:1: 
```


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 82ff608:
* **2/2** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=82ff6081fe711b2ba9497c3c14565a9d551f2431).

### :detective: 2 new failures recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4014721) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test (1/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=77310179) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=77310179))
<details>
<summary>
<code>Dec 19 05:29:13 RuntimeError: test_jit_simple failed!</code>
</summary>

```
Dec 19 05:29:13 Ran 2307 tests in 84.526s 
Dec 19 05:29:13  
Dec 19 05:29:13 FAILED (failures=1, errors=1, skipped=77, expected failures=1) 
Dec 19 05:29:13  
Dec 19 05:29:13 Generating XML reports... 
Dec 19 05:29:13 Traceback (most recent call last): 
Dec 19 05:29:13   File "test/run_test.py", line 456, in <module> 
Dec 19 05:29:13     main() 
Dec 19 05:29:13   File "test/run_test.py", line 449, in main 
Dec 19 05:29:13     raise RuntimeError(message) 
Dec 19 05:29:13 RuntimeError: test_jit_simple failed! 
Dec 19 05:29:13 + cleanup 
Dec 19 05:29:13 + retcode=1 
Dec 19 05:29:13 + set +x 
Dec 19 05:29:13 =================== sccache compilation log =================== 
Dec 19 05:29:13 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 19 05:29:13 Compile requests                56 
Dec 19 05:29:13 Compile requests executed        0 
Dec 19 05:29:13 Cache hits                       0 
Dec 19 05:29:13 Cache misses                     0 
Dec 19 05:29:13 Cache timeouts                   0 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4014723) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_legacy_test (2/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=77312590) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=77312590))
<details>
<summary>
<code>Dec 19 05:30:16 RuntimeError: test_jit_legacy failed!</code>
</summary>

```
Dec 19 05:30:15 Ran 2307 tests in 144.964s 
Dec 19 05:30:15  
Dec 19 05:30:15 FAILED (failures=1, errors=1, skipped=59, expected failures=1) 
Dec 19 05:30:15  
Dec 19 05:30:15 Generating XML reports... 
Dec 19 05:30:16 Traceback (most recent call last): 
Dec 19 05:30:16   File "test/run_test.py", line 456, in <module> 
Dec 19 05:30:16     main() 
Dec 19 05:30:16   File "test/run_test.py", line 449, in main 
Dec 19 05:30:16     raise RuntimeError(message) 
Dec 19 05:30:16 RuntimeError: test_jit_legacy failed! 
Dec 19 05:30:16 + cleanup 
Dec 19 05:30:16 + retcode=1 
Dec 19 05:30:16 + set +x 
Dec 19 05:30:16 =================== sccache compilation log =================== 
Dec 19 05:30:16 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 19 05:30:16 Compile requests               304 
Dec 19 05:30:16 Compile requests executed        0 
Dec 19 05:30:16 Cache hits                       0 
Dec 19 05:30:16 Cache misses                     0 
Dec 19 05:30:16 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
Hi @XiaobingSuper I will be out for two weeks, please add other reviewers like @gchanan @zou3519 while I'm away. Plus I will try to review as much as possible before I leave.

**Comment by VitalyFedyunin** [comment]
You can also loop @ezyang into reviews for next couple weeks.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by XiaobingSuper** [comment]
Just rebased.

**Comment by XiaobingSuper** [comment]
@ezyang, just rebase to solve the conflicts.

**Comment by ShawnZhong** [comment]
Hi @XiaobingSuper, I am trying to implement the CUDA part of `log_sigmoid`, and wonder if the `buffer` is necessary. It seems to me that log_sigmoid is the only activation function that requires it.

**Comment by XiaobingSuper** [comment]
@ShawnZhong  , using the `buffer` got from forward step can reduce the backward's compute time(see https://github.com/pytorch/pytorch/blob/6d9a9e379d01ab66365d8e98dc3566fab9465a0d/aten/src/THNN/generic/LogSigmoid.c), for cuda case, I think it is also useful for the backward performance.

**Pull request closed without merging**
