### PR TITLE
Add option to record C++ backtraces in _record_memory_history

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #86145
* #86139

I used this to debug https://github.com/pytorch/pytorch/issues/86136 so it is useful. The implementation is not so fast so it is not enabled by default.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]

**Review by zdevito — APPROVED** [review]
This is useful, but the cost of Python (2 us) vs C++ stack tracing (however long it takes to to string format  and gather a stack trace) is not on the same order of magnitude. It is done on _every_ allocation so it happens a lot. This can lead people to think that enabling this for long running jobs is more expensive than it is (Python is pretty cheap), or for someone to think this is cheap but severely slow down the job they are looking at. 

Maybe either warn that C++ stack traces are slow, or change the api to enable them to be more clear `_enable_expensive_memory_history`. There is probably a cheaper approach that walks the C++ stack and saves the addresses but does not formatting that can enable fast gathering of C++ stack traces in the future.

**Comment by ezyang** [comment]
I made it guarded behind a scary looking kwarg, and also added a docblock for the function!

**Pull request closed without merging**
