### PR TITLE
Split RRef class into abstract RRef and RRefBase

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #31681 Apply clang-format to csrc/distributed/rpc
* **#28942 Split RRef class into abstract RRef and RRefBase**

The new abstract RRef class contains only user-facing RRef APIs.
It will be later moved to a common folder so that it can be shared
by jit and distributed packages to provide TorchScript support.

Differential Revision: [D18240590](https://our.internmc.facebook.com/intern/diff/D18240590)

### CODE REVIEW

**Comment by mrshenli** [comment]
I still need to add `to_here()` to the abstract `RRef` class, but hopefully this is sufficient to unblock @wanchaol.

**Review by zhaojuanmao — APPROVED** [review]

**Comment by mrshenli** [comment]
@wanchaol could you please confirm on whether JIT can support abstract types? I will land this if yes or if it can be made so. If JIT cannot and does not plan to support abstract types, we probably should abandon this.

**Comment by pritamdamania87** [comment]
Is this a duplicate of https://github.com/pytorch/pytorch/pull/30137?

**Comment by wanchaol** [comment]
> Is this a duplicate of #30137?

I was just pulling in the changes of this PR as part of https://github.com/pytorch/pytorch/pull/30137 to test if it works. I think this works as expected and abstract types are fine by the use of IValue. 

@mrshenli can you probably rebase and merge this? We could call the abstract type `RRefInterface` and call `RRefBase` still `RRef` per @pritamdamania comments.

**Comment by mrshenli** [comment]
@wanchaol yes, will merge next Monday.

**Pull request closed without merging**
