### PR TITLE
[Needs test] Removing exception from the default_collate

### PR DESCRIPTION
**Pull request by perone**
The `default_collate()` function is nowadays arbitrary on which types it will be able to aggregate in a batch, handling special cases such as strings differently than other object classes for instance.
This PR will add more flexibility to the `default_collate()` function by allowing it to return a list (just like when it finds a string object) when it cannot stack using the known data types. This is very useful for many tasks when we want to propagate complex information about the samples (such as in medical imaging).
I don't see a strong reason to keep this exception here, it will just add a restriction on the batching system.

### CODE REVIEW

**Comment by ezyang** [comment]
This gonna need a test.

@pytorchbot test this please

**Comment by zou3519** [comment]
@perone the exception is originally there in case users attempt to batch data that they expect to be tensors but isn't actually tensor data. If we remove the exception I'm worried that the usability would go down a little, but we'd definitely gain more flexibility.

Is your use case handled by providing your own `collate_fn` and passing it into DataLoader or do you think that this flexibility is important for many users?

**Comment by perone** [comment]
Thanks for taking a look at that @zou3519. I understand the problem, however, I would say that in many applications this can be useful in long-term, because it will allow us to propagate complex structured objects that aren't easily wrapped in a Tensor.
I can accomplish the same using a custom `collate_fn`, however, in my case, I'm trying to write a user-facing API, which will then force users to instantiate DataLoader with this custom `collate_fn` or as an alternative, to use a custom `DataLoader` where I already have my default `collate_fn` defined, so neither options are elegant.
There is also another minor issue, the `default_collate` is using nowadays a global `_use_shared_memory` variable that would force you to add reference to it when replicating it outside of the module or setting manually, which is also not very elegant (this makes me think if `default_collate` shouldn't be a custom class object that is initialized with context).

Apart from that, the `default_collate` that we have today is arbitrarily selective: it allows you to have not only tensors but also strings. On the other side, I understand your concern about usability, however, if the user receives a batch that isn't a tensor, it would raise another exception later when feeding to the model, so this isn't a problem that will silently pass. My only concern is: you have more than one worker and you start passing complex objects that wouldn't allow shared memory, making copies very inefficient. This is indeed a usability issue. 

As you mentioned, it would allow flexibility but it would hurt a little the usability, but in my opinion, the long-term gains would be worth the change. What do you think ? (Sorry for the long comment).

**Comment by vadimkantorov** [comment]
Preserving a list when the batch can't be converted to a tensor is useful to, say, return a list of ground truth boxes without having to keep packing logic in the data loader.

Previously discussed in: https://github.com/pytorch/pytorch/issues/1512, my current workaround is `torch.utils.data.dataloader.default_collate = (lambda default_collate = torch.utils.data.dataloader.default_collate: lambda batch: batch if all(map(torch.is_tensor, batch)) and any([tensor.size() != batch[0].size() for tensor in batch]) else default_collate(batch))()`, and it's not elegant at all.

**Pull request closed without merging**
