### PR TITLE
[jit Python None should have its type inferred as NoneType

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #26666 [jit] module dedupe
* #27399 [jit] kill _parameter_list
* **#26665 [jit Python None should have its type inferred as NoneType**

This is actually useful. For example: in batchnorm.py, all the tracked
stats are either `nn.Parameter` or `None`. We should register them as
params if they are set, or attributes with type NoneType if they are
not.

Differential Revision: [D17551197](https://our.internmc.facebook.com/intern/diff/D17551197)

### CODE REVIEW

**Review by resistor — CHANGES_REQUESTED** [review]
Change LGTM, but testcase plz.

**Comment by eellison** [comment]
I think this might have a bad interaction with the `is None` check partial compilation

**Comment by suo** [comment]
> I think this might have a bad interaction with the is None check partial compilation

Can you elaborate?

**Comment by eellison** [comment]
> > I think this might have a bad interaction with the is None check partial compilation
> 
> Can you elaborate?

Anytime there's a `None` attribute you can reasonably assume this is an Optional attribute. Bc of the partial compilation of if statements with `is None` checks, the optional behavior will get compiled away here if we infer None. This is valid for constants, but i'm not sure about generally assuming this to be true.

**Review by zdevito — APPROVED** [review]

**Pull request closed without merging**
