### PR TITLE
[PyTorch] Optimize TupleType::annotation_str_impl

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #96498
* __->__ #96497

stringstream is expensive to create, we used stringstream instead of ostringstream, and we can easily specialize the empty tuple. Also, anybody compiling with C++20 support can move out of the stringstream and it shouldn't hurt people without C++20 support to do so. I would consider specializing the 1-element case as well but I don't have evidence that that's necessary right now.

Differential Revision: [D43882402](https://our.internmc.facebook.com/intern/diff/D43882402/)

### CODE REVIEW

**Comment by swolchok** [comment]
this was already approved once as #96215 FWIW

**Review by Skylion007 — APPROVED** [review]
Instead of trying to improve the speed of stringstream, wouldn't it be better to convert the code over to use libfmt https://github.com/fmtlib/fmt which is faster, more succinct etc? It's already a PyTorch dependency and supports constexpr etc strings when possible etc. Specifically, fmt::join is very fast and very efficient https://fmt.dev/latest/api.html#_CPPv4I0EN3fmt4joinE9join_viewIN6detail10iterator_tI5RangeEEN6detail10sentinel_tI5RangeEEERR5Range11string_view

**Comment by swolchok** [comment]
didn't know we had fmtlib; I'll take a look with join

**Comment by swolchok** [comment]
> It's already a PyTorch dependency

Are sure? I don't see any fmt/foo.h includes in the public repo

**Comment by swolchok** [comment]
I'm also unclear on how much join() can help us here -- we have to materialize annotation_str for each subelement right now.

**Comment by Skylion007** [comment]
> > It's already a PyTorch dependency
> 
> Are sure? I don't see any fmt/foo.h includes in the public repo

We have it in third_party/fmt. Good point about join(), I suppose since you would need to define custom iterators with std::for_each etc.

**Pull request closed without merging**
