### PR TITLE
[ONNX] Update merge rules and persons of interest

### PR DESCRIPTION
**Pull request by BowenBao**

### CODE REVIEW

**Comment by BowenBao** [comment]
cc @malfet @abock

**Review by malfet — APPROVED** [review]

**Comment by b0noI** [comment]
Before merging this in, I wanted to outline several things:
* each module from this file should be consistent with the page (person of interest), so please update it as well. Keep in mind that on POI page we should not be removing people, just making them as "emeritus"
* starting [last meeting of the PyTorch core maintainers](https://dev-discuss.pytorch.org/t/first-pytorch-quarterly-maintainers-meeting-minutes-meeting-date-july-22-2022/709) we have some very basic ground rules for adding/removing people to the module contributors:
     * @BowenBao please publish anywhere (public Google Doc would fine) maintainers document for ONNX module that should include: basic process how new contributors to the module should be added (will it be by voting? how someone can suggest new module contributor to you?), what are the pre-requirements for the maintainer (any number of PRs landed?)? Most important part, what is the time to first comment on the bug/PR in this module maintainers should commit to?
     * as soon as number 1 is done, @abock please confirm on this PR that you will be ok to own responsibility of reviewing bugs/PRs relevant to the module in which you will be now a maintainer

**Comment by malfet** [comment]
@b0noI I've edited your text a bit, leaving other comments below
> * each module from this file should be consistent with the[ Persons of Interest](https://pytorch.org/docs/stable/community/persons_of_interest.html) page(source [here](https://github.com/pytorch/pytorch/blob/master/docs/source/community/persons_of_interest.rst)), so please update it as well. Keep in mind that on POI page we should not be removing people, just making them as "emeritus"

Sorry, which file? 

And can you please elaborate, what's in your mind is the difference between POI and CODEOWNERS?
Is latter just tool that tells GH whom to assign reviewing PR touching particular files?

But regardless, I think merge_rules should be somewhat separate from both - POI/CodeOwner for a particular folder is free to add non-codeowner accounts as reviewers, and that does not imply that those person should also be reponsible for triaging incoming issues.

**Comment by b0noI** [comment]
> But regardless, I think merge_rules should be somewhat separate from both - POI/CodeOwner for a particular folder is free to add non-codeowner accounts as reviewers, and that does not imply that those person should also be reponsible for triaging incoming issues.

this commit changes merge_rules - defines who have the rights to merge changes, isn't? this should be exclusive rights to the maintainer

**Comment by b0noI** [comment]
thank you for updating POI file, since we are in the process of updating new process I want to unblock this PR ASAP, syncing with core maintainers to check if we are ok to unblock this without first publishing public doc that describes how new maintainers for ONNX are added. ETA: EOD today

**Comment by malfet** [comment]
@BowenBao can you please clarify in a few words why do you want to add @abock to merge rules, rather than @shubhambhokare1  or @AllenTiTaiWang , which would be more suitable candidates according to https://pytorch.org/docs/master/community/governance.html#module-maintainers

**Comment by BowenBao** [comment]
@b0noI @malfet Thanks for pointers to related pages. This PR was meant to be a simple inplace update, as @abock is taking over the role of @garymm as manager of our team. 
We will take a closer look at maintainer/contributor pages and publish the necessary info. Please give us more time for things to get settled and sorted out.

**Comment by BowenBao** [comment]
@b0noI can you share links to a few existing maintainer documents of other modules? We would like to know what are the standards and default for some of the questions above.

**Pull request closed without merging**
