### PR TITLE
Enable UFMT on `test/onnx_caffe2`, `test/optim`, `test/package` and `test/profiler`

### PR DESCRIPTION
**Pull request by shink**
Part of: #123062

Ran lintrunner on:

 - `test/onnx_caffe2`
- `test/optim`
- `test/package`
- `test/profiler`

### CODE REVIEW

**Comment by ezyang** [comment]
looks like it raced

**Comment by ezyang** [comment]
diff

```
diff --git b/test/profiler/test_profiler.py a/test/profiler/test_profiler.py
index f46087c6f06..8fb737981fc 100644
--- b/test/profiler/test_profiler.py
+++ a/test/profiler/test_profiler.py
@@ -3180,7 +3180,7 @@ class TestExperimentalUtils(TestCase):
             self.assertEqual(
                 event_metrics.self_time_ns,
                 event_key.event.duration_time_ns
-                - sum(child.duration_time_ns for child in event_key.event.children),
+                - sum([child.duration_time_ns for child in event_key.event.children]),
             )
 
     def test_utils_intervals_overlap(self):
```

looks sus

**Comment by shink** [comment]
@ezyang Thanks for your review. It have been fixed. See https://github.com/pytorch/pytorch/pull/123901/commits/bd5117ddcdc56d6bfe08342d3b9b9fe2c07c0792

**Comment by ezyang** [comment]
clean

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
