### PR TITLE
dbr quant: extend qconfig_dict support to functionals, part 2

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#69766 dbr quant: extend qconfig_dict support to functionals, part 2**
* #69758 dbr quant: extend qconfig_dict support to functions, part 1
* #69726 dbr quant: make fqn during prepare op hook required
* #69720 fx quant: move _parent_name to common utils
* #69719 dbr quant: initial support of qconfig_dict for modules
* #69636 fx quant: refactor qconfig_dict utils to separate file

Summary:

Follow-up on the previous PR, removes the requirement to have a parent
qconfig in order for the object type qconfig to be applied for a function.

Test plan:

```
python test/test_quantization.py TestQuantizeDBR
```

Differential Revision: [D33020218](https://our.internmc.facebook.com/intern/diff/D33020218)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Comment by jerryzh168** [comment]
does it mean we can remove https://github.com/pytorch/pytorch/blob/f205f1a3ba076e37a6f328d466a503e1523c616f/torch/ao/quantization/_quantize_dbr.py#L38 now?

**Review by jerryzh168 — APPROVED** [review]

**Comment by vkuzo** [comment]
> does it mean we can remove
> 
> https://github.com/pytorch/pytorch/blob/f205f1a3ba076e37a6f328d466a503e1523c616f/torch/ao/quantization/_quantize_dbr.py#L38
> 
> now?

currently eager mode quantization is called from this flow to swap the modules, I believe this function is still needed.  We may be able to remove it later with some refactoring.

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020218).

**Pull request closed without merging**
