### PR TITLE
Fix BytesWarning in torch.load()

### LINKED ISSUE #74812: BytesWarning causes exception in torch.load() when running Python with -bb flag
### 🐛 Describe the bug

When running Python with the [`-bb`](https://docs.python.org/3.10/using/cmdline.html#cmdoption-b) option, loading a model with `torch.load()` fails with a `BytesWarning`:

```console
$ python -bb -c 'import torch; torch.save(1, "test.pkl"); torch.load("test.pkl")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ahedges/projects/personal/pytorch/torch/serialization.py", line 700, in load
    if _is_zipfile(opened_file):
  File "/Users/ahedges/projects/personal/pytorch/torch/serialization.py", line 59, in _is_zipfile
    while byte != "":
BytesWarning: Comparison between bytes and string
```

This flag is useful to catch additional errors during testing, and I discovered this while working on a project that uses PyTorch. Fixing it here will make it easier to test other projects for errors, as well as reduce the chance for a similar bug in PyTorch.

I will be releasing a PR shortly.

### Versions

PyTorch version: 1.12.0a0+git5375b2e
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6.5 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.3
Libc version: N/A

Python version: 3.7.13 (default, Mar 17 2022, 14:15:44) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: Darwin-20.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.12.0a0+git5375b2e
[conda] Could not collect

cc @mruberry

### PR DESCRIPTION
**Pull request by aphedges**
Fixes #74812.

I have enabled the `-bb` option when tests are run to prevent regressions. I don't think it will make CI run more slowly, but I'm not entirely sure.

### CODE REVIEW

**Comment by aphedges** [comment]
Pinging @malfet (according to <https://github.com/pytorch/pytorch/wiki/Developer-FAQ#my-pr-hasnt-been-reviewed-in-a-while-what-should-i-do>).

**Comment by aphedges** [comment]
Pinging @malfet again. I would really appreciate a review.

**Review by kit1980 — APPROVED** [review]

**Comment by aphedges** [comment]
@kit1980, thank you very much!

**Comment by kit1980** [comment]
@aphedges I see now at least one test is failing, can you also update this?

```Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "test_torch.py", line 751, in test_cpp_warnings_have_python_context
    self.assertTrue(re.search(s, str(escaped_warning_message), re.IGNORECASE) is not None)
BytesWarning: str() on a bytes instance
```

**Comment by aphedges** [comment]
@kit1980, I'm not surprised that a failure happened, given that it's been so long. I'll push a fix within the next couple of days.

**Comment by aphedges** [comment]
This failure was caused by 2d4291fb81b385f2b6ec064b61599a9bcd75a519, but it's unclear why the change was made in the first place because it was a failure on the commit author's machine, not in CI. I asked for clarification at <https://github.com/pytorch/pytorch/pull/77531#discussion_r900461269>, but I have no clue if I'll get a response.

In the meantime, I'll push my fix and see if tests now pass.

**Comment by kit1980** [comment]
Let's land this.

**Comment by aphedges** [comment]
@kit1980, thank you very much!

**Comment by janeyx99** [comment]
@aphedges Sorry, but your change broke our slow tests that run on trunk only. :( When you reland this, please ensure the slow tests are run and pass by adding the ciflow/trunk label to your pull request.

@pytorchbot revert -m "Broke slow tests in cuda 10.2 https://github.com/pytorch/pytorch/runs/6944238177?check_suite_focus=true" -c nosignal

**Pull request closed without merging**
