### PR TITLE
Fix hash.h compile errors in newer compilers

### PR DESCRIPTION
**Pull request by apaszke**
Disable the default `std::hash<T>` overload if `T` is an enum type.

### CODE REVIEW

**Comment by stefan-it** [comment]
Hi @apaszke, 

GCC 7 is fine now. But I got an error message using clang in version 5:

```bash
torch/csrc/jit/generated/aten_dispatch.cpp:24:6: warning: unused function
      'pack_list' [-Wunused-function]
void pack_list(std::vector<Tensor> & outputs, Scalar v) { outputs.push_b...
     ^
In file included from torch/csrc/jit/python_arg_flatten.cpp:1:
In file included from torch/csrc/jit/python_arg_flatten.h:5:
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:75:12: error: call to
      'dispatch_hash' is ambiguous
    return _hash_detail::dispatch_hash(o);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:118:10: note: in
      instantiation of member function 'torch::hash<at::ScalarType>::operator()'
      requested here
  return torch::hash<T>()(o);
         ^
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:85:41: note: in
      instantiation of function template specialization
      'torch::_hash_detail::simple_get_hash<at::ScalarType>' requested here
      return hash_combine(_hash_detail::simple_get_hash(std::get<idx>(t)),
                                        ^
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:86:27: note: in
      instantiation of member function 'torch::hash<std::tuple<const
      std::vector<long, std::allocator<long> > &, const int &, const bool &,
      const at::ScalarType &, const bool &> >::tuple_hash<3, const
      std::vector<long, std::allocator<long> > &, const int &, const bool &,
      const at::ScalarType &, const bool &>::operator()' requested here
                          tuple_hash<idx-1, Ts...>()(t));
                          ^
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:98:12: note: in
      instantiation of member function 'torch::hash<std::tuple<const
      std::vector<long, std::allocator<long> > &, const int &, const bool &,
      const at::ScalarType &, const bool &> >::tuple_hash<4, const
      std::vector<long, std::allocator<long> > &, const int &, const bool &,
      const at::ScalarType &, const bool &>::operator()' requested here
    return tuple_hash<sizeof...(Types)-1, Types...>()(t);
           ^
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:132:10: note: in
      instantiation of member function 'torch::hash<std::tuple<const
      std::vector<long, std::allocator<long> > &, const int &, const bool &,
      const at::ScalarType &, const bool &> >::operator()' requested here
  return torch::hash<decltype(std::tie(args...))>()(std::tie(args...));
         ^
torch/csrc/jit/python_arg_flatten.h:28:14: note: in instantiation of function
      template specialization 'torch::get_hash<std::vector<long,
      std::allocator<long> >, int, bool, at::ScalarType, bool>' requested here
      return get_hash(m.sizes, m.device, m.requires_grad, m.type, m.is_v...
             ^
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:52:6: note: candidate
      function [with T = at::ScalarType]
auto dispatch_hash(const T& o) -> decltype(std::hash<T>()(o), std::size_t()) {
     ^
/mnt/Repositories/pytorch-clang/torch/csrc/utils/hash.h:59:68: note: candidate
      function [with T = at::ScalarType]
typename std::enable_if<std::is_enum<T>::value, std::size_t>::type dispa...
                                                                   ^
1 error generated.
```

**Comment by stefan-it** [comment]
GCC 7 is fine now. I'm currently testing some other compilers :)

**Comment by peterjc123** [comment]
@apaszke This one is not working in MSVC.

**Comment by peterjc123** [comment]
@apaszke My mistake. It works on MSVC. Thanks.

**Comment by stefan-it** [comment]
I can confirm that this patch works on Ubuntu 16.04 with:

* GCC 4.9.4
* GCC 5.4.1
* GCC 6.3.0
* GCC 4.8.5
* clang 3.8.0

And as mentioned above on ArchLinux with GCC 7.2.0 and clang 5.0 :)

**Comment by soumith** [comment]
awesome, thanks a lot for testing this well @stefan-it !

**Pull request merged**
