### PR TITLE
[quant] Add support for quantization of Embedding{Bag} in dynamic quant APIs

### PR DESCRIPTION
**Pull request by supriyar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65674

Summary:
Before this PR user had to use the eager mode static quantization APIs to quantize Embedding/EmbeddingBag modules.
With this PR they can use either the static or dynamic quantization APIs for Embedding quantization

The only qconfig supported for embedding quantization is float_qparams_weight_only_qconfig whcih is currently enforced in the from_float
method of the quantized Embedding/Embedding modules.

To combine embedding quantization with Linear dynamic quantization, user can use the qconfig_dict to specify different qconfig for each module type.

The prepare/convert APIs can still be used to quantize Embeddings, with the caveat that user need to ensure input to Embedding ops are FP32.

Addresses Issue #65185

Test Plan:
python test/test_quantization.py

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D31211199](https://our.internmc.facebook.com/intern/diff/D31211199)

### CODE REVIEW

**Review by vkuzo — APPROVED** [review]
lg

**Comment by jerryzh168** [comment]
I remember embedding/embeddigbag are actually weight_only quantization, do we also want to refactor the eager mode api to be more aligned with the fx graph mode api in the future (using tuples of activation_dtype, weight_dtype, compute_dtype to represent different types of quantization)?

**Comment by supriyar** [comment]
@supriyar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31211199).

**Comment by erksch** [comment]
Hey there! Did this land in PyTorch 1.10.0? 
Using `float_qparams_weight_only_qconfig` for `nn.Embedding` did not seem to do anything.

**Pull request closed without merging**
