### PR TITLE
Add half specializations for load of sum

### PR DESCRIPTION
**Pull request by CaoE**
Add half specializations for load of sum

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by sanchitintel** [comment]
sum has changed a lot since I last checked. This PR would help me towards vectorizing mean for FP16 with high numerical-accuracy.

**Comment by CaoE** [comment]
@jgong5 Could you please review this PR ? Thank you.

**Comment by CaoE** [comment]
@mingfeima Could you please help review this PR ? Thank you.

**Review by jgong5 — APPROVED** [review]
Do we have UT covering the change?

**Comment by CaoE** [comment]
> Do we have UT covering the change?

Existing UTs will cover the change.
https://github.com/pytorch/pytorch/blob/main/test/test_reductions.py#L1698

**Comment by CaoE** [comment]
@cpuhrsch Could you please review this PR ? Thank you.

**Review by cpuhrsch — APPROVED** [review]

**Comment by vadimkantorov** [comment]
Could a similar approach be also used for eliding an upcasting copy for:
- https://github.com/pytorch/pytorch/issues/55366

?

**Pull request closed without merging**
