### PR TITLE
Batched torch.eig() and use of magma for CUDA torch.eig() operation

### PR DESCRIPTION
**Pull request by mfkasim1**
This pull request is the first one in response to my feature request #32531 about batched `torch.eig()`.
It is actually harder than I previously thought and I ended up writing `torch.eig()` in ATen (replacing the legacy functions used beforehand).
I also create an eig function for CUDA using magma which in my run shows a slight improvement in terms of running time.

I haven't made the tests for batched `eig`, just to show that the change I made here does not break the previous tests for `torch.eig()`.
Should I add a new function in `test_torch.py` for batched eig or should I just change the function `test_eig`?

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 8e83819d:


* **4/4** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=8e83819d50d46099afca7d1102a7fd82bab7d49b).

### :detective: 4 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4402709) pytorch_linux_xenial_py3_5_build (1/4)
**Step:** "Should run job" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=94659966) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=94659966))
<details>
<summary>
<code>/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found</code>
</summary>

```
+ '[' -z pytorch-linux-xenial-py3.5-build ']' 
+ '[' -e /home/circleci/workspace/.circleci/scripts/COMMIT_MSG ']' 
+ '[' -n https://github.com/pytorch/pytorch/pull/32932 ']' 
+ [[ pull/32932 != \c\i\-\a\l\l\/* ]] 
+ [[ pull/32932 != \n\i\g\h\t\l\y ]] 
+ [[ pull/32932 != \p\o\s\t\n\i\g\h\t\l\y ]] 
+ '[' -e /home/circleci/workspace/.circleci/scripts/should_run_job.py ']' 
+ python /home/circleci/workspace/.circleci/scripts/should_run_job.py pytorch-linux-xenial-py3.5-build 
Rejecting pytorch-linux-xenial-py3.5-build 
+ circleci step halt 
/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4402718) pytorch_parallelnative_linux_xenial_py3_6_gcc5_4_build (2/4)
**Step:** "Should run job" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=94659995) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=94659995))
<details>
<summary>
<code>/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found</code>
</summary>

```
+ '[' -z pytorch-parallelnative-linux-xenial-py3.6-gcc5.4-build ']' 
+ '[' -e /home/circleci/workspace/.circleci/scripts/COMMIT_MSG ']' 
+ '[' -n https://github.com/pytorch/pytorch/pull/32932 ']' 
+ [[ pull/32932 != \c\i\-\a\l\l\/* ]] 
+ [[ pull/32932 != \n\i\g\h\t\l\y ]] 
+ [[ pull/32932 != \p\o\s\t\n\i\g\h\t\l\y ]] 
+ '[' -e /home/circleci/workspace/.circleci/scripts/should_run_job.py ']' 
+ python /home/circleci/workspace/.circleci/scripts/should_run_job.py pytorch-parallelnative-linux-xenial-py3.6-gcc5.4-build 
Rejecting pytorch-parallelnative-linux-xenial-py3.6-gcc5.4-build 
+ circleci step halt 
/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4402707) pytorch_paralleltbb_linux_xenial_py3_6_gcc5_4_build (3/4)
**Step:** "Should run job" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=94660233) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=94660233))
<details>
<summary>
<code>/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found</code>
</summary>

```
+ '[' -z pytorch-paralleltbb-linux-xenial-py3.6-gcc5.4-build ']' 
+ '[' -e /home/circleci/workspace/.circleci/scripts/COMMIT_MSG ']' 
+ '[' -n https://github.com/pytorch/pytorch/pull/32932 ']' 
+ [[ pull/32932 != \c\i\-\a\l\l\/* ]] 
+ [[ pull/32932 != \n\i\g\h\t\l\y ]] 
+ [[ pull/32932 != \p\o\s\t\n\i\g\h\t\l\y ]] 
+ '[' -e /home/circleci/workspace/.circleci/scripts/should_run_job.py ']' 
+ python /home/circleci/workspace/.circleci/scripts/should_run_job.py pytorch-paralleltbb-linux-xenial-py3.6-gcc5.4-build 
Rejecting pytorch-paralleltbb-linux-xenial-py3.6-gcc5.4-build 
+ circleci step halt 
/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4402795) binary_linux_manywheel_3_7m_cu100_devtoolset7_test (4/4)
**Step:** "Should run job" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=94660435) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=94660435))
<details>
<summary>
<code>/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found</code>
</summary>

```
+ '[' -z 'manywheel 3.7m cu100 devtoolset7' ']' 
+ '[' -e /home/circleci/workspace/.circleci/scripts/COMMIT_MSG ']' 
+ '[' -n https://github.com/pytorch/pytorch/pull/32932 ']' 
+ [[ pull/32932 != \c\i\-\a\l\l\/* ]] 
+ [[ pull/32932 != \n\i\g\h\t\l\y ]] 
+ [[ pull/32932 != \p\o\s\t\n\i\g\h\t\l\y ]] 
+ '[' -e /home/circleci/workspace/.circleci/scripts/should_run_job.py ']' 
+ python /home/circleci/workspace/.circleci/scripts/should_run_job.py 'manywheel 3.7m cu100 devtoolset7' 
Rejecting manywheel 3.7m cu100 devtoolset7 
+ circleci step halt 
/home/circleci/workspace/.circleci/scripts/should_run_job.sh: line 25: circleci: command not found 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by albanD** [comment]
Hi,

Thanks for the PR!
Could you rebase your branch on top of the 'viable/strict' branch (this is the latest master where all the tests are passing) to make sure all the CI work fine please?
At a glance, the code looks good.

You can add your tests to the `test_eig()`, just leave the existing ones and add yours below.

**Comment by mfkasim91** [comment]
Thanks for the comments and the review, @albanD. I will work on this after the other PR (#33090) is done. Although I think this PR should not affect the other PR, I think it's better to check if it works that way.

**Comment by mfkasim91** [comment]
I think I messed up the commits. Sorry. I will try to fix it

**Pull request closed without merging**
