### PR TITLE
[dynamo] Reserve the tensorrt backend name for torch-tensorrt

### PR DESCRIPTION
**Pull request by narendasan**
In PR #93822 the `fx2trt` backend was removed which registered the `tensorrt` backend names to point to `fx2trt` / `torch_tensorrt` and move the name to `onnxrt`. We want to reserve the name `tensorrt` for `torch_tensorrt` to prevent any confusion but due to code-freeze we cannot complete the integration and set up testing for the next release. So we propose leaving out the `tensorrt` name until we can set up the backend and testing for it. 

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by frank-wei — APPROVED** [review]
LGTM! We'd keep tensorrt for torch-tensorrt.

**Comment by narendasan** [comment]
@frank-wei How can i fix the CI issues?

**Comment by frank-wei** [comment]
@narendasan  looks like not this PR's fault. Can you rebase?

**Comment by frank-wei** [comment]
The failed tests are flaky which are not related to this PR.

**Comment by gottbrath** [comment]
@seemethere @malfet @atalman  I know this is coming late in the process but can we review this for Cherry picking into the release branch.  cc: @frank-wei

**Comment by malfet** [comment]
At the very quick glance at the PR, title does not correspond to what the code is actually doing (I.e. the registration is commented out)

**Comment by narendasan** [comment]
We didnt want to introduce a significant functional component this close to release. There doesnt seem to be a central registry for backend names so this was the closest I could think of to reserving the name i.e removing the tensorrt -> ONNX-RT mapping and putting in a placeholder file for tensorrt -> torch-trt

**Pull request closed without merging**
