### PR TITLE
Fix ideep submodule

### PR DESCRIPTION
**Pull request by kumpera**
It was incorrectly changed in #97157

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen

### CODE REVIEW

**Review by H-Huang — APPROVED** [review]

**Comment by weiwangmeta** [comment]
What is the delta between this PR and the PR #97430 ?

**Comment by yanbing-j** [comment]
> What is the delta between this PR and the PR #97430 ?

The `third_party/ideep` change in #97430  was reverted by https://github.com/pytorch/pytorch/pull/96226 by mistake. This PR is to move the change back.

**Pull request closed without merging**
