### PR TITLE
Add Half for aten2, logaddexp, logaddexp2, hypot, and nextafter on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Add Half for aten2, logaddexp, logaddexp2, hypot, and nextafter on CPU.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by thiagocrepaldi — COMMENTED** [review]
test/onnx/test_op_consistency.py change LGTM

**Comment by cpuhrsch** [comment]
@CaoE - Could I kindly ask you to prod me again to review this one after your other accepted PRs have merged?

**Comment by CaoE** [comment]
@cpuhrsch Of course, and thank you very much for your help.

**Comment by CaoE** [comment]
@cpuhrsch Other accepted PRs mentioned in https://github.com/pytorch/pytorch/pull/107764  have been merged.   Could you please review this PR ? Thank you.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
