### PR TITLE
[jit] allow dict to be mixed between tracing and scripting

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#39601 [jit] allow dict to be mixed between tracing and scripting**
* #40424 [jit] fix dictConstruct order issue

Differential Revision: [D22202689](https://our.internmc.facebook.com/intern/diff/D22202689)

### CODE REVIEW

**Comment by xw285cornell** [comment]
Thanks for working on this! Are the test failures related? 

Also is it possible to support Dict/List recursively, e.g. Dict[str, List[Tensor]]? (sorry for asking too much :( )

**Comment by wanchaol** [comment]
> Thanks for working on this! Are the test failures related?
> 
> Also is it possible to support Dict/List recursively, e.g. Dict[str, List[Tensor]]? (sorry for asking too much :( )

The test failures seems un-related, let me try to run them again. 

For recursive support, I think the current solution should work, if you look at the test case I added, it is `Dict[str, List[Tensor]`

**Comment by yf225** [comment]
Thanks a lot @wanchaol! This will unblock PyPer Feed preproc model tracing, and we urgently need this feature now. cc. @alyssawangqq

**Review by jamesr66a — APPROVED** [review]
Sure, looks fine. But I'd be interested to know:

1) Is an embedded ScriptObject call the only place we can see this used? I don't recall any ops that take dict, for example, but it would be nice to double check
2) What failure modes might look like, e.g. tracing a program that passes a dynamic dict to this thing, but the trace encode static values

**Comment by yf225** [comment]
With this patch applied on top of current master, I notice that if I traced the module with `{'x': torch.tensor(1)}` (i.e. dict with 1 key), I won't be able to run the traced module with `{'x': torch.tensor(1), 'y': torch.tensor(2)}` (i.e. dict with 2 keys). Curious is this expected? Thanks!
```python
import torch

from typing import Dict

class TestModule(torch.nn.Module):
    def __init__(self):
        super(TestModule, self).__init__()

    def forward(self, dict_input):
        @torch.jit.script
        def script_function(dict_input: Dict[str, torch.Tensor]):
            return dict_input['x']
        return script_function(dict_input)

input_1 = {'x': torch.tensor(1)}
input_2 = {'x': torch.tensor(2), 'y': torch.tensor(3)}

m = TestModule()
m_traced = torch.jit.trace(m, (input_1, ))
print(m_traced(input_1))
print(m_traced(input_2))
```
Output:
```
tensor(1)
Traceback (most recent call last):
  File "test_yf225.py", line 21, in <module>
    print(m_traced(input_2))
  File "/data/miniconda3/envs/working3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Expected 1 elements in a list but found 2
```

**Comment by wanchaol** [comment]
@jamesr66a 

> 1. Is an embedded ScriptObject call the only place we can see this used? I don't recall any ops that take dict, for example, but it would be nice to double check

I think it's true that no other real ops is taking dict. this only applies to mix tracing and scripting, so another possibility is to trace a function that embeds a script function (which takes dict as input). 


> 2. What failure modes might look like, e.g. tracing a program that passes a dynamic dict to this thing, but the trace encode static values

This seems the failure that @yf225 just posted, that we actually encode the static dict inputs here https://github.com/pytorch/pytorch/blob/caaf49d262a379f0ad3dac2d0659f742bfb29020/torch/csrc/jit/frontend/tracer.cpp#L331 when add the tracer inputs. IIRC this is because we need to connect the dict value tensors to the symbolic values generated, so that we could use it later on. This is something weird behavior that we impose to the user though

**Comment by wanchaol** [comment]
So as this is a separate issue from what we try to do in this PR, record this in https://github.com/pytorch/pytorch/issues/40529 and move the discussion there.

**Comment by xw285cornell** [comment]
Not supporting dynamic dict should be ok for my use case, as I expect the number of features will remain the same when we trace and actually using it :)

**Pull request closed without merging**
