### PR TITLE
update xnnpack to newer version and update API usage in pytorch

### PR DESCRIPTION
**Pull request by tiandiao123**
Summary:
Update XNNPACK to 51a987591a6fc9f0fc0707077f53d763ac132cbf (https://github.com/google/XNNPACK/commits/51a987591a6fc9f0fc0707077f53d763ac132cbf)

Update the corresponding CMake and BUCK rules, as well as the generate_wrapper.py for the new version.

Due to XNNPACK having already changed a lot. We need to update XNNPACK in this time for many reasons. Firstly, XNNAPCK has updated a lot, and developers' community has re-factored codes' such as API changes. We can see from their cmakefile.txt to see there are many changes! Thus, in order to follow up upstream. We need to update xnnpack at this time. It is very crucial for our future development. Also, many projects are relying on newer versions of XNNPACK, so we probably need to update XNNPACK third-party libs at this time. we have some api changes of XNNPACK, so we also need to update them in this time. We also update target building files and generate-wrapper.py file to make this process more automatically. The original target files have some files which are missing, so we add them into buck2 building files so that it can build and test XNNPACK successfully.

Test Plan:
buck2 build //xplat/third-party/XNNPACK:operators
buck2 build //xplat/third-party/XNNPACK:XNNPACK
buck2 test fbcode//caffe2/test:xnnpack_integration

Reviewed By: digantdesai

Differential Revision: D43092938

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @albanD

### CODE REVIEW

**Comment by tiandiao123** [comment]
@albanD
hello we are updating our diff to update xnnpack, but pytorch repo onlu allows 2000 lines codes' change. But I think since we are updating our new version of xnnpack, we cannot shrink it into smaller size, could you give us an exception?

**Comment by tiandiao123** [comment]
> @albanD @seemethere hello we are updating our diff to update xnnpack, but pytorch repo onlu allows 2000 lines codes' change. But I think since we are updating our new version of xnnpack, we cannot shrink it into smaller size, could you give us an exception?

@albanD or @seemethere

**Comment by albanD** [comment]
What's the difference with https://github.com/pytorch/pytorch/pull/94230 ? The questions there are still relevant to this PR right?

**Comment by tiandiao123** [comment]
> @albanD or @seemethere

that one can be closed, we actually combined 4 diffs into single one. This should be official for us @kirklandsign @digantdesai

**Comment by albanD** [comment]
Any reason why the script to generate this bzl files is not here? We could have it in our scripts/ folder to make sure we don't loose it.

Also are these bzl files used by the bazel build? FYI @vors

**Comment by digantdesai** [comment]
> Any reason why the script to generate this bzl files is not here? We could have it in our scripts/ folder to make sure we don't loose it.

We do have it here, just forgot to include that in this PR. @tiandiao123 will push an update soon.

> Also are these bzl files used by the (open source) bazel build? FYI @vors

Not sure TBH, XNNPACK supports bazel build so we should be using those for that.

**Comment by tiandiao123** [comment]
We have added generate-xnnpack-wrappers.py @albanD

**Review by albanD — COMMENTED** [review]
Sounds good once we have the generation script for these and all CI is green, thanks!

**Review by digantdesai — APPROVED** [review]
LGTM

**Review by albanD — APPROVED** [review]

**Comment by malfet** [comment]
This PR broke periodic builds, as it missed `ciflow/periodic`. I guess one need to update https://github.com/pytorch/pytorch/blob/master/third_party/generate-xnnpack-wrappers.py but I'm not sure if it's used correctly here

**Comment by tiandiao123** [comment]
> This PR broke periodic builds, as it missed `ciflow/periodic`. I guess one need to update https://github.com/pytorch/pytorch/blob/master/third_party/generate-xnnpack-wrappers.py but I'm not sure if it's used correctly here

we are investigating it.

**Pull request closed without merging**
