### PR TITLE
 [1/N] Apply clang-tidy to c10 cuda files

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by cyyever** [comment]
@zou3519  More changes were added.

**Review by Skylion007 — APPROVED** [review]

**Comment by malfet** [comment]
This is getting reverted internally right now, will post the reason soon

**Comment by malfet** [comment]
@cyyever can you please explain how `clang-tidy` come up with the following changes to the codebase:
```
- void update_stat(Stat& stat, int64_t amount) {
+ void add_amount_to_stat(Stat& stat, size_t amount) {
```

**Comment by malfet** [comment]
Ok, so before this change `python3 -c "import torch;y=torch.empty(3,device='cuda');print(torch.cuda.memory_stats(0)['max_split_size'])"` prints `-1`, after `18446744073709551615`

**Comment by cyyever** [comment]
@malfet I refactored the stat update functions to reduce the number of static_casts.

**Comment by cyyever** [comment]
> Ok, so before this change `python3 -c "import torch;y=torch.empty(3,device='cuda');print(torch.cuda.memory_stats(0)['max_split_size'])"` prints `-1`, after `18446744073709551615`

Is -1 a valid value before this change? If not, then it may indicate some invariant was violated already.

**Comment by malfet** [comment]
> I refactored the stat update functions to reduce the number of static_casts.

My point is that PR with 'apply clang-tidy' title should not contain any human made changes, only ones made by the tool.
As is PR title is misleading

**Comment by cyyever** [comment]
Exactly , the last commit should be separated. I will take care of this to avoid possible confusion.
________________________________

**Comment by kit1980** [comment]
> Exactly , the last commit should be separated. I will take care of this to avoid possible confusion.

@cyyever if you reland this, can you try to add a unit test that would catch the issue?

**Comment by cyyever** [comment]
@kit1980 All tests in CI passed before. malfet said 'the failures in torch.cuda.memory_stats(device=0) (presumably)" ' I am not sure which failures he referred, may be some META inner tests failed.

**Comment by kit1980** [comment]
> @kit1980 All tests in open source CI passed before while malfet said 'the failures in torch.cuda.memory_stats(device=0) (presumably) '. I am not sure which failures he referred, may be some META inner tests failed. Need more information to write tests

@cyyever yes, Meta internal tests failed (it was a complicated integration test). It would be great to have a simple unit test on GitHub that would have failed on the `update_stat` -> `add_amount_to_stat` changes.

**Comment by cyyever** [comment]
@kit1980 I supplied a patch in #111555, and I suspect previous changes made a negative stat number into a large positive one, so that some OOM behaviour trigged in the META test. Can you help import #111555 to verify that it passed the test? I will check the open source allocator tests and try to add some cases.

**Pull request closed without merging**
