### PR TITLE
`cosh`: port to structured kernel

### PR DESCRIPTION
**Pull request by SplitInfinity**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #55564 Migrate cos to structured kernel
* **#55563 Migrate cosh to structured kernel**
* #55540 Migrate acosh to structured kernel
* #55538 Migrate sinh to structured kernel

Differential Revision: [D27653767](https://our.internmc.facebook.com/intern/diff/D27653767)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
but need to do CUDA too!

**Comment by SplitInfinity** [comment]
> but need to do CUDA too!

What am I missing? I updated the CUDA kernel to use `TensorIteratorBase` instead of `TensorIterator`.

**Comment by ezyang** [comment]
Might be a problem with sinh, which is also got compilation errors

**Comment by SplitInfinity** [comment]
> Might be a problem with sinh, which is also got compilation errors

Ah yes, that would explain things.

**Pull request closed without merging**
