### PR TITLE
[pytorch] Make global module hook to pass kwargs similar to how module hook works

### PR DESCRIPTION
**Pull request by joebos**
Differential Revision: D63576353

### CODE REVIEW

**Comment by xw285cornell** [comment]
@albanD @jbschlosser this PR seems reasonable (more context in D63576353, c&p here: 

"
Currently you can register a module forward hook to a module, and get called with args, kwargs and output.
PyTorch also supports global module forward hook so we do not need to register the hook at each module level. however, current global hook can only pass args and ouput. It does not support kwargs passing.
This diff is to make the global module  hook to pass kwargs, same as module level hook does.
"

Wondering do you know who should be the best reviewer for this?

**Review by mikaylagawarecki — COMMENTED** [review]
Sorry for missing this, this looks alright but can we perhaps add a small test in https://github.com/pytorch/pytorch/blob/main/test/nn/test_module_hooks.py and also fix lint

**Review by mikaylagawarecki — COMMENTED** [review]
https://github.com/pytorch/pytorch/pull/137403#issuecomment-2395205289 please also sign the CLI and add the test per https://github.com/pytorch/pytorch/pull/137403#pullrequestreview-2385504564

**Comment by joebos** [comment]
> [#137403 (comment)](https://github.com/pytorch/pytorch/pull/137403#issuecomment-2395205289) please also sign the CLI and add the test per [#137403 (review)](https://github.com/pytorch/pytorch/pull/137403#pullrequestreview-2385504564)
The PR/diff is updated, mikaylagawarecki, could you help review again?

**Review by mikaylagawarecki — COMMENTED** [review]
This looks good, just need to fix lint, fyi external and internal lintrunner are different (but we need external lintrunner to pass to merge this).

Could you undo the internal lintrunner changes and do [`make setuplint`](https://github.com/pytorch/pytorch/blob/main/Makefile#L45) and `lintrunner -a`?

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Pull request closed without merging**
