### PR TITLE
Fix backward of binary_cross_entropy_with_logits

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #79381
* #77975

The previous PR in this stack uncovered an error in the forward over
backward for this function.

In this PR, we fix this error and we also fix the gradgrad
implementation (and make it more stable and faster using `logsigmoid`).
We also move the double backward for this function to `FunctoinsManual`
as there's no reason for it to be in `native_functions`

Fixes https://github.com/pytorch/pytorch/issues/79609

Differential Revision: [D37282004](https://our.internmc.facebook.com/intern/diff/D37282004)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Comment by Lezcano** [comment]
@JackCaoG this one's also going to need a matching PR on the XLA side

**Comment by JackCaoG** [comment]
SG, I will try to draft a xla change today or tmr.

**Comment by JackCaoG** [comment]
XLA actually does not lower this op. Test failed because of `l1_loss_backward` which pr is already ready.

**Comment by Lezcano** [comment]
You are right! Sorry for the noise!

How should we go about merging the fist PR of this stack though? Can we go forward with it?

**Comment by JackCaoG** [comment]
@Lezcano There is a new policy regarding that, I was hoping @bdhirsh can shed some light. I think I will need to merge my pr first, but then in this pr you need to update the xla pin for pytorch repo(pytorch now pins to a fix version of pt/xla, in order to make ci pass you need to update that pin when mergin this pr).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37282004).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37282004).

**Comment by janeyx99** [comment]
Oh no, this was a false revert -- sorry about that @Lezcano! The test is still failing even after the revert--feel free to reland.

**Pull request closed without merging**
