### PR TITLE
Add assertions to fix torch::jit::load bugs

### LINKED ISSUE #77561: Unhandled std::out_of_range exception in torch::jit::load()
### 🐛 Describe the bug

Hi,
I found uncaught exception during testing with libFuzzer.
The out_of_range exception occurs at `/pytorch/aten/src/ATen/core/ivalue_inl.h:501` during execution of torch::jit::load() funciton:
```
    498          TORCH_CHECK(idx < inlineSize_, \"TupleElements: invalid index Index = \", idx, \"; Length = \", inlineSize_);
    499          return elementsInline_[idx];
    500        } else {
--->501          return elementsVector_.at(idx);
    502        }
    503      }
    504    
    505      C10_NODISCARD iterator begin() {
    506        if (inlineSize_) {
    507          return elementsInline_;
    508        } else {
    509          return elementsVector_.data()

```

The bug could be reproduced with `aot_model_compiler` binary:
```
aot_model_compiler --model=crash-file --model_name=name --model_version=1 --input_dims='1,3,224,224;2,2' --input_types='float;float'
```
Crashing file is provided in [crash.zip](https://github.com/pytorch/pytorch/files/8701735/crash.zip)

Asan output is:
```
  "AsanReport": [
    "==142006== ERROR: libFuzzer: deadly signal\n",
    "[Detaching after fork from child process 142353]\n",
    "    #0 0x59ec11 in __sanitizer_print_stack_trace /llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3\n",
    "    #1 0x513547 in fuzzer::PrintStackTrace() /llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5\n",
    "    #2 0x4f9753 in fuzzer::Fuzzer::CrashCallback() /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3\n",
    "    #3 0x7f402f8a63bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)\n",
    "    #4 0x7f402f6c818a in __libc_signal_restore_set /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3\n",
    "    #5 0x7f402f6c818a in raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3\n",
    "    #6 0x7f402f6a7858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7\n",
    "    #7 0x7f402fab2910  (/lib/x86_64-linux-gnu/libstdc++.so.6+0x9e910)\n",
    "    #8 0x7f402fabe38b  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa38b)\n",
    "    #9 0x7f402fabe3f6 in std::terminate() (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa3f6)\n",
    "    #10 0x7f402fabe6a8 in __cxa_throw (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa6a8)\n",
    "    #11 0x7f402fab53aa  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa13aa)\n",
    "    #12 0x6a4cdf in std::vector<c10::IValue, std::allocator<c10::IValue> >::_M_range_check(unsigned long) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:1073:4\n",
    "    #13 0x9315ee3 in std::vector<c10::IValue, std::allocator<c10::IValue> >::at(unsigned long) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:1112:2\n",
    "    #14 0x9315ee3 in c10::ivalue::TupleElements::at(unsigned long) const /pytorch_fuzz/aten/src/ATen/core/ivalue_inl.h:501:30\n",
    "    #15 0x9ec5505 in torch::jit::restoreAccurateTypeTags(c10::IValue const&, c10::Type::SingletonOrSharedTypePtr<c10::Type> const&) /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:97:64\n",
    "    #16 0x9e0514b in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1::operator()(c10::StrongTypePtr const&, c10::IValue) const /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:157:7\n",
    "    #17 0x9e0514b in c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > std::__invoke_impl<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >, torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr, c10::IValue>(std::__invoke_other, torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr&&, c10::IValue&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14\n",
    "    #18 0x9e044b0 in std::enable_if<__and_<std::__not_<std::is_void<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > > >, std::is_convertible<std::__invoke_result<torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr, c10::IValue>::type, c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > > >::value, c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > >::type std::__invoke_r<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >, torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr, c10::IValue>(torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1&, c10::StrongTypePtr&&, c10::IValue&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:141:14\n",
    "    #19 0x9e0431b in std::_Function_handler<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue), torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_1>::_M_invoke(std::_Any_data const&, c10::StrongTypePtr&&, c10::IValue&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:291:9\n",
    "    #20 0x9eed44d in std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)>::operator()(c10::StrongTypePtr, c10::IValue) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14\n",
    "    #21 0x9eed0ee in torch::jit::Unpickler::readGlobal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_9::operator()() const /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:704:20\n",
    "    #22 0x9eed0ee in void std::__invoke_impl<void, torch::jit::Unpickler::readGlobal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_9&>(std::__invoke_other, torch::jit::Unpickler::readGlobal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_9&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14\n",
    "    #23 0x9ecb6d4 in torch::jit::Unpickler::readInstruction() /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:444:7\n",
    "    #24 0x9ec9ac7 in torch::jit::Unpickler::run() /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:226:27\n",
    "    #25 0x9ec9762 in torch::jit::Unpickler::parse_ivalue() /pytorch_fuzz/torch/csrc/jit/serialization/unpickler.cpp:183:3\n",
    "    #26 0x9e0c84e in torch::jit::readArchiveAndTensors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<std::function<c10::StrongTypePtr (c10::QualifiedName const&)> >, c10::optional<std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, caffe2::serialize::PyTorchStreamReader&, c10::Type::SingletonOrSharedTypePtr<c10::Type> (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::shared_ptr<torch::jit::DeserializationStorageContext>) /pytorch_fuzz/torch/csrc/jit/serialization/import_read.cpp:54:20\n",
    "    #27 0x9e02779 in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::readArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:171:10\n",
    "    #28 0x9dfe60b in torch::jit::(anonymous namespace)::ScriptModuleDeserializer::deserialize(c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:274:19\n",
    "    #29 0x9e013c4 in torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:403:23\n",
    "    #30 0x9e01977 in torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:375:17\n",
    "    #31 0x9e0176c in torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>) /pytorch_fuzz/torch/csrc/jit/serialization/import.cpp:367:10\n",
    "    #32 0x5cdfd2 in LLVMFuzzerTestOneInput /load_fuzz.cc:45:18\n",
    "    #33 0x4fac81 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15\n",
    "    #34 0x4e4b9c in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6\n",
    "    #35 0x4ea8eb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9\n",
    "    #36 0x513e82 in main /llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10\n",
    "    #37 0x7f402f6a90b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16\n",
    "    #38 0x4df4bd in _start (/fuzz/load_fuzz+0x4df4bd)\n",
```

### Versions

PyTorch version: 1.12.0a0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 14.0.0 (https://github.com/llvm/llvm-project.git de5b16d8ca2d14ff0d9b6be9cf40566bc7eb5a01)
CMake version: version 3.22.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-175-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.2
[conda] Could not collect

### PR DESCRIPTION
**Pull request by apach301**
Fixes #77561, #77563, #77573 and #77575

### CODE REVIEW

**Comment by apach301** [comment]
@Gamrix I fixed some bugs by adding assertions (https://github.com/pytorch/pytorch/issues/77561#issuecomment-1145433818)

**Review by Gamrix — CHANGES_REQUESTED** [review]
Some of the tests are reporting errors due to your changes. Could you please fix the signed/unsigned comparisons and submit it again? 

Sample Error:

```
var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/conv_serialization.h:310:31: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     TORCH_INTERNAL_ASSERT(idx < config_vals.size(), "Unexpected index = ", idx, " for config_vals.");
/var/lib/jenkins/workspace/c10/macros/Macros.h:205:64: note: in definition of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^~~~
/var/lib/jenkins/workspace/c10/util/Exception.h:332:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                          \
       ^~~~~~~~~~~~~~~~~~~~~
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/conv_serialization.h:310:5: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     TORCH_INTERNAL_ASSERT(idx < config_vals.size(), "Unexpected index = ", idx, " for config_vals.");
     ^
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/conv_serialization.h: In instantiation of ‘c10::intrusive_ptr<ConvPackedParamsBase<kSpatialDim> > deserialize_conv(ConvParamsSerializationTypeV3) [with unsigned int kSpatialDim = 3; ConvParamsSerializationTypeV3 = std::tuple<long int, std::vector<long int, std::allocator<long int> >, std::vector<c10::optional<at::Tensor>, std::allocator<c10::optional<at::Tensor> > > >]’:
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/fbgemm_utils.cpp:397:47:   required from ‘register_conv_params()::<lambda(c10::IValue)> [with int kSpatialDim = 3]’
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/fbgemm_utils.cpp:394:10:   required from ‘struct register_conv_params() [with int kSpatialDim = 3]::<lambda(struct c10::IValue)>’
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/fbgemm_utils.cpp:399:6:   required from ‘int register_conv_params() [with int kSpatialDim = 3]’
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/fbgemm_utils.cpp:424:39:   required from here
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/conv_serialization.h:310:31: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     TORCH_INTERNAL_ASSERT(idx < config_vals.size(), "Unexpected index = ", idx, " for config_vals.");
/var/lib/jenkins/workspace/c10/macros/Macros.h:205:64: note: in definition of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^~~~
/var/lib/jenkins/workspace/c10/util/Exception.h:332:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {                                          \
       ^~~~~~~~~~~~~~~~~~~~~
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cpu/conv_serialization.h:310:5: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
     TORCH_INTERNAL_ASSERT(idx < config_vals.size(), "Unexpected index = ", idx, " for config_vals.");
     ^
cc1plus: all warnings being treated as error
```

**Comment by apach301** [comment]
@Gamrix I fixed the signed comparison error in assertions. Could you please re-run all workflows to check it? Also there is another PR #77557 that have all checks passed.

**Comment by Gamrix** [comment]
Rebasing to check if these errors are related to your change. 
`2022-08-09T23:23:21.9441210Z Build left local git repository checkout dirty` is weird but I could see how one of these changes might have caused this. 

@pytorchmergebot rebase -s

**Review by Gamrix — APPROVED** [review]
Looks good to me. Thanks for adding some more error checking so that debugging would be easier.

**Comment by Gamrix** [comment]
@pytorchmerebot merge

**Pull request closed without merging**
