### PR TITLE
[compiled autograd] initialize cudagraph tls from context manager

### PR DESCRIPTION
**Pull request by xmfan**
FIXES https://github.com/pytorch/pytorch/issues/126934. Cudagraphs TLS is initialized on module import, but compiled autograd codepaths might not import it. This causes problems because autograd/compiled autograd will restore TLS state, and in this case will restore the TLS to an uninitialized state

Should fix flaky cudagraph tests: https://github.com/pytorch/pytorch/issues/131663, https://github.com/pytorch/pytorch/issues/132108

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #135402
* #137251
* #136695
* __->__ #136735
* #136059

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by BoyuanFeng — APPROVED** [review]

**Review by eellison — APPROVED** [review]
are there any other relevant codepaths that we might need to important cudagraphs for ?

**Comment by xmfan** [comment]
Nothing else for compiled autograd

**Pull request closed without merging**
