### PR TITLE
Add SGDR(Stochastic Gradient Descent with Warm Restarts) scheduler

### PR DESCRIPTION
**Pull request by Kirayue**
Add SGDR(Stochastic Gradient Descent with Warm Restarts) scheduler to `lr_scheduler.py`.

### CODE REVIEW

**Comment by Kirayue** [comment]
Sorry, I do not know what's wrong with `ci/circleci: pytorch_linux_trusty_py2_7_9_test`.

**Comment by weiyangfb** [comment]
could you add a test at `test_optim.py`?

**Comment by Kirayue** [comment]
Sure, thank you.

**Comment by soumith** [comment]
@Kirayue your PR is failing in python2 (rightly so):

```
Dec 24 07:14:55 ======================================================================
Dec 24 07:14:55 ERROR: test_sgdr_lr1 (__main__.TestLRScheduler)
Dec 24 07:14:55 ----------------------------------------------------------------------
Dec 24 07:14:55 Traceback (most recent call last):
Dec 24 07:14:55   File "test_optim.py", line 811, in test_sgdr_lr1
Dec 24 07:14:55     scheduler = SGDR(self.opt, T_0=T, T_mult=T_mult, eta_min=eta_min)
Dec 24 07:14:55   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/optim/lr_scheduler.py", line 464, in __init__
Dec 24 07:14:55     super().__init__(optimizer, last_epoch)
Dec 24 07:14:55 TypeError: super() takes at least 1 argument (0 given)
Dec 24 07:14:55 
Dec 24 07:14:55 ======================================================================
Dec 24 07:14:55 ERROR: test_sgdr_lr2 (__main__.TestLRScheduler)
Dec 24 07:14:55 ----------------------------------------------------------------------
Dec 24 07:14:55 Traceback (most recent call last):
Dec 24 07:14:55   File "test_optim.py", line 828, in test_sgdr_lr2
Dec 24 07:14:55     scheduler = SGDR(self.opt, T_0=T, T_mult=T_mult, eta_min=eta_min)
Dec 24 07:14:55   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/optim/lr_scheduler.py", line 464, in __init__
Dec 24 07:14:55     super().__init__(optimizer, last_epoch)
Dec 24 07:14:55 TypeError: super() takes at least 1 argument (0 given)
Dec 24 07:14:55 
Dec 24 07:14:55 ======================================================================
Dec 24 07:14:55 ERROR: test_sgdr_lr3 (__main__.TestLRScheduler)
Dec 24 07:14:55 ----------------------------------------------------------------------
Dec 24 07:14:55 Traceback (most recent call last):
Dec 24 07:14:55   File "test_optim.py", line 845, in test_sgdr_lr3
Dec 24 07:14:55     scheduler = SGDR(self.opt, T_0=T, T_mult=T_mult, eta_min=eta_min)
Dec 24 07:14:55   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/optim/lr_scheduler.py", line 464, in __init__
Dec 24 07:14:55     super().__init__(optimizer, last_epoch)
Dec 24 07:14:55 TypeError: super() takes at least 1 argument (0 given)
Dec 24 07:14:55 
Dec 24 07:14:55 ======================================================================
Dec 24 07:14:55 ERROR: test_sgdr_lr4 (__main__.TestLRScheduler)
Dec 24 07:14:55 ----------------------------------------------------------------------
Dec 24 07:14:55 Traceback (most recent call last):
Dec 24 07:14:55   File "test_optim.py", line 862, in test_sgdr_lr4
Dec 24 07:14:55     scheduler = SGDR(self.opt, T_0=T, T_mult=T_mult, eta_min=eta_min)
Dec 24 07:14:55   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/optim/lr_scheduler.py", line 464, in __init__
Dec 24 07:14:55     super().__init__(optimizer, last_epoch)
Dec 24 07:14:55 TypeError: super() takes at least 1 argument (0 given)
Dec 24 07:14:55 
Dec 24 07:14:55 ======================================================================
Dec 24 07:14:55 ERROR: test_sgdr_lr_state_dict (__main__.TestLRScheduler)
Dec 24 07:14:55 ----------------------------------------------------------------------
Dec 24 07:14:55 Traceback (most recent call last):
Dec 24 07:14:55   File "test_optim.py", line 930, in test_sgdr_lr_state_dict
Dec 24 07:14:55     lambda: SGDR(self.opt, T_0=100))
Dec 24 07:14:55   File "test_optim.py", line 933, in _check_scheduler_state_dict
Dec 24 07:14:55     scheduler = constr()
Dec 24 07:14:55   File "test_optim.py", line 929, in <lambda>
Dec 24 07:14:55     lambda: SGDR(self.opt, T_0=10, T_mult=2),
Dec 24 07:14:55   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/optim/lr_scheduler.py", line 464, in __init__
Dec 24 07:14:55     super().__init__(optimizer, last_epoch)
Dec 24 07:14:55 TypeError: super() takes at least 1 argument (0 given)
Dec 24 07:14:55 
Dec 24 07:14:55 ----------------------------------------------------------------------
```

**Comment by Kirayue** [comment]
@soumith thank you for your help.  But there is still failing in python2.

**Comment by Kirayue** [comment]
Could you teach me where to see the failure message as you mentioned above?

**Comment by soumith** [comment]
@Kirayue click on the "Details" button on the failing CI tests in this page, to see the failures.
Here's a screenshot:
screen shot 2018-12-26 at 2 01 26 am

**Comment by Kirayue** [comment]
Hi, @soumith
I clicked  "Details" and saw this page. here is a screenshot for "ci/circleci: pytorch_linux_trusty_py2_7_build".

image

I don't know what's wrong with my code. Thank you so much for the speedy reply.

**Comment by soumith** [comment]
@Kirayue those three failures are not your fault. it looks like the CI system's infrastructure failures.

**Comment by Kirayue** [comment]
Is there any progress on this error?

**Comment by ezyang** [comment]
Hi @Kirayue, we shouldn't use numpy for these tests; these should be written in pure PyTorch. (We also need a merge with master, but that is easy; the conflict is just imports)

**Comment by ezyang** [comment]
The CI error is not your fault, and if you merge with master the CI will retrigger.

**Comment by Kirayue** [comment]
Hi, @ezyang 
Thanks for getting back to me. Sorry to bother you, I’m not sure I understand `merge with master`.
This is what I am going to do,
1. sync pytorch(pytorch:master) to my fork(pytorch/master) master 
2. merge pytorch/master to pytorch/sgdr under my fork 
Is that right?

**Comment by ezyang** [comment]
I generally merge to master like this: (I am assuming that `origin` is pytorch/pytorch)

```
git fetch origin
git merge origin/master
git push # or whatever it is you do to push to your branch
```

**Comment by Kirayue** [comment]
Hi, @ezyang, sorry to bother you again. I followed the steps you mentioned, and I merged with `pytorch:master`. Is there anything wrong with the merge,  there are many files that I did not modify.

**Comment by ezyang** [comment]
Yes, something bad has happened. Can you reset your branch to the old version, push it to a new branch and open a new PR (this time, allow maintainers to make edits). I will complete the merge for you.

**Pull request closed without merging**
