### PR TITLE
Avoid unnecessary copy of Tensor in softmax

### PR DESCRIPTION
**Pull request by ezgicicek**
Summary:
This opportunity was found with the combination of [Infer's PULSE_UNNECESSARY_COPY analysis and Strobelight cycle counts](https://fb.workplace.com/groups/infer.eng/permalink/970566283876913/).

This shows up as one of the top issues ordered by inclusive cycle counts across the whole fleet (D33790780) with cycles **226,757,691,000**

Differential Revision: D35814997

### CODE REVIEW

**Comment by vadimkantorov** [comment]
this is rather minor, right? the tensor data itself isn't copied, right?

**Comment by albanD** [comment]
The Tensor data isn't copied indeed. This is just saving two atomic ops.

**Comment by ezgicicek** [comment]
Oh, you are right! I think Infer got confused here because in the declaration of `converted`, the first branch (`input_.toType(dtype.value())`) will not create a copy, only the second branch (there is a call to a copy constructor for `input`). I will try to fix our analysis to not report on these.

@albanD Which atomic ops you meant?

**Comment by albanD** [comment]
> (there is a call to a copy constructor for input)

Yes but the `Tensor` class can be though as `std::shared_ptr<TensorImpl>`. So the copy constructor for Tensor here is only doing a refcount bump. Which is relatively cheap compared to everything else happening in that function.

**Pull request closed without merging**
