### PR TITLE
[autograd] Avoid holding lock when completing GraphTask futureResult

### PR DESCRIPTION
**Pull request by jjlilley**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#35101 [autograd] Avoid holding lock when completing GraphTask futureResult**

TSAN is noting lock-order-inversion in context of dist autograd because
we're holding lock when GraphTask calls markCompleted() on the relevant futureResult_.

Add an atomic bool to make it possible to protect this without holding the mutex,
and also fix alignment of a few struct vars.

Differential Revision: [D20553517](https://our.internmc.facebook.com/intern/diff/D20553517/)

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I'm not sure to grasp the root cause of the problem here and when it was introduced?

Was this introduced when the future API was added and we should never hold the graph_task lock when completing the future? (or it should be a reentrant lock?)
Or is it the special use of the future that the distributed engine does that leads to this issue?

**Comment by jjlilley** [comment]
> I'm not sure to grasp the root cause of the problem here and when it was introduced?
> 
> Was this introduced when the future API was added and we should never hold the graph_task lock when completing the future? (or it should be a reentrant lock?)
> Or is it the special use of the future that the distributed engine does that leads to this issue?

So, looking at this a bit: 
- The future logic appears that this logic has been in the branch since 05 Jan.
- Given circleci results, this particular patch definitely needs a tweak for tests.
- I stumbled on the when I noticed TSAN complaining about lock order violations within the different node callbacks in dist autograd.
-  Right now, we're calling accumulateGrad() in the DistEngine from the completed callback, and ends up being a longer-than-ideal chain of code being called underneath an arbitrary lock.

My goal here is simply that if we can avoid holding the lock while calling a number of hard-to-audit and hard-to-reason-about callbacks, the codebase will be healthier for this.

**Comment by albanD** [comment]
That sounds good.
But if the problem is that we should be very careful not to hold a lock when we complete a future to avoid this. Then this must happen everywhere where future are used?

Also not sure what the flag is atomic in the latest version of the PR as it is only used while the lock is held?

**Comment by jjlilley** [comment]
> That sounds good.
> But if the problem is that we should be very careful not to hold a lock when we complete a future to avoid this. Then this must happen everywhere where future are used?

Yes, we should be careful to avoid unnecessarily holding locks when completing futures. In some cases, it might be unavoidable. The potential deadlock risk isn't unique to these futures - any callback scheme has this possible issue.
 
> Also not sure what the flag is atomic in the latest version of the PR as it is only used while the lock is held?

Right, I need to check a few things with this change before re-uploading. I wish it were possible (like in Phabricator) to mark "changes planned."

**Comment by albanD** [comment]
We usually put a [WIP] in the PR title if it is being worked on and not ready for review.

**Comment by jjlilley** [comment]
> That sounds good. Can you add a quick comment in the code to make sure this is documented?

Will do.

> We usually put a [WIP] in the PR title if it is being worked on and not ready for review.

Thanks for the [WIP] suggestion in the title - I'll do that, still learning the conventions on this project :)

**Comment by jjlilley** [comment]
This should be ready for a look (Pritam?) - I think we're better off not holding a mutex across the CB invocation here, since there's a big unknown in the downstream callbacks (e.g. in dist_engine)

**Review by osalpekar — APPROVED** [review]
I ran into this same deadlock issue when the Distributed Autograd callbacks tried to acquire the graph_task mutex. Thanks @jjlilley!

**Comment by jjlilley** [comment]
Thanks for looking!

**Pull request closed without merging**
