### PR TITLE
[jit] Improve type unifcation error

### PR DESCRIPTION
**Pull request by driazati**

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
Instead of fixing tensor lists, can you make the general change?

We should be running `unifyTypeList` on the inputs to the list instead of trying to unify the type with only the first element. 

This would fix the case of `my_opt_list = [1, None, 2]`.

**Comment by eellison** [comment]
Also how did you run into this?

**Comment by driazati** [comment]
This was the `bad optional access` error from fairseq

**Comment by driazati** [comment]
Closing in favor of #30777

**Pull request closed without merging**
