### PR TITLE
Changing from sample_inputs to reference_inputs in test_compare_cpu

### PR DESCRIPTION
**Pull request by srossross**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #85583
* __->__ #86462

### CODE REVIEW

**Comment by srossross** [comment]
@lezcano can you take a look before I request a review?

**Review by lezcano — APPROVED** [review]
LGTM

**Review by mruberry — APPROVED** [review]
Cool; nice comments for the new xfails.

**Comment by mruberry** [comment]
The ROCm failures look real:

```
2022-10-26T21:39:34.0129521Z ==================================== RERUNS ====================================
2022-10-26T21:39:34.0129823Z _____ TestCommonCUDA.test_compare_cpu__refs_bitwise_right_shift_cuda_int64 _____
2022-10-26T21:39:34.0130099Z Unexpected success
2022-10-26T21:39:34.0130386Z _____ TestCommonCUDA.test_compare_cpu__refs_bitwise_right_shift_cuda_int64 _____
2022-10-26T21:39:34.0130651Z Unexpected success
2022-10-26T21:39:34.0130867Z =================================== FAILURES ===================================
2022-10-26T21:39:34.0131163Z _____ TestCommonCUDA.test_compare_cpu__refs_bitwise_right_shift_cuda_int64 _____
2022-10-26T21:39:34.0131593Z Unexpected success
```

some of the xfails may need to become skips because CPUs are inconsistently consistent with CUDA

**Pull request closed without merging**
