### PR TITLE
Cleanup `.watchman` file

### PR DESCRIPTION
**Pull request by eqy**
This seems to be an artifact from an fb tool that snuck into a commit (#113117)? CC @malfet

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Seems like the addition was unintentional to me. cc PR author @stroxler and reviewer @yanboliang

**Review by yanboliang — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Hmm, we should have added this one to .gitignore, PR is coming

**Pull request closed without merging**
