### PR TITLE
DOC: remove java documentation

### PR DESCRIPTION
**Pull request by mattip**
Continuation of issue gh-36064 and PR gh-38042 which removed the unmaintained javaspinx extension. The unknown sphinx directives cause warnings when building documentation.

Edit: link to PR as well as issue

### CODE REVIEW

**Comment by ShawnZhong** [comment]
I'm not sure if we want to remove the java docs entirely since they are still being served at https://pytorch.org/docs/stable/packages.html.

**Comment by ShawnZhong** [comment]
I just found another URL https://pytorch.org/javadoc/ serving the Javadoc, but it is not linked from the main docs site.

**Comment by mattip** [comment]
I may be off the mark here, but it seems this PR should have been part of gh-38042. When a new release builds the new `stable` docs, the pages you link to will silently disappear, no? If there is a process to revert gh-38042 in order to build the pages for a release, then reverting the effects of this PR should be part of that process. If  https://pytorch.org/javadoc/ is the canonical link to the Java documentation, I could add a link to it in-place of the link to `packages` in the Language Bindings section of [index.rst](https://github.com/pytorch/pytorch/blob/v1.5.0/docs/source/index.rst). How are those pages built?

**Comment by ShawnZhong** [comment]
BTW, I found an old PR https://github.com/pytorch/pytorch/pull/31956 which seems to be a combination of #36064 and this PR. 

I agree that we should remove `docs/source/org/pytorch/*.rst` in favor of `https://pytorch.org/javadoc/`, which seems to be built manually by @jlin27 in https://github.com/pytorch/pytorch.github.io/pull/326 and served at https://github.com/pytorch/pytorch.github.io/tree/site/javadoc.

**Comment by ezyang** [comment]
For the record, gh-38042 happened because the Sphinx upgrade broke completely when we had javasphinx. @jlin27 would be better able to say what the future of our Java documentation should be. However, I think it's definitely true that we need Java documentation of some sort; probably just not through sphinx! Also cc @dreiss

**Comment by jlin27** [comment]
The most recent Javadocs process is what Shawn pointed to here: https://github.com/pytorch/pytorch.github.io/pull/326 
The reason for this method was an ask from the Java team to format the docs to match the industry standard Javadoc theme plus add the outer PyTorch dot org website frame, so we custom applied these in the html files. 

The original version of the Javadocs was just created via javaphinx from the rst files under https://github.com/pytorch/pytorch/tree/master/docs/source/org/pytorch

After you pointed it out, I realized that the index.rst in master and 1.5 link to the old javadocs files, so I've updated them to the recent ones in these PRs:
* [master] https://github.com/pytorch/pytorch/pull/39038
* [1.5] https://github.com/pytorch/pytorch/pull/39039

I propose that after the above 2 PRs are merged, we remove all the Javadoc files from pytorch/pytorch:
* https://github.com/pytorch/pytorch/tree/master/docs/source/org/pytorch
* https://github.com/pytorch/pytorch/blob/master/docs/source/packages.rst

**Review by jlin27 — APPROVED** [review]

**Comment by jlin27** [comment]
Circling back to say the PRs to reference Javadocs from https://pytorch.org/javadoc/ the have been merged, so this PR to remove unused documentation can go ahead. The site no longer points to javadocs generated from these rst files.

**Pull request closed without merging**
