### PR TITLE
[c10d] Make NCCL backend support barrier op

### PR DESCRIPTION
**Pull request by teng-li**
This is a feature request from: https://github.com/pytorch/pytorch/issues/13573

As the title says, this PR makes NCCL backend support barrier op.

There are a couple scenarios that need to be addressed:
(1) When there is already a NCCL op happened, we need to record what GPU device(s)  the previous op happened and queue the allreduce barrier op on the same GPU device
(2) When there is no NCCL op yet, we will try to use a single GPU and separate each process from a single GPU as the best effort.

As for the async work, during wait, we would like not just wait on the NCCL kernel to be completed, but also block the thread until the current stream and nccl stream return.

`test_distributed` should cover the test. I also manually tested both scenarios.

### CODE REVIEW

**Review by ssnl — COMMENTED** [review]
Thank you so much!  This looks good to me, but I will leave it to @pietern to do a review from a professional :)

**Review by pietern — COMMENTED** [review]
The implied behavior of this barrier is:

```
for (auto& work : anyGeneratedWork) {
  work.wait();
}
barrier()
```

In other words, wait for all pending work to complete and then perform a barrier. The behavior is implied for the MPI backend as well. Because all calls are serialized, executing a barrier means all prior work has completed. The behavior is different for Gloo, where a barrier is independent of other operations.

I think we should not mix the expectations here of 1) the barrier being a point in the code that all processes arrived at, and 2) a point by which all prior posted work has executed.

Without the implication, there is no need for the last device tracking and you can simply execute the "lastDevices_.empty()" path of the if statement in the barrier implementation here.

**Comment by teng-li** [comment]
@pietern I disagree, all NCCL/cuda ops are async by nature. Barriers are meant to be used with collectives. By just making a CPU code sync point without considering the collective makes no sense. Think about it as (not exactly the case but close enough), all of your work happens on a different thread, and you would like your barrier sync point to be on your work thread. I would like to keep the current implementation. 

Additionally, test_distributed won't even be able to pass with your proposed approach.

**Review by ssnl — APPROVED** [review]

**Comment by pietern** [comment]
@teng-li It is only the same for MPI because everything is serialized. There is simply no alternative.

I'm fine with these semantics, and I agree they are useful (less code to wait for everything to complete). BUT, then it should also be documented as such, and tested as such. In a test you can kick off some async work, run a barrier, and check that all tensors have the expected results.

I also think there is an alternative approach to this, given the semantic you're looking for, that is more robust. The last devices list assumes that you're using a single NCCL communicator, and that you ensure everything is completed by queuing something against that same communicator. This is only true if you have a single communicator, but breaks down when you have multiple. To fix this, you can keep a map with a single CUDA event per NCCL communicator, that you record immediately after queuing some operation on that communicator. Then when you execute a barrier, you can use a single device communicator, grab a stream, wait for the CUDA events of all other communicators, and then run the allreduce. With this approach nothing can fall through the cracks when using multiple communicators.

This semantic should also be implemented for the Gloo backend.

**Pull request closed without merging**
