### PR TITLE
Simplify c10::string_view implementation

### PR DESCRIPTION
**Pull request by cyyever**
Remove unnecessary code in C++17

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting you change, it is failing internal builds' -c ghfirst

Here is the build error FYI:

```
In file included from xplat/caffe2/c10/util/Exception.h:5:
In file included from xplat/caffe2/c10/util/StringUtil.h:6:
xplat/caffe2/c10/util/string_view.h:576:31: error: out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated [-Werror,-Wdeprecated]
    basic_string_view<CharT>::npos;
```

**Pull request closed without merging**
