### PR TITLE
add --run-parallel 4 to shard1 and shard2 tests

### PR DESCRIPTION
**Pull request by jeffdaily**
Also corrects logic for running tests in the RUN_PARALLEL_BLOCKLIST.

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, provided that CI is green

**Comment by jeffdaily** [comment]
Most tests are passing now.  pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test2 is failing to report results, but tests are passing.

test | before-perf | after perf
-----|-------------|-----------
pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test1 | 2h 18m | 1h 52m
pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test2 | 2h 0m | 1h 26m

**Comment by jithunnair-amd** [comment]
@malfet Can you have one of your team members look into the issue with pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test2 build?

**Comment by jithunnair-amd** [comment]
@jeffdaily At least the latest CI build shows that the ROCm CI error occurs even on a 4 GPU machine.

**Comment by jeffdaily** [comment]
CI job not reporting.  Link: https://ci.pytorch.org/jenkins/job/pytorch-pull-request/208204/

**Pull request closed without merging**
