### PR TITLE
Removing BUILD_C10_EXPERIMENTAL_OPS option and unglobbing experimental/c10d ops

### PR DESCRIPTION
**Pull request by pjh5**

### CODE REVIEW

**Comment by ArutyunovG** [comment]
Hi @pjh5,

BUILD_C10_EXPERIMENTAL option was added to support v140 build.
Is it true, that v140 is not supported anymore from now, and only v141 build is?

Then I'll just write (for internal purposes) building script on v141 and work only with it, and v140 build script should be removed.

cc @peterjc123 on this as well.

**Comment by pjh5** [comment]
@ArutyunovG I eliminated this option because setting it to off broke the build anyways, since there was a hard requirement on some cpp file with c10/experimental. Can you elaborate on your use case more? Was turning this flag off working for you?

**Comment by ArutyunovG** [comment]
@pjh5 


The option was added to support v140 in PR #13550

It was (and, unfortunately is) the only way to avoid errors like this with MSVC <= 1900 (which is <= v140).

```
 "D:\pytorch-scripts\caffe2_builders\v140\pytorch\build\Debug\INSTALL.vcxproj" (целевой объект по умолчанию) (1)
       ->
       "D:\pytorch-scripts\caffe2_builders\v140\pytorch\build\Debug\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (3
       ) ->
       "D:\pytorch-scripts\caffe2_builders\v140\pytorch\build\Debug\caffe2\caffe2.vcxproj" (целевой объект по умолчанию
       ) (13) ->
       (Целевой объект ClCompile) ->
         D:\pytorch-scripts\caffe2_builders\v140\pytorch\c10/util/TypeList.h(160): error C2938: 'extract_type_t<unknown
       -type>' : Failed to specialize alias template (compiling source file D:\pytorch-scripts\caffe2_builders\v140\pyt
       orch\caffe2\operators\experimental\c10\schemas\add.cc) [D:\pytorch-scripts\caffe2_builders\v140\pytorch\build\De
       bug\caffe2\caffe2.vcxproj]
         D:\pytorch-scripts\caffe2_builders\v140\pytorch\c10/util/TypeList.h(160): error C3546: '...': there are no par
       ameter packs available to expand (compiling source file D:\pytorch-scripts\caffe2_builders\v140\pytorch\caffe2\o
       perators\experimental\c10\schemas\add.cc) [D:\pytorch-scripts\caffe2_builders\v140\pytorch\build\Debug\caffe2\ca
       ffe2.vcxproj]
         D:\pytorch-scripts\caffe2_builders\v140\pytorch\c10/util/TypeList.h(42): error C2338: In typelist::to_tuple<T>
       , T must be typelist<...>. (compiling source file D:\pytorch-scripts\caffe2_builders\v140\pytorch\caffe2\operato
       rs\experimental\c10\schemas\add.cc) [D:\pytorch-scripts\caffe2_builders\v140\pytorch\build\Debug\caffe2\caffe2.v
       cxproj]
         D:\pytorch-scripts\caffe2_builders\v140\pytorch\caffe2/core/operator_c10wrapper.h(54): error C2794: 'type': is
        not a member of any direct or indirect base class of 'c10::guts::typelist::to_tuple<int>' (compiling source fil
       e D:\pytorch-scripts\caffe2_builders\v140\pytorch\caffe2\operators\experimental\c10\schemas\add.cc) [D:\pytorch-
       scripts\caffe2_builders\v140\pytorch\build\Debug\caffe2\caffe2.vcxproj]
         D:\pytorch-scripts\caffe2_builders\v140\pytorch\caffe2/core/operator_c10wrapper.h(54): error C2938: 'to_tuple_
       t<int>' : Failed to specialize alias template (compiling source file D:\pytorch-scripts\caffe2_builders\v140\pyt
       orch\caffe2\operators\experimental\c10\schemas\add.cc) [D:\pytorch-scripts\caffe2_builders\v140\pytorch\build\De
       bug\caffe2\caffe2.vcxproj]
```

However, as checked in both CI tests, and on my side, v141 is successfull to build c10 experimental ops.
This seems to be an outdated v140 compiler issue.

To fix build with setting the option to off, all I had to do is to add [the following #ifdef in layer_norm_op.cc](https://github.com/ArutyunovG/pytorch/blob/61484a6d89c4e840aedac1076915e2d4de4d841d/caffe2/operators/layer_norm_op.cc#L210).

However, I didn't contribute the changes yet, because the main thing, why this ssd_infer branch was created for (add support for TF OD API-trained models inference in Caffe2) is not ready yet. 

It is also worth noting the conversation in [this PR](https://github.com/peterjc123/pytorch-scripts/pull/52). After that the #ifdef solution was added, but not submitted as PR yet.

To put all this stuff together, this is a summary: 

- v140 doesn't build c10 experimental ops, because the compiler seems to be outdated. If one is going to support it, there needs to be special care. 
- However, it can be just called deprecated and only v141 is called supported in Windows.

**Comment by ezyang** [comment]
CC @smessmer

**Pull request closed without merging**
