### PR TITLE
Add braces around single line conditional

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85207
* #85206
* #85205
* #85204

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
I thought you said clang didn't allow this?

**Comment by ezyang** [comment]
It actually does; what is specifically the problem is

```
if (cond) foo;
```

turns into

```
if (cond)
  foo;
```

aka clang won't insert braces when it makes it multiline. But if you explicitly add the braces it will preserve them.

**Pull request closed without merging**
