### PR TITLE
fixing trivial reduction & broadcast scheduling

### PR DESCRIPTION
**Pull request by jjsjann123**
cherry-picked fixes from https://github.com/csarofeen/pytorch/pull/1714

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
LGTM Thanks Jie.

**Review by davidberard98 — APPROVED** [review]
mirroring stamp in case it's needed for GH1

**Comment by csarofeen** [comment]
This fix is to avoid putting cases like in the python/C++ test into a single kernel. The issue is trying to generate a kernel where a broadcast dimension cannot be understand to be broadcasting to a single size. Today we rely on proving a dimension is definitely the same by interactions through pointwise operations. We can definitely alleviate this constraint in the future, but for now the protection added in this PR will make it safe by segmenting the broadcasts into different kernels.

**Comment by jjsjann123** [comment]
Saw a bunch of unexpected success from test_meta.py. Am I on a bad commit?

**Comment by davidberard98** [comment]
Yes those are expected I think, you can see in https://hud.pytorch.org/ that the base commit also has those failures

**Comment by jjsjann123** [comment]
Tests looks clean to me (except the unexpected success failures)

**Pull request closed without merging**
