### PR TITLE
Restore support for dim=None on WeightNorm.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
CC @mcarilli

**Comment by mcarilli** [comment]
@ezyang Thanks for catching this!  Since this is a common case (and wasn't caught by the tests) we should probably update the tests for it.  I can do that if you want.

**Comment by ezyang** [comment]
The tests are crap. @mcarilli, if you want to beef up the tests to actually test that the correct norm is being applied, that would be super helpful.

**Comment by mcarilli** [comment]
Haha understood.  I was trusting the CI.  I'll add some tests based on my offline debugging scripts.

**Review by li-roy — APPROVED** [review]

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
