### PR TITLE
Fix dtype mismatch for unallocated storage deserialization

### LINKED ISSUE #90497: Saving and loading unallocated storage and tensor at the same time can result in incorrect dtype
In #89557, it was shown that the following checks

https://github.com/pytorch/pytorch/blob/b0bd5c4508a8923685965614c2c74e6a8c82f7ba/test/test_serialization.py#L688-L689

did not previously check if a loaded storage's dtype matches the saved storage, and indeed there are some cases where they do not match. I will look into it and fix it

cc @mruberry

### PR DESCRIPTION
**Pull request by kurtamohler**
Fixes #90497

cc @mruberry

### CODE REVIEW

**Comment by mruberry** [comment]
@ezyang I think you might want to check this?

**Review by ezyang — APPROVED** [review]
This special case is just... lol

**Comment by kurtamohler** [comment]
Yeah, I think when I do #91325 I'll hopefully be able to make the serialization code a little less insane

**Pull request closed without merging**
