### PR TITLE
Add autocast support for IPU

### PR DESCRIPTION
**Pull request by charlie-wt**
As part of this, a new `AutocastIPU` dispatch key has been added.

There's an existing PR, #85043, to make `Autocast` a proper per-backend functionality key, but it ran into issues with layering with other functionality keys and went stale.

This has been tested in the out-of-tree IPU PyTorch backend.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good to me.
Any testing that we should be doing on our end?

**Comment by charlie-wt** [comment]
> Sounds good to me. Any testing that we should be doing on our end?

we've got some tests for the ipu stuff in our backend; i was hoping that any non-ipu regressions would be caught by existing unit tests.

i could add an 'expected failure' test for when supplying an invalid device type though, since i've changed the message?

**Review by albanD — APPROVED** [review]
Sounds good then.
Having testing here is always best to catch regressions early. But if not possible, that's fine.

**Comment by charlie-wt** [comment]
@pytorchbot label "topic: not user facing"

(probably better to mention as part of the ipu backend updating in accordance)

**Comment by charlie-wt** [comment]
the remaining test errors all seem to be `AssertionError: Redefinition of test test_refs_are_in_decomp_table_op__refs_logaddexp_cpu` (or `AssertionError: Redefinition of test test_refs_are_in_python_ref_db_op__refs_logaddexp_cpu`)

**Comment by albanD** [comment]
Can you rebase on latest main to make CI pass? (or ask the bot to do it if you prefer).

**Comment by albanD** [comment]
@pytorchbot merge

Hopefully all should be green now!

**Pull request closed without merging**
