### PR TITLE
Revert "Updates assertEqual to use torch.isclose-like logic (#37294)"

### PR DESCRIPTION
**Pull request by jeffdaily**
This reverts commit 9cfc10d52e0d0a8576b0a5a347fa6fa8da86244a.

This is breaking ROCm CI. Notably, TestNCCL.

@mruberry @ezyang @xw285cornell

### CODE REVIEW

**Comment by mruberry** [comment]
I'm confused how the PR that this reverts is affecting test_nccl and ROCm? When I look at the CI it seems like the tensors being compared in test_nccl are very different from each other. Are the tensors actually not that different?

**Comment by sunway513** [comment]
If I'd make a guess, the original failure might due to the following lines that changed the test coverage on ROCm path:
https://github.com/pytorch/pytorch/pull/38689/files#diff-9996665f82f52030836eb8657057cfadL6530
https://github.com/pytorch/pytorch/pull/38689/files#diff-9996665f82f52030836eb8657057cfadL5615
Or this line that changed the tolerance settings on GPUs:
https://github.com/pytorch/pytorch/pull/38689/files#diff-9996665f82f52030836eb8657057cfadR11461
cc @jithunnair-amd

**Comment by mruberry** [comment]
> If I'd make a guess, the original failure might due to the following lines that changed the test coverage on ROCm path:
> https://github.com/pytorch/pytorch/pull/38689/files#diff-9996665f82f52030836eb8657057cfadL6530
> https://github.com/pytorch/pytorch/pull/38689/files#diff-9996665f82f52030836eb8657057cfadL5615
> Or this line that changed the tolerance settings on GPUs:
> https://github.com/pytorch/pytorch/pull/38689/files#diff-9996665f82f52030836eb8657057cfadR11461
> cc @jithunnair-amd

All of these cited changes are in test_torch.py, though, and would have no effect on test_nccl.py.

**Comment by mruberry** [comment]
Looks like the tests in question aren't being wrong because of another failure: 

```
01:30:41 ======================================================================
01:30:41 ERROR: test_backend_full_group (__main__.TestDistBackend)
01:30:41 ----------------------------------------------------------------------
01:30:41 Traceback (most recent call last):
01:30:41   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
01:30:41     self._join_processes(fn)
01:30:41   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
01:30:41     self._check_return_codes(elapsed_time)
01:30:41   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
01:30:41     raise RuntimeError(error)
01:30:41 RuntimeError: Processes 1 2 exited with error code 10
01:30:41 
01:30:41 ----------------------------------------------------------------------
```

**Comment by jithunnair-amd** [comment]
@mruberry Which log is the above snippet from?

**Comment by mruberry** [comment]
> @mruberry Which log is the above snippet from?

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28334/console

The subtest 2 under the rocmdeb-ubuntu16.04 tests, the one that would run the NCCL tests.

**Comment by jithunnair-amd** [comment]
Thanks. The actual reason for the failure is a memory access fault:
```
01:29:11 test_backend_full_group (__main__.TestDistBackend) ... Memory exception on virtual address 0x7f61a970c000, node id 4 : Page not present
01:29:11 GPU address 0x7f61a970c000, node id 0, size in byte 0x1000
01:29:11 Memory is allocated using hsaKmtAllocMemory
01:29:11 CPU address of the memory is 0x7f61a970c000
01:29:11 Memory is mapped to node id: 4 5 6 7 
01:29:11 Memory access fault by GPU node-4 (Agent handle: 0x3c0fa60) on address 0x7f61a970c000. Reason: Page not present or supervisor privilege.
```
@jeffdaily This is most likely same as the known issue being debugged wrt mgpu memory access faults on ROCm.
@mruberry I'm attempting to reproduce the test_nccl failure at https://github.com/pytorch/pytorch/commit/9cfc10d52e0d0a8576b0a5a347fa6fa8da86244a. I'll get back with some details.

**Comment by mruberry** [comment]
> @mruberry I'm attempting to reproduce the test_nccl failure at 9cfc10d. I'll get back with some details.

Cool, when you run the test would you also post the tensor values that are being compared? I'm curious if they actually are different or not.

**Comment by jithunnair-amd** [comment]
I've been able to reproduce the assertion error at commit https://github.com/pytorch/pytorch/commit/9cfc10d52e0d0a8576b0a5a347fa6fa8da86244a. However, it is only reproducible when running the test_nccl suite as a whole, but not when running the same tests individually. This points to a potential issue with RCCL buffers or some other syncing issue. At this point, it doesn't look like commit https://github.com/pytorch/pytorch/commit/9cfc10d52e0d0a8576b0a5a347fa6fa8da86244a is the root cause, it's only manifesting/surfacing the issue. We'll have to debug it further locally.

**Comment by jeffdaily** [comment]
It's important that we fully understand why this commit caused test_nccl.py to fail.  Testing locally I could reproduce.  Blacklisting this test allowed all remaining tests to pass. 
Closing this PR in favor of https://github.com/pytorch/pytorch/pull/38730.

**Comment by jithunnair-amd** [comment]
@mruberry @ezyang I have narrowed down the reason why commit 9cfc10d causes the test_nccl failure: the assertion logic has now changed to comparing tensors on the CPU as opposed to the GPU when `a` is a CUDA tensor and `b` is a CPU tensor:
Post - 9cfc10d: https://github.com/pytorch/pytorch/blob/9cfc10d52e0d0a8576b0a5a347fa6fa8da86244a/torch/testing/_internal/common_utils.py#L932
Pre - 9cfc10d: https://github.com/pytorch/pytorch/blob/6a23214a47a3ee30e9129bad3b38af4c2081d1d4/torch/testing/_internal/common_utils.py#L949

Still debugging the root cause.

**Comment by mruberry** [comment]
@jithunnair-amd that's correct. Tests (like this one?) were and still are relying on assertEqual to synchronize devices for them. This is incorrect, however. In the future we'll probably default the exact_device kwarg to True to ensure that tests perform their own cross-device synchronization or explicitly indicate they don't care about how the synchronization is performed.

**Pull request closed without merging**
