### PR TITLE
Fix CUDA extension ninja build

### PR DESCRIPTION
**Pull request by zasdfgbnm**
I am submitting this PR on behalf of Janne Hellsten(@nurpax) from @NVIDIA, for the convenience of CLA. Thanks Janne a lot for the contribution!

Currently, the ninja build decides whether to rebuild a .cu file or not pretty randomly. And there are actually two issues:

First, the arch list in the building command is ordered randomly. When the order changes, it will unconditionally rebuild regardless of the timestamp.

Second, the header files are not included in the dependency list, so if the header file changes, it is possible that ninja will not rebuild.

This PR fixes both issues. The fix for the second issue requires nvcc >= 10.2. nvcc < 10.2 can still build CUDA extension as it used to be, but it will be unable to see the changes in header files.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Any way to test this?

**Comment by zasdfgbnm** [comment]
@ezyang I don't think there is a clean way to test it. The gcc dependency is tested either IIUC. It is possible to write some shell script to do the test, but it can be very messy, and I don't suggest doing so.

**Comment by zasdfgbnm** [comment]
Looks mypy is failing

```python
Traceback (most recent call last):
  File "test_type_hints.py", line 217, in test_run_mypy
    self.fail(f"mypy failed: {stdout} {stderr}")
AssertionError: mypy failed: torch/utils/cpp_extension.py:23: error: Module 'pkg_resources' has no attribute 'packaging'  [attr-defined]
Found 1 error in 1 file (checked 1165 source files)
```

**Comment by zasdfgbnm** [comment]
@ezyang This was breaking ROCm CI, and I fixed it in my most recent commit https://github.com/pytorch/pytorch/pull/49344/commits/36c79f4637974b650cffb776dffcca8b47e0f4d3, this PR should be in good state now.

**Pull request closed without merging**
