### PR TITLE
Revert "Revert "Build and run Metal tests in CI (#86062)""

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #86073

This reverts commit 195184e69cda79678590c759719b1dc1d7ef6d09.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
Failure is fairly benign but don't know why we didn't catch this in OSS: 

```
stderr: **redacted**/aten/src/ATen/native/metal/mpscnn/MPSImageWrapper.mm:26:10: error: ARC forbids explicit message send of 'dealloc'
  [super dealloc];
   ~~~~~ ^
```

**Pull request closed without merging**
