### PR TITLE
Canonicalize includes in aten, and add tests for it

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #36303 Canonicalize includes in torch, and add tests for it
* **#36301 Canonicalize includes in aten, and add tests for it**

Differential Revision: [D20943004](https://our.internmc.facebook.com/intern/diff/D20943004)

### CODE REVIEW

**Comment by ezyang** [comment]
Some of these are incorrect (only seeing the error in internal CI):

```
xplat/caffe2/aten/src/ATen/native/quantized/cpu/qnnpack/src/requantization/gemmlowp-scalar.c:16:10: error: 'gemmlowp-scalar.h' file not found with <angled> include; use "quotes" instead
#include <gemmlowp-scalar.h>
```

**Comment by zasdfgbnm** [comment]
@ezyang Should be working this time

**Comment by ezyang** [comment]
RIP. Looks like the paths are not what we expect them to be:

```
xplat/caffe2/aten/src/ATen/native/quantized/cpu/qnnpack/src/requantization/gemmlowp-scalar.c:16:10: fatal error: 'ATen/native/quantized/cpu/qnnpack/src/requantization/gemmlowp-scalar.h' file not found
#include <ATen/native/quantized/cpu/qnnpack/src/requantization/gemmlowp-scalar.h>
```

**Comment by ezyang** [comment]
This is going to need internal build system changes, but I don't know when I'm going to have time to look at this. Maybe you can find someone else to push this through?

**Comment by zasdfgbnm** [comment]
@ezyang If the effort is more than a simple find and replace, then I am not sure if we still want to canonicalize the include as the benefit is not large. But what I can do to this PR is, instead of requiring all includes to be `#include <`, we only disallow `#include "ATen/native/...."` style include, but still allowing `#include "gemmlowp-scalar.h"` style, that sounds like the most reasonable approach.

**Comment by ezyang** [comment]
It's not a simple find and replace; I think that the cpp files in these subdirectories aren't having their include paths rooted in the same place as everything else. @AshkanAliabadi  would probably be able to say best.

**Comment by AshkanAliabadi** [comment]
Yeah the files in there don't have their include search paths rooted in ATen.  I think our internal builds can be massaged to take handle this though.

**Comment by zasdfgbnm** [comment]
@ezyang I have reverted all changes in qnnpack, and exclude it from quick checks. I think for now this is a safe option.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
